"""
air_permitting_data.py — live EPA + embedded FLM snapshot.
Generated by upgrade_air_permitting.py on 2026-04-15 01:50 UTC.

Replace the inline dicts in main.py with:

    from air_permitting_data import (
        NONATTAINMENT as _AP_NONATTAINMENT,
        MONITORS     as _AP_MONITORS,
        CLASS1       as _AP_CLASS1,
    )

Counts at generation:
  - nonattainment areas: 113
  - Class I areas:       83
  - AQS monitors:        0

Sources:
  - EPA Green Book ArcGIS (gispub.epa.gov/arcgis/rest/services/OAR_OAQPS)
  - 40 CFR 81 Class I legal list (embedded)
  - EPA AQS Data Mart API (if EPA_AQS_API_KEY set)
"""

NONATTAINMENT = {
  "ozone": [
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.26155875921346,
          -122.09498969448454
        ],
        [
          40.262546262884136,
          -122.09217937440695
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          42.418812000669206,
          -86.27355099957315
        ],
        [
          42.76893700028984,
          -85.89498200056235
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.217543015949225,
          -121.02783893361186
        ],
        [
          38.70904295981796,
          -120.07233205299259
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          33.29756103173433,
          -85.04702808227415
        ],
        [
          34.412876937584606,
          -83.79888701452514
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          41.75948995056982,
          -86.82482896412982
        ],
        [
          42.2435910357569,
          -86.22252096916677
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.29473895593623,
          -122.07158824895653
        ],
        [
          40.152032960186034,
          -121.0766970047478
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          37.83191604350188,
          -120.99552299707307
        ],
        [
          38.509990969531806,
          -120.01993199565827
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.83496695836549,
          -84.89756606011224
        ],
        [
          39.14735897015048,
          -84.29522196410373
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.770398931089844,
          -84.82027199023565
        ],
        [
          39.59005900649983,
          -83.97719907792525
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.90650292155683,
          -82.34803706408893
        ],
        [
          41.85337997362986,
          -80.99972898586809
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.554390953070396,
          -83.26063798667722
        ],
        [
          40.44391398204524,
          -82.18282497347535
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          32.052085018427896,
          -98.06682897762266
        ],
        [
          33.43406401998822,
          -96.07553405864347
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          41.723558989063584,
          -84.15820001276977
        ],
        [
          43.16884395990803,
          -82.41839608337827
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          28.825049030500608,
          -96.08903695907252
        ],
        [
          30.63027907275208,
          -94.34675002964183
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          32.61859149028363,
          -116.10626649471683
        ],
        [
          33.433750489588434,
          -114.46251149282045
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          34.81772573558954,
          -118.79839611159176
        ],
        [
          35.79263449305124,
          -117.63021749638858
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          34.03247148996475,
          -118.79812124058948
        ],
        [
          35.16652488725964,
          -115.74909749388267
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          35.826905144281035,
          -115.70610828807608
        ],
        [
          36.665444558154675,
          -114.85132361450344
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          32.803119489327294,
          -118.94486249752116
        ],
        [
          34.8181334906431,
          -116.51831111038236
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.18001204405565,
          -86.03317801718416
        ],
        [
          38.60672501062845,
          -85.41527204932684
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          37.805818971833375,
          -85.94853990994115
        ],
        [
          38.52391405409397,
          -85.28303007359472
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          37.183108492736636,
          -120.39165349927924
        ],
        [
          37.90312149394621,
          -119.30899549805092
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          43.117395000036595,
          -86.46127800003894
        ],
        [
          43.4724870004052,
          -86.06647000022855
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.005187495905616,
          -121.27976749976096
        ],
        [
          39.52683849718857,
          -120.36232833369742
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.41430701570475,
          -112.68733636318417
        ],
        [
          41.364596955856534,
          -111.55309306760101
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          32.94200000142423,
          -113.1280999999054
        ],
        [
          34.04809999843946,
          -111.03990000147304
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          33.42589349001037,
          -116.72032666704499
        ],
        [
          34.03382686549979,
          -115.24342570542174
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.018422494050526,
          -122.42204850099313
        ],
        [
          39.31639249615178,
          -120.00514349825976
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          32.5341564884396,
          -117.59589649588116
        ],
        [
          33.50502648980025,
          -116.08104249503818
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          36.89332949283241,
          -123.02382650161664
        ],
        [
          38.86424549489397,
          -121.2081565002568
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          34.790583491117474,
          -121.58626950005632
        ],
        [
          38.29791549406127,
          -117.98076249638744
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          34.89747549143997,
          -120.39999999990893
        ],
        [
          35.78939339881426,
          -119.47251549863918
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.77632571446621,
          -112.21437699079739
        ],
        [
          40.51907350773291,
          -111.53322727335201
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.194279999658164,
          -121.82871300036052
        ],
        [
          39.208094999662784,
          -121.81107299962027
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          37.63412895297672,
          -120.65225694610845
        ],
        [
          38.43337898917613,
          -119.19360596196464
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.46149907335829,
          -110.80866406321499
        ],
        [
          40.6441659460631,
          -109.04840703271978
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          34.04553448989312,
          -119.47802349724422
        ],
        [
          34.90127549173201,
          -118.63229949663018
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          32.655600000471,
          -114.75848471918704
        ],
        [
          32.745932490197305,
          -114.56388472195721
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          33.85673049663449,
          -116.92077971206872
        ],
        [
          34.01944416241869,
          -116.71967347505245
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          33.42789397887672,
          -117.28361179396357
        ],
        [
          33.7208988477217,
          -117.0307506642601
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          29.114435019070555,
          -98.80655303526434
        ],
        [
          29.760618037129166,
          -98.11690297724334
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.71271798685941,
          -77.3116509194873
        ],
        [
          39.72149303838715,
          -76.06046798457407
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          41.27788607201074,
          -73.51806507780032
        ],
        [
          42.05058793191204,
          -71.78699393429221
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.98060098172835,
          -73.72777595018147
        ],
        [
          41.666830062178384,
          -72.3055309328292
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.079129935934716,
          -75.20367890379458
        ],
        [
          41.35742396767371,
          -73.90240592436429
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.495864939713435,
          -74.25564107942054
        ],
        [
          41.36637603820722,
          -71.85615006222916
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.29001196326999,
          -75.7887579942505
        ],
        [
          39.839006994134685,
          -75.42341804734347
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.363109034637716,
          -76.23327799467774
        ],
        [
          39.72208804914305,
          -75.76666805279828
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.92877107220274,
          -75.55978999988399
        ],
        [
          40.42444392673347,
          -74.03136598168464
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.721413982182725,
          -76.13689995751864
        ],
        [
          40.608580033431686,
          -74.72150408223584
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.80182602883548,
          -77.11990101504297
        ],
        [
          38.995109924492716,
          -76.90939607072313
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.2550830133991,
          -77.67726196399148
        ],
        [
          39.72010094721118,
          -76.38079202503677
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.49966001183797,
          -77.9619879817393
        ],
        [
          39.32465897160258,
          -77.03177891926043
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.087970095078084,
          -90.37408199566316
        ],
        [
          39.00004700976213,
          -89.59508405278666
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.003504944582396,
          -90.96446102725454
        ],
        [
          38.96776399860973,
          -90.10910699249364
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          42.49276599674597,
          -87.95339505713582
        ],
        [
          42.66957093605009,
          -87.80552419956796
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          43.54311804201932,
          -87.86071277637382
        ],
        [
          43.892527463070465,
          -87.69554714303342
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          42.66774495476547,
          -88.54021029879405
        ],
        [
          43.54343799524724,
          -87.75753406318448
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          43.89147223016504,
          -87.831602601894
        ],
        [
          44.32764890760105,
          -87.50669689901788
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          44.79428679739343,
          -87.4063332877546
        ],
        [
          45.42854484498261,
          -86.80519680192327
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          41.43414900000011,
          -87.52594799999972
        ],
        [
          41.718939000000006,
          -86.92935299999999
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          41.201298000102746,
          -88.70727699993348
        ],
        [
          42.49619999983037,
          -87.52461292432363
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          45.21175454496452,
          -87.01928308483896
        ],
        [
          45.274508441866104,
          -86.97279050691645
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.12426599957644,
          -105.90422300009116
        ],
        [
          41.00205496365089,
          -103.56132699964103
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          31.783148000000153,
          -106.69999999999997
        ],
        [
          31.825000000000156,
          -106.52702999999997
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          31.387229694019606,
          -106.64564592146696
        ],
        [
          32.00244892060761,
          -105.95432899764009
        ]
      ]
    }
  ],
  "pm25": [
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.195893415269,
          -76.67813869765715
        ],
        [
          40.555195645146746,
          -76.1514424564352
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.194351215892794,
          -80.3608709223281
        ],
        [
          40.67456172545655,
          -79.68877920765034
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.80179748523279,
          -75.60163890613894
        ],
        [
          40.06638860867779,
          -75.21044106477606
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          47.38458537697423,
          -116.32859122329273
        ],
        [
          47.68887782059086,
          -115.98599218514636
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          41.0635547243204,
          -82.34805479121371
        ],
        [
          41.6315937138211,
          -81.37475466584331
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.67659995672029,
          -120.77110005712423
        ],
        [
          39.89359995394945,
          -120.39460005917341
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          32.642399971554745,
          -115.79830006195819
        ],
        [
          33.07509997171289,
          -115.36630006282805
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          34.79039996366644,
          -121.58509099158519
        ],
        [
          38.3002572134986,
          -117.9807731827957
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          32.75004479533847,
          -118.95173319636127
        ],
        [
          34.817977004583646,
          -116.5173916579315
        ]
      ]
    }
  ],
  "pm10": [
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.41836013106178,
          -75.89182990186525
        ],
        [
          40.968215251734506,
          -75.05122264511682
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          33.01855019128553,
          -87.33558191644957
        ],
        [
          33.8431413542942,
          -86.34153962882108
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.634908929455854,
          -81.65020470500504
        ],
        [
          40.988608010086644,
          -81.08670454851797
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          37.967107419498326,
          -82.06470368538477
        ],
        [
          38.68405454815859,
          -81.19428041598769
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.29496617320726,
          -122.0730783691628
        ],
        [
          39.88851521619091,
          -121.33511219815104
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.906507990535225,
          -82.34820398054688
        ],
        [
          41.85474918538341,
          -81.00000354041923
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          41.723508032984185,
          -84.15820465512407
        ],
        [
          43.168640351280665,
          -82.41906713477972
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          64.71912993617646,
          -148.01697217617445
        ],
        [
          64.97894485644704,
          -147.1749699603477
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          32.64241184954284,
          -115.79829059860187
        ],
        [
          33.0751359075561,
          -115.36634952832956
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.24286497857659,
          -79.27699296223011
        ],
        [
          40.72598807828588,
          -78.34865168243715
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          42.140733384304234,
          -121.91401970514168
        ],
        [
          42.31647739378572,
          -121.62010164200314
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          35.460641804729676,
          -84.58454124778746
        ],
        [
          36.30170597565603,
          -83.65139499425449
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.721207966115145,
          -76.7218581305715
        ],
        [
          40.31561108709532,
          -75.87396386324646
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.276427936452144,
          -79.90107313960333
        ],
        [
          40.349186950528455,
          -79.82874111584526
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          42.6108079500675,
          -88.54230999218336
        ],
        [
          43.19604003452581,
          -87.75800574603777
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          31.33272389034056,
          -111.00065560596235
        ],
        [
          31.471222917154567,
          -110.85825157770834
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          43.72428042701404,
          -122.54841105956315
        ],
        [
          43.7673154374123,
          -122.41075103799044
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.76281083361745,
          -80.5194913105528
        ],
        [
          41.17313311029493,
          -78.97490285641561
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.77605695104337,
          -112.21438768112861
        ],
        [
          40.518953057462646,
          -111.53606749022127
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          36.89067796929845,
          -123.1069272666367
        ],
        [
          38.86435107853094,
          -121.20646289709205
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          34.81112293218286,
          -121.58595106620405
        ],
        [
          38.29800513371277,
          -117.98014724489398
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          47.04318463931523,
          -122.61857777094966
        ],
        [
          47.30272264086871,
          -122.23482171248051
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.01850805323276,
          -122.12484719588102
        ],
        [
          39.05300917765391,
          -120.57733300011652
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          38.73450413703085,
          -121.94941727055529
        ],
        [
          39.454698208844896,
          -121.13316915928404
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.03366497172944,
          -112.68670770078467
        ],
        [
          41.904020187494666,
          -111.55310458533366
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          33.38660484813949,
          -118.94350324799903
        ],
        [
          34.81782893648279,
          -116.51736778889087
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.71970793861718,
          -77.62753542029938
        ],
        [
          40.65954313403027,
          -76.15180896220583
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          32.76769116951639,
          -112.20373343095346
        ],
        [
          33.08777509747927,
          -111.87760833966881
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          41.99769722985171,
          -112.08995987383437
        ],
        [
          42.31442125389046,
          -111.70109979921091
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          41.46845416056586,
          -112.16600288519834
        ],
        [
          41.999118855565165,
          -111.77309772867241
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.9820898243239,
          -73.72777718365577
        ],
        [
          41.66659518486159,
          -72.53660085663897
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.07901009552732,
          -74.94290363322838
        ],
        [
          41.20520330239581,
          -73.90240720814379
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.49669359537198,
          -74.76243659035875
        ],
        [
          41.666744442189845,
          -71.85664062580116
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.289887898957105,
          -75.78875980257287
        ],
        [
          39.839015007036075,
          -75.42341974823955
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.496500491333,
          -75.55979173338206
        ],
        [
          40.18390811145478,
          -74.39005136994918
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          39.72141894392689,
          -76.13670792188317
        ],
        [
          40.60848817858169,
          -74.72200149780646
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.15504787593109,
          -80.9417514699578
        ],
        [
          40.59934995683011,
          -80.59479744729751
        ]
      ]
    },
    {
      "name": "Unknown",
      "class": "Moderate",
      "bounds": [
        [
          40.15960788714494,
          -80.6818721841513
        ],
        [
          40.638694429245525,
          -80.51790334113174
        ]
      ]
    }
  ]
}


CLASS1 = [
  {
    "name": "Acadia NP",
    "lat": 44.35,
    "lon": -68.21,
    "state": "ME"
  },
  {
    "name": "Arches NP",
    "lat": 38.73,
    "lon": -109.59,
    "state": "UT"
  },
  {
    "name": "Badlands NP",
    "lat": 43.85,
    "lon": -102.34,
    "state": "SD"
  },
  {
    "name": "Big Bend NP",
    "lat": 29.25,
    "lon": -103.25,
    "state": "TX"
  },
  {
    "name": "Bryce Canyon NP",
    "lat": 37.59,
    "lon": -112.19,
    "state": "UT"
  },
  {
    "name": "Canyonlands NP",
    "lat": 38.33,
    "lon": -109.88,
    "state": "UT"
  },
  {
    "name": "Capitol Reef NP",
    "lat": 38.37,
    "lon": -111.27,
    "state": "UT"
  },
  {
    "name": "Carlsbad Caverns NP",
    "lat": 32.17,
    "lon": -104.44,
    "state": "NM"
  },
  {
    "name": "Crater Lake NP",
    "lat": 42.94,
    "lon": -122.11,
    "state": "OR"
  },
  {
    "name": "Denali NP",
    "lat": 63.33,
    "lon": -150.5,
    "state": "AK"
  },
  {
    "name": "Everglades NP",
    "lat": 25.29,
    "lon": -80.89,
    "state": "FL"
  },
  {
    "name": "Glacier NP",
    "lat": 48.7,
    "lon": -113.72,
    "state": "MT"
  },
  {
    "name": "Grand Canyon NP",
    "lat": 36.1,
    "lon": -112.11,
    "state": "AZ"
  },
  {
    "name": "Grand Teton NP",
    "lat": 43.79,
    "lon": -110.68,
    "state": "WY"
  },
  {
    "name": "Great Smoky Mountains NP",
    "lat": 35.61,
    "lon": -83.51,
    "state": "TN"
  },
  {
    "name": "Guadalupe Mountains NP",
    "lat": 31.92,
    "lon": -104.87,
    "state": "TX"
  },
  {
    "name": "Haleakala NP",
    "lat": 20.72,
    "lon": -156.17,
    "state": "HI"
  },
  {
    "name": "Hawaii Volcanoes NP",
    "lat": 19.42,
    "lon": -155.29,
    "state": "HI"
  },
  {
    "name": "Isle Royale NP",
    "lat": 48.1,
    "lon": -88.55,
    "state": "MI"
  },
  {
    "name": "Kings Canyon NP",
    "lat": 36.89,
    "lon": -118.56,
    "state": "CA"
  },
  {
    "name": "Lassen Volcanic NP",
    "lat": 40.49,
    "lon": -121.51,
    "state": "CA"
  },
  {
    "name": "Mammoth Cave NP",
    "lat": 37.19,
    "lon": -86.1,
    "state": "KY"
  },
  {
    "name": "Mesa Verde NP",
    "lat": 37.23,
    "lon": -108.46,
    "state": "CO"
  },
  {
    "name": "Mount Rainier NP",
    "lat": 46.88,
    "lon": -121.73,
    "state": "WA"
  },
  {
    "name": "North Cascades NP",
    "lat": 48.77,
    "lon": -121.2,
    "state": "WA"
  },
  {
    "name": "Olympic NP",
    "lat": 47.8,
    "lon": -123.6,
    "state": "WA"
  },
  {
    "name": "Petrified Forest NP",
    "lat": 34.91,
    "lon": -109.81,
    "state": "AZ"
  },
  {
    "name": "Redwood NP",
    "lat": 41.3,
    "lon": -124.0,
    "state": "CA"
  },
  {
    "name": "Rocky Mountain NP",
    "lat": 40.34,
    "lon": -105.68,
    "state": "CO"
  },
  {
    "name": "Sequoia NP",
    "lat": 36.49,
    "lon": -118.68,
    "state": "CA"
  },
  {
    "name": "Shenandoah NP",
    "lat": 38.53,
    "lon": -78.35,
    "state": "VA"
  },
  {
    "name": "Theodore Roosevelt NP",
    "lat": 46.98,
    "lon": -103.53,
    "state": "ND"
  },
  {
    "name": "Virgin Islands NP",
    "lat": 18.33,
    "lon": -64.73,
    "state": "VI"
  },
  {
    "name": "Voyageurs NP",
    "lat": 48.5,
    "lon": -92.88,
    "state": "MN"
  },
  {
    "name": "Wind Cave NP",
    "lat": 43.57,
    "lon": -103.48,
    "state": "SD"
  },
  {
    "name": "Yellowstone NP",
    "lat": 44.43,
    "lon": -110.59,
    "state": "WY"
  },
  {
    "name": "Yosemite NP",
    "lat": 37.85,
    "lon": -119.54,
    "state": "CA"
  },
  {
    "name": "Zion NP",
    "lat": 37.3,
    "lon": -113.05,
    "state": "UT"
  },
  {
    "name": "Boundary Waters Canoe Area",
    "lat": 47.9,
    "lon": -91.5,
    "state": "MN"
  },
  {
    "name": "Bob Marshall Wilderness",
    "lat": 47.7,
    "lon": -113.4,
    "state": "MT"
  },
  {
    "name": "Bridger Wilderness",
    "lat": 42.8,
    "lon": -109.55,
    "state": "WY"
  },
  {
    "name": "Caney Creek Wilderness",
    "lat": 34.53,
    "lon": -94.05,
    "state": "AR"
  },
  {
    "name": "Cape Romain Wilderness",
    "lat": 33.0,
    "lon": -79.63,
    "state": "SC"
  },
  {
    "name": "Chiricahua Wilderness",
    "lat": 31.85,
    "lon": -109.3,
    "state": "AZ"
  },
  {
    "name": "Cloud Peak Wilderness",
    "lat": 44.37,
    "lon": -107.17,
    "state": "WY"
  },
  {
    "name": "Dolly Sods Wilderness",
    "lat": 39.0,
    "lon": -79.3,
    "state": "WV"
  },
  {
    "name": "Eagles Nest Wilderness",
    "lat": 39.7,
    "lon": -106.33,
    "state": "CO"
  },
  {
    "name": "Flat Tops Wilderness",
    "lat": 40.02,
    "lon": -107.13,
    "state": "CO"
  },
  {
    "name": "Galiuro Wilderness",
    "lat": 32.55,
    "lon": -110.27,
    "state": "AZ"
  },
  {
    "name": "Great Sand Dunes Wilderness",
    "lat": 37.78,
    "lon": -105.59,
    "state": "CO"
  },
  {
    "name": "Hercules-Glades Wilderness",
    "lat": 36.7,
    "lon": -93.0,
    "state": "MO"
  },
  {
    "name": "James River Face Wilderness",
    "lat": 37.6,
    "lon": -79.4,
    "state": "VA"
  },
  {
    "name": "La Garita Wilderness",
    "lat": 37.8,
    "lon": -106.98,
    "state": "CO"
  },
  {
    "name": "Linville Gorge Wilderness",
    "lat": 35.92,
    "lon": -81.92,
    "state": "NC"
  },
  {
    "name": "Lye Brook Wilderness",
    "lat": 43.1,
    "lon": -73.0,
    "state": "VT"
  },
  {
    "name": "Maroon Bells-Snowmass Wilderness",
    "lat": 39.07,
    "lon": -107.07,
    "state": "CO"
  },
  {
    "name": "Mazatzal Wilderness",
    "lat": 34.03,
    "lon": -111.45,
    "state": "AZ"
  },
  {
    "name": "Mesa Verde Wilderness",
    "lat": 37.2,
    "lon": -108.47,
    "state": "CO"
  },
  {
    "name": "Mingo Wilderness",
    "lat": 36.98,
    "lon": -90.15,
    "state": "MO"
  },
  {
    "name": "Mokelumne Wilderness",
    "lat": 38.6,
    "lon": -120.07,
    "state": "CA"
  },
  {
    "name": "Mount Zirkel Wilderness",
    "lat": 40.87,
    "lon": -106.7,
    "state": "CO"
  },
  {
    "name": "Otter Creek Wilderness",
    "lat": 38.8,
    "lon": -79.7,
    "state": "WV"
  },
  {
    "name": "Pecos Wilderness",
    "lat": 35.88,
    "lon": -105.58,
    "state": "NM"
  },
  {
    "name": "Pine Mountain Wilderness",
    "lat": 34.4,
    "lon": -111.95,
    "state": "AZ"
  },
  {
    "name": "Presidential Range Wilderness",
    "lat": 44.27,
    "lon": -71.3,
    "state": "NH"
  },
  {
    "name": "Rainbow Lake Wilderness",
    "lat": 46.5,
    "lon": -91.1,
    "state": "WI"
  },
  {
    "name": "Rawah Wilderness",
    "lat": 40.72,
    "lon": -105.92,
    "state": "CO"
  },
  {
    "name": "Red Rock Lakes Wilderness",
    "lat": 44.6,
    "lon": -111.8,
    "state": "MT"
  },
  {
    "name": "Saguaro Wilderness",
    "lat": 32.25,
    "lon": -110.5,
    "state": "AZ"
  },
  {
    "name": "San Gorgonio Wilderness",
    "lat": 34.1,
    "lon": -116.83,
    "state": "CA"
  },
  {
    "name": "San Jacinto Wilderness",
    "lat": 33.8,
    "lon": -116.68,
    "state": "CA"
  },
  {
    "name": "San Pedro Parks Wilderness",
    "lat": 36.15,
    "lon": -106.88,
    "state": "NM"
  },
  {
    "name": "Selway-Bitterroot Wilderness",
    "lat": 46.1,
    "lon": -115.0,
    "state": "ID"
  },
  {
    "name": "Sipsey Wilderness",
    "lat": 34.33,
    "lon": -87.43,
    "state": "AL"
  },
  {
    "name": "Swanquarter Wilderness",
    "lat": 35.38,
    "lon": -76.23,
    "state": "NC"
  },
  {
    "name": "Sycamore Canyon Wilderness",
    "lat": 35.05,
    "lon": -112.07,
    "state": "AZ"
  },
  {
    "name": "Thousand Lakes Wilderness",
    "lat": 40.7,
    "lon": -121.53,
    "state": "CA"
  },
  {
    "name": "Three Sisters Wilderness",
    "lat": 44.1,
    "lon": -121.77,
    "state": "OR"
  },
  {
    "name": "Upper Buffalo Wilderness",
    "lat": 35.88,
    "lon": -93.25,
    "state": "AR"
  },
  {
    "name": "Weminuche Wilderness",
    "lat": 37.72,
    "lon": -107.43,
    "state": "CO"
  },
  {
    "name": "West Elk Wilderness",
    "lat": 38.72,
    "lon": -107.25,
    "state": "CO"
  },
  {
    "name": "Wichita Mountains Wilderness",
    "lat": 34.73,
    "lon": -98.7,
    "state": "OK"
  },
  {
    "name": "Wolf Island Wilderness",
    "lat": 31.35,
    "lon": -81.3,
    "state": "GA"
  }
]


MONITORS = []

