"""
news_slug_route.py - /news/<slug> Flask route, registered from main.py.

Renders any row from the press_releases table as a polished HTML page.

Phase EE (2026-05-12): visual + distribution upgrade. The user reported
"daily cron news articles are ugly." Three concrete improvements:

  1. Schema.org PressRelease JSON-LD + full OG/Twitter cards so the
     page becomes AI-citable and link-preview-friendly.
  2. Data-stat cards rendered from auto_press_releases.source_data
     when the row was generated by the marketing engine — turns
     "wall of text" into a magazine-style data brief.
  3. Share buttons (LinkedIn, X, Email, Copy-link) at the bottom so a
     reader can amplify in one click.
  4. "Subscribe to the DC Hub Daily Brief" CTA — drops them into the
     existing /api/v1/digest/subscribe pipeline.

Body rendering: now handles Markdown-style ## H2 headings, > blockquotes,
- bullet lists, and **bold** so Claude's output renders structured
instead of as one block of plain text.
"""
import html as _html
import json as _json
import re as _re


def _format_date(date_val):
    if not date_val: return ""
    try:
        if hasattr(date_val, "strftime"):
            return date_val.strftime("%B %d, %Y")
        # Try parse ISO date string
        if isinstance(date_val, str) and len(date_val) >= 10:
            from datetime import datetime
            try:
                d = datetime.fromisoformat(date_val[:10])
                return d.strftime("%B %d, %Y")
            except Exception:
                pass
        return str(date_val)
    except Exception:
        return str(date_val)


def _body_to_html(body_text):
    """Rich Markdown-lite renderer for press release bodies.

    Handles (in order of detection per paragraph):
      ## Section heading      → <h2>
      ### Subsection          → <h3>
      > pull-quote text       → <blockquote>
      - bullet                → <ul><li>
      1. numbered             → <ol><li>
      "quoted attribution"    → <blockquote>
      anything else           → <p> with **bold** → <strong>
    """
    if not body_text:
        return ""
    paragraphs = [p.strip() for p in body_text.split("\n\n") if p.strip()]
    out = []
    for p in paragraphs:
        # H2
        if p.startswith("## "):
            out.append("<h2>" + _html.escape(p[3:].strip()) + "</h2>")
            continue
        if p.startswith("### "):
            out.append("<h3>" + _html.escape(p[4:].strip()) + "</h3>")
            continue
        # Blockquote (full paragraph starts with >)
        if p.startswith("> "):
            text = "\n".join(line.lstrip("> ").rstrip()
                              for line in p.split("\n"))
            out.append("<blockquote>" + _format_inline(text) + "</blockquote>")
            continue
        # Bullet list (lines starting with - or *)
        lines = p.split("\n")
        if all(l.lstrip().startswith(("- ", "* ", "• "))
               or l.strip() == "" for l in lines if l.strip()):
            items = [l.lstrip().lstrip("-*• ").strip()
                     for l in lines if l.strip()]
            out.append("<ul>" + "".join(
                "<li>" + _format_inline(i) + "</li>" for i in items
            ) + "</ul>")
            continue
        # Numbered list
        if all(_re.match(r"^\s*\d+\.\s", l)
               for l in lines if l.strip()):
            items = [_re.sub(r"^\s*\d+\.\s+", "", l).strip()
                     for l in lines if l.strip()]
            out.append("<ol>" + "".join(
                "<li>" + _format_inline(i) + "</li>" for i in items
            ) + "</ol>")
            continue
        # Heuristic: pull quotes (starts with " or — DC Hub said)
        first = p.lstrip()[:15].lower()
        if first.startswith(('"', '"', "'", "'")) or first.startswith("quote from"):
            out.append("<blockquote>" + _format_inline(p) + "</blockquote>")
            continue
        # Default paragraph
        out.append("<p>" + _format_inline(p) + "</p>")
    return "\n".join(out)


def _format_inline(text):
    """Inline markdown: **bold**, *italic*, `code`, [link](url). Escape first."""
    esc = _html.escape(text)
    # Links: [text](url) — only http/https for safety
    esc = _re.sub(
        r'\[([^\]]+)\]\((https?://[^)\s]+)\)',
        lambda m: f'<a href="{m.group(2)}">{m.group(1)}</a>',
        esc,
    )
    # **bold**
    esc = _re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', esc)
    # *italic* (after bold to avoid eating bold markers)
    esc = _re.sub(r'(?<!\*)\*([^*\n]+)\*(?!\*)', r'<em>\1</em>', esc)
    # `code`
    esc = _re.sub(r'`([^`\n]+)`', r'<code>\1</code>', esc)
    # Newlines inside a paragraph → <br>
    esc = esc.replace("\n", "<br>")
    return esc


def _render_stat_cards(source_data):
    """Render top BUILD / AVOID markets + AI adoption headline numbers
       as a magazine-style data block above the body. Only fires when
       the row was generated by the marketing engine and source_data
       carries the signal payload."""
    if not isinstance(source_data, dict):
        return ""
    cards = []
    ai = source_data.get("ai_usage_24h") or {}
    calls = ai.get("tool_calls", 0)
    callers = ai.get("unique_callers", 0)
    if calls > 0:
        cards.append(_stat_card(
            "AI usage / 24h",
            f"{calls:,}",
            f"{callers:,} unique AI agents · MCP tool calls"
        ))
    build = source_data.get("top_build_markets") or []
    if build:
        first = build[0]
        cards.append(_stat_card(
            "Top BUILD market",
            _html.escape(first.get("market", "?")),
            f"Excess {first.get('excess', 0):.1f} · Constraint {first.get('constraint', 0):.1f} · {_html.escape(first.get('iso','?'))}"
        ))
    avoid = source_data.get("top_avoid_markets") or []
    if avoid:
        first = avoid[0]
        cards.append(_stat_card(
            "Top AVOID market",
            _html.escape(first.get("market", "?")),
            f"Constraint {first.get('constraint', 0):.1f} · {_html.escape(first.get('iso','?'))}",
            color="amber"
        ))
    if not cards:
        return ""
    return ('<div class="stat-cards">' + "".join(cards) + '</div>')


def _stat_card(label, big, sub, color="indigo"):
    color_var = {"indigo": "#8b6fff", "amber": "#f59e0b",
                 "green": "#10b981", "red": "#ef4444"}.get(color, "#8b6fff")
    return (
        f'<div class="stat-card" style="border-left-color:{color_var}">'
        f'<div class="stat-label">{_html.escape(label)}</div>'
        f'<div class="stat-big">{big}</div>'
        f'<div class="stat-sub">{sub}</div>'
        f'</div>'
    )


def _build_jsonld(title, subheadline, body, slug, date_human, source):
    """Schema.org PressRelease JSON-LD — what makes the page citable by
       AI agents + Google News + LinkedIn link previews."""
    canonical = f"https://dchub.cloud/news/{slug}"
    description = (subheadline or body[:200] or "DC Hub press release.")[:300]
    payload = {
        "@context": "https://schema.org",
        "@type": "NewsArticle",
        "headline": title,
        "description": description,
        "url": canonical,
        "datePublished": date_human,
        "inLanguage": "en-US",
        "publisher": {
            "@type": "Organization",
            "name": "DC Hub",
            "url": "https://dchub.cloud",
            "logo": {
                "@type": "ImageObject",
                "url": "https://dchub.cloud/icons/dchub-logo.png",
            },
        },
        "author": {
            "@type": "Organization",
            "name": source or "DC Hub",
        },
        "mainEntityOfPage": canonical,
        "isAccessibleForFree": True,
        "keywords": "data center, power index, DCPI, ISO, grid intelligence, "
                    "data center markets, AI infrastructure",
    }
    return ('<script type="application/ld+json">' +
            _json.dumps(payload, separators=(",", ":")) +
            '</script>')


def _render_share_buttons(slug, title):
    """LinkedIn / X / Email / Copy-link share buttons."""
    canonical = f"https://dchub.cloud/news/{slug}"
    from urllib.parse import quote
    li_url = "https://www.linkedin.com/sharing/share-offsite/?url=" + quote(canonical)
    tw_url = ("https://twitter.com/intent/tweet?text=" +
              quote(title + " — ") + "&url=" + quote(canonical))
    em_url = ("mailto:?subject=" + quote(title) +
              "&body=" + quote(canonical))
    return f"""<div class="share">
  <div class="share-label">Share this brief</div>
  <div class="share-buttons">
    <a href="{li_url}" target="_blank" rel="noopener" class="share-btn linkedin">
      <span>in</span> Share on LinkedIn
    </a>
    <a href="{tw_url}" target="_blank" rel="noopener" class="share-btn x">
      <span>𝕏</span> Share on X
    </a>
    <a href="{em_url}" class="share-btn email">
      <span>✉</span> Email
    </a>
    <button class="share-btn copy" onclick="navigator.clipboard.writeText('{canonical}');this.textContent='✓ Copied';">
      <span>🔗</span> Copy link
    </button>
  </div>
</div>"""


def _render_subscribe_cta():
    """Conversion-funnel hook: drop press readers into the daily brief
       subscription list. Reuses /api/v1/digest/subscribe."""
    return """<div class="subscribe-cta">
  <div class="sub-kicker">📬 Daily DC Hub Brief</div>
  <h3>Get tomorrow's market intelligence by 9am ET</h3>
  <p>One short email · top BUILD/AVOID verdict shifts · biggest 7-day movers · zero noise.</p>
  <form onsubmit="return subscribeBrief(event)" class="sub-form">
    <input type="email" name="email" placeholder="you@company.com" required>
    <button type="submit">Subscribe →</button>
  </form>
  <div class="sub-msg" id="sub-msg"></div>
</div>
<script>
async function subscribeBrief(ev) {
  ev.preventDefault();
  const email = ev.target.email.value;
  const msg = document.getElementById('sub-msg');
  msg.textContent = 'Subscribing…';
  try {
    const r = await fetch('/api/v1/digest/subscribe', {
      method: 'POST', headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({email, source: 'auto_press_release'})
    });
    const d = await r.json();
    if (d.ok || d.success || d.subscribed) {
      msg.style.color = '#10b981';
      msg.textContent = '✓ Subscribed. Check your inbox tomorrow morning.';
    } else {
      msg.style.color = '#f59e0b';
      msg.textContent = d.error || d.message || 'Try again.';
    }
  } catch (e) {
    msg.style.color = '#f59e0b';
    msg.textContent = 'Network error — try again.';
  }
  return false;
}
</script>"""


_STYLES = """<style>
:root { --bg:#0a0a0f; --bg2:#11121a; --fg:#e8eaf0; --muted:#9ca3af;
        --muted2:#c4c8d4; --accent:#8b6fff; --accent2:#a855f7;
        --accent-bg:rgba(139,111,255,0.10); --border:#1f2030;
        --good:#10b981; --warn:#f59e0b; --bad:#ef4444; }
* { box-sizing: border-box; }
body { margin:0; font:17px/1.7 -apple-system,"Inter","Segoe UI",Roboto,Arial,sans-serif;
       background:var(--bg); color:var(--fg);
       -webkit-font-smoothing:antialiased; }
.wrap { max-width:760px; margin:0 auto; padding:32px 22px 80px; }
.nav { font-size:13px; margin-bottom:32px; opacity:.7 }
.nav a { color:var(--muted); text-decoration:none; }
.nav a:hover { color:var(--fg); }
.kicker { display:inline-flex; align-items:center; gap:8px;
          font-size:11px; letter-spacing:1.4px; text-transform:uppercase;
          color:var(--accent); font-weight:800; margin-bottom:18px;
          padding:5px 12px; background:var(--accent-bg);
          border:1px solid rgba(139,111,255,0.3); border-radius:999px; }
.kicker .dot { width:6px; height:6px; border-radius:50%; background:var(--good);
               animation:pulse 2s ease-in-out infinite; }
@keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.4} }
h1 { font-size:38px; line-height:1.12; letter-spacing:-0.9px;
     margin:0 0 16px; font-weight:800; }
.subhead { font-size:21px; color:var(--muted2); margin:0 0 30px;
           line-height:1.45; font-weight:500; }
.meta { font-size:13px; color:var(--muted); margin:0 0 28px;
        padding:14px 0 20px; border-bottom:1px solid var(--border);
        display:flex; align-items:center; gap:10px; flex-wrap:wrap; }
.meta strong { color:var(--muted2); font-weight:600; }
.meta .dot-sep { color:var(--border); }
.byline { display:inline-flex; align-items:center; gap:8px;
          color:var(--muted2); font-size:13px; }
.byline-avatar { width:24px; height:24px; border-radius:50%;
                 background:linear-gradient(135deg, var(--accent), var(--accent2));
                 display:flex; align-items:center; justify-content:center;
                 color:#fff; font-weight:800; font-size:11px; }

/* Stat cards */
.stat-cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(190px,1fr));
              gap:12px; margin:0 0 36px; }
.stat-card { background:var(--bg2); border:1px solid var(--border);
             border-left:3px solid var(--accent); border-radius:10px;
             padding:14px 16px; }
.stat-label { font-size:11px; letter-spacing:1px; text-transform:uppercase;
              color:var(--muted); font-weight:700; margin-bottom:6px; }
.stat-big { font-family:'JetBrains Mono','SF Mono',Menlo,monospace;
            font-size:26px; font-weight:800; letter-spacing:-0.5px;
            color:var(--fg); line-height:1.1; }
.stat-sub { font-size:12px; color:var(--muted); margin-top:6px; line-height:1.4; }

/* Body */
.body { font-size:17px; }
.body p { margin:0 0 18px; line-height:1.75; }
.body h2 { font-size:24px; font-weight:700; letter-spacing:-0.3px;
           margin:36px 0 14px; line-height:1.3; }
.body h3 { font-size:19px; font-weight:700; margin:28px 0 10px;
           color:var(--muted2); }
.body blockquote { margin:24px 0; padding:18px 22px;
                   background:var(--accent-bg); border-left:3px solid var(--accent);
                   border-radius:6px; font-style:italic; color:var(--muted2);
                   font-size:18px; line-height:1.6; }
.body blockquote p { margin:0; }
.body ul, .body ol { margin:0 0 22px; padding-left:24px; }
.body li { margin-bottom:8px; line-height:1.65; }
.body strong { color:var(--fg); font-weight:700; }
.body code { font-family:'JetBrains Mono',monospace; font-size:0.92em;
             background:rgba(255,255,255,0.06); padding:1px 7px;
             border-radius:4px; color:#ffc7a8; }
.body a { color:var(--accent); text-decoration:underline; text-underline-offset:3px; }
.body a:hover { color:var(--accent2); }

/* Share */
.share { margin:48px 0 36px; padding:24px 0; border-top:1px solid var(--border);
         border-bottom:1px solid var(--border); }
.share-label { font-size:11px; letter-spacing:1.5px; text-transform:uppercase;
               color:var(--muted); font-weight:700; margin-bottom:14px; }
.share-buttons { display:flex; gap:8px; flex-wrap:wrap; }
.share-btn { display:inline-flex; align-items:center; gap:8px; padding:9px 16px;
             background:var(--bg2); border:1px solid var(--border); border-radius:8px;
             color:var(--fg); text-decoration:none; cursor:pointer;
             font-family:inherit; font-size:14px; font-weight:600;
             transition:.15s; }
.share-btn:hover { border-color:var(--accent); color:var(--fg); }
.share-btn.linkedin:hover { border-color:#0a66c2; }
.share-btn span { font-size:1rem; opacity:.85 }

/* Subscribe */
.subscribe-cta { margin:32px 0; padding:28px;
                 background:linear-gradient(135deg,rgba(139,111,255,0.08),rgba(168,85,247,0.06));
                 border:1px solid rgba(139,111,255,0.22); border-radius:14px; }
.sub-kicker { font-size:11px; letter-spacing:1.4px; text-transform:uppercase;
              color:var(--accent); font-weight:800; margin-bottom:6px; }
.subscribe-cta h3 { font-size:22px; margin:0 0 6px; letter-spacing:-0.3px; }
.subscribe-cta p { color:var(--muted2); margin:0 0 16px; font-size:14px; }
.sub-form { display:flex; gap:8px; flex-wrap:wrap; }
.sub-form input { flex:1; min-width:180px; padding:11px 14px;
                  background:var(--bg); border:1px solid var(--border);
                  border-radius:8px; color:var(--fg); font-family:inherit; font-size:14px; }
.sub-form input:focus { outline:none; border-color:var(--accent); }
.sub-form button { padding:11px 22px;
                   background:linear-gradient(135deg, var(--accent), var(--accent2));
                   border:none; border-radius:8px; color:#fff; font-weight:700;
                   font-family:inherit; font-size:14px; cursor:pointer; }
.sub-msg { margin-top:10px; font-size:13px; min-height:18px; }

/* Footer */
.footer { margin-top:48px; padding-top:24px; border-top:1px solid var(--border);
          font-size:13px; color:var(--muted); }
.footer a { color:var(--muted2); text-decoration:none; }
.footer a:hover { color:var(--fg); }

@media (max-width:560px) {
  h1 { font-size:30px; }
  .subhead { font-size:18px; }
  .wrap { padding:24px 18px 60px; }
}
</style>"""


_NOT_FOUND = """<!doctype html><html><head>
<meta charset="utf-8"/><title>Article Not Found - DC Hub</title>
<style>body{font:16px/1.5 -apple-system,sans-serif;background:#0a0a0f;
color:#e8eaf0;text-align:center;padding:80px 20px}
h1{color:#8b6fff}a{color:#8b6fff}</style></head><body>
<h1>Article not found</h1><p>No press release with slug '{SLUG}' exists.</p>
<p><a href="/news">&larr; Back to all news</a></p></body></html>"""


def _render_not_found(slug):
    return _NOT_FOUND.replace("{SLUG}", _html.escape(slug))


def _render_page(title, subheadline, body, category, date_human, slug, meta,
                 source="DC Hub", source_data=None):
    """Phase EE: rich page renderer."""
    canonical = f"https://dchub.cloud/news/{slug}"
    title_esc = _html.escape(title or "DC Hub Press Release")
    desc_esc = _html.escape((meta or subheadline or title or "")[:300])
    body_html = _body_to_html(body)
    stat_html = _render_stat_cards(source_data)
    share_html = _render_share_buttons(slug, title or "")
    sub_html = _render_subscribe_cta()
    jsonld = _build_jsonld(title or "", subheadline or "", body or "",
                            slug, date_human, source)
    is_auto = (source or "").startswith("DC Hub Auto")
    auto_badge = ('<span class="dot"></span>Autonomous brief'
                  if is_auto else
                  'Press release · DC Hub')

    return f"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>{title_esc} · DC Hub</title>
<meta name="description" content="{desc_esc}">
<link rel="canonical" href="{canonical}">
<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">
<meta property="og:title" content="{title_esc}">
<meta property="og:description" content="{desc_esc}">
<meta property="og:url" content="{canonical}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="DC Hub">
<meta property="og:image" content="https://dchub.cloud/og-default.png">
<meta property="article:published_time" content="{_html.escape(date_human)}">
<meta property="article:section" content="{_html.escape(category)}">
<meta property="article:author" content="DC Hub">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@dchubcloud">
<meta name="twitter:title" content="{title_esc}">
<meta name="twitter:description" content="{desc_esc}">
<meta name="twitter:image" content="https://dchub.cloud/og-default.png">
{jsonld}
{_STYLES}
</head><body><div class="wrap">

<div class="nav"><a href="/news">← All briefs</a></div>

<div class="kicker">{auto_badge}</div>
<h1>{title_esc}</h1>
<div class="subhead">{_html.escape(subheadline or '')}</div>

<div class="meta">
  <div class="byline">
    <div class="byline-avatar">DC</div>
    <span><strong>{_html.escape(source or 'DC Hub')}</strong></span>
  </div>
  <span class="dot-sep">·</span>
  <span>{_html.escape(date_human or '')}</span>
  <span class="dot-sep">·</span>
  <span>{_html.escape(category or 'Press Release')}</span>
</div>

{stat_html}

<div class="body">
{body_html}
</div>

{share_html}

{sub_html}

<div class="footer">
  Published by <a href="https://dchub.cloud">DC Hub</a> ·
  <a href="/press">Press room</a> ·
  <a href="/dcpi">DCPI</a> ·
  <a href="/api/press-releases/{_html.escape(slug)}">JSON</a> ·
  <a href="/press/feed.xml">RSS</a>
</div>

</div></body></html>"""


def register(app, get_pg_conn, return_pg_conn):
    """Register the /news/<slug> route on the given Flask app."""
    @app.route("/news/<slug>", methods=["GET"])
    def news_slug_page(slug):
        if slug.startswith("digest-"):
            return "Use /news/digest-YYYY-MM-DD for date-based digests", 404

        conn = None
        try:
            conn = get_pg_conn()
            cur = conn.cursor()
            # Pull press_releases row + (when available) the auto_press_releases
            # audit row for source_data + source attribution.
            cur.execute("""
                SELECT pr.id, pr.slug, pr.title, pr.subheadline, pr.body,
                       pr.category, pr.date, pr.meta_description, pr.source,
                       apr.source_data
                FROM press_releases pr
                LEFT JOIN auto_press_releases apr ON apr.press_release_id = pr.id
                WHERE pr.slug = %s LIMIT 1
            """, (slug,))
            row = cur.fetchone()
            return_pg_conn(conn)
            conn = None

            if not row:
                return _render_not_found(slug), 404

            (_id, _slug, title, subheadline, body, category, date_val,
             meta, source, source_data) = row
            return _render_page(
                title=title or "",
                subheadline=subheadline or "",
                body=body or "",
                category=category or "Press Release",
                date_human=_format_date(date_val),
                slug=_slug or slug,
                meta=(meta or subheadline or title or "")[:300],
                source=source or "DC Hub",
                source_data=source_data,
            )
        except Exception as e:
            # auto_press_releases table might not exist on older deploys;
            # try again without the JOIN
            try:
                if conn: return_pg_conn(conn)
            except Exception: pass
            try:
                conn = get_pg_conn()
                cur = conn.cursor()
                cur.execute(
                    "SELECT id, slug, title, subheadline, body, category, "
                    "date, meta_description, source FROM press_releases "
                    "WHERE slug = %s LIMIT 1", (slug,))
                row = cur.fetchone()
                return_pg_conn(conn)
                if not row:
                    return _render_not_found(slug), 404
                _id, _slug, title, subheadline, body, category, date_val, meta, source = row
                return _render_page(
                    title=title or "",
                    subheadline=subheadline or "",
                    body=body or "",
                    category=category or "Press Release",
                    date_human=_format_date(date_val),
                    slug=_slug or slug,
                    meta=(meta or subheadline or title or "")[:300],
                    source=source or "DC Hub",
                    source_data=None,
                )
            except Exception as ee:
                return _render_not_found(
                    slug + " (error: " + str(ee)[:120] + ")"), 500
