#!/usr/bin/env python3
"""
patch_main_extras.py — swap inline _AP_STATE_CONTEXT + _AP_NEI for imports.

What it does (in-place, idempotent):
  1. Inserts `from air_permitting_extras import STATE_CONTEXT, NEI_SOURCES ...`
     near the existing air-permitting imports in main.py.
  2. Removes the big inline _AP_STATE_CONTEXT = { ... } dict (16 -> 51 states).
  3. Removes the big inline _AP_NEI = [ ... ] list (22 -> 77 NEI sources).

Creates main.py.bak.extras before touching anything.
Validates py_compile afterward — auto-restores backup on any syntax error.

Usage (from the directory containing main.py + air_permitting_extras.py):
    python3 patch_main_extras.py
"""
from __future__ import annotations
import re
import sys
import shutil
import py_compile
from pathlib import Path

SRC = Path("main.py")
EXTRAS = Path("air_permitting_extras.py")

if not SRC.exists():
    print("ERROR: main.py not found in current directory.")
    sys.exit(1)
if not EXTRAS.exists():
    print("ERROR: air_permitting_extras.py not found. Run finalize_air_permitting.py first.")
    sys.exit(1)

BAK = SRC.with_suffix(".py.bak.extras")
shutil.copy2(SRC, BAK)
print(f"✓ Backup: {BAK}")

text = SRC.read_text()
original_len = len(text)


def remove_balanced_block(s: str, marker: str, opener: str, closer: str) -> tuple[str, bool]:
    """Find `marker` in s, then delete from its start through the matching balanced closer.
       Returns (new_string, found_flag)."""
    idx = s.find(marker)
    if idx == -1:
        return s, False
    op = s.find(opener, idx)
    depth = 0
    i = op
    while i < len(s):
        c = s[i]
        if c == opener:
            depth += 1
        elif c == closer:
            depth -= 1
            if depth == 0:
                end = i + 1
                while end < len(s) and s[end] in "\r\n":
                    end += 1
                return s[:idx] + s[end:], True
        i += 1
    return s, False


# ─── Step 1: insert the import ────────────────────────────────────────
IMPORT_BLOCK = """# Expanded state context + NEI sources (generated by finalize_air_permitting.py)
from air_permitting_extras import (
    STATE_CONTEXT as _AP_STATE_CONTEXT,
    NEI_SOURCES  as _AP_NEI,
)

"""

if "from air_permitting_extras import" in text:
    print("· Extras import already present — skipping insertion.")
else:
    # Prefer inserting right after the existing `from air_permitting_data import`
    # block that the earlier patcher added. Fall back to the block anchor.
    anchor_re = re.compile(r"from air_permitting_data import \([^)]*\)\s*\n", re.DOTALL)
    m = anchor_re.search(text)
    if m:
        pos = m.end()
        text = text[:pos] + IMPORT_BLOCK + text[pos:]
        print("✓ Inserted extras import after `from air_permitting_data import ...`")
    else:
        # Fallback: after `import time as _ap_time`
        anchor = "import time as _ap_time"
        pos = text.find(anchor)
        if pos == -1:
            print("ERROR: can't find an anchor to insert the extras import.")
            print("       main.py may have been reorganized. Aborting without writing.")
            sys.exit(2)
        eol = text.find("\n", pos)
        text = text[:eol + 1] + "\n" + IMPORT_BLOCK + text[eol + 1:]
        print("✓ Inserted extras import after `import time as _ap_time`")

# ─── Step 2: remove _AP_STATE_CONTEXT block ────────────────────────────
text, found_sc = remove_balanced_block(text, "_AP_STATE_CONTEXT = {", "{", "}")
if found_sc:
    print("✓ Removed inline _AP_STATE_CONTEXT block")
else:
    print("· _AP_STATE_CONTEXT already removed (or not found)")

# ─── Step 3: remove _AP_NEI block ──────────────────────────────────────
text, found_nei = remove_balanced_block(text, "_AP_NEI = [", "[", "]")
if found_nei:
    print("✓ Removed inline _AP_NEI block")
else:
    print("· _AP_NEI already removed (or not found)")

# ─── Write out ──────────────────────────────────────────────────────────
SRC.write_text(text)
new_len = len(text)
delta = original_len - new_len
print()
print(f"Before: {original_len:,} bytes")
print(f"After:  {new_len:,} bytes  ({'-' if delta >= 0 else '+'}{abs(delta):,})")

# ─── Syntax validate or restore ────────────────────────────────────────
try:
    py_compile.compile(str(SRC), doraise=True)
    print("✓ Syntax OK — safe to commit.")
except py_compile.PyCompileError as e:
    print(f"✗ SYNTAX ERROR in patched main.py:\n{e}")
    print(f"  Restoring backup from {BAK}...")
    shutil.copy2(BAK, SRC)
    print("  Done. main.py restored to pre-patch state.")
    sys.exit(3)

# Secondary check — can the module be imported without blowing up?
print()
print("Optional smoke test (in your shell):")
print("    python3 -c 'import main' 2>&1 | head -20")
print()
print("Then commit + push:")
print("    git add main.py")
print("    git commit -m 'feat(air-permitting): wire 51-state context + 77 NEI via extras module'")
print("    git push")
