#!/usr/bin/env python3
"""
patch_news_slug_page_v3.py — add /news/<slug> route via separate module.

V3 fixes V2's escape-hell by base64-encoding the standalone module.
No more triple-quote-in-triple-quote acrobatics.

What it does (idempotent):
  1. Decodes news_slug_route.py from a base64 blob and writes it.
  2. Appends one import + one register() call to the END of main.py.

Auto-restores main.py from backup on any syntax error.
"""
from __future__ import annotations
import base64
import shutil
import sys
import py_compile
from pathlib import Path

SRC = Path("main.py")
ROUTE_FILE = Path("news_slug_route.py")

if not SRC.exists():
    print("ERROR: main.py not found.")
    sys.exit(1)

NEWS_MODULE_B64 = """
IiIiCm5ld3Nfc2x1Z19yb3V0ZS5weSAtIC9uZXdzLzxzbHVnPiBGbGFzayByb3V0ZSwgcmVnaXN0
ZXJlZCBmcm9tIG1haW4ucHkuCgpSZW5kZXJzIGFueSByb3cgZnJvbSB0aGUgcHJlc3NfcmVsZWFz
ZXMgdGFibGUgYXMgYSBzdHlsZWQgZGFyay10aGVtZSBIVE1MCnBhZ2UuIENhbGxlZCBieSBtYWlu
LnB5IGF0IHN0YXJ0dXAgdmlhIHJlZ2lzdGVyKGFwcCwgZ2V0X2Nvbm4sIHJldHVybl9jb25uKS4K
IiIiCmltcG9ydCBodG1sIGFzIF9odG1sCgoKX1BBR0VfSEVBRF8xID0gIiIiPCFkb2N0eXBlIGh0
bWw+CjxodG1sIGxhbmc9ImVuIj48aGVhZD4KPG1ldGEgY2hhcnNldD0idXRmLTgiLz4KPG1ldGEg
bmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCxpbml0aWFsLXNjYWxl
PTEiLz4KPHRpdGxlPiIiIgoKX1BBR0VfSEVBRF8yID0gIiIiIC0gREMgSHViPC90aXRsZT4KPG1l
dGEgbmFtZT0iZGVzY3JpcHRpb24iIGNvbnRlbnQ9XCIiIiIKCl9QQUdFX0hFQURfMyA9ICIiIlwi
Pgo8c3R5bGU+Cjpyb290IHsgLS1iZzojMGEwYTBmOyAtLWZnOiNlOGVhZjA7IC0tbXV0ZWQ6Izg4
ODsgLS1tdXRlZDI6I2FhYTsKICAtLWFjY2VudDojOGI2ZmZmOyAtLWFjY2VudC1iZzpyZ2JhKDEz
OSwxMTEsMjU1LDAuMTIpOyAtLWJvcmRlcjojMjMyNzM3OyB9CiogeyBib3gtc2l6aW5nOiBib3Jk
ZXItYm94OyB9CmJvZHkgeyBtYXJnaW46MDsgZm9udDoxNnB4LzEuNjUgLWFwcGxlLXN5c3RlbSwi
SW50ZXIiLCJTZWdvZSBVSSIsUm9ib3RvLEFyaWFsLHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZDp2
YXIoLS1iZyk7IGNvbG9yOnZhcigtLWZnKTsgfQoud3JhcCB7IG1heC13aWR0aDo3ODBweDsgbWFy
Z2luOjAgYXV0bzsgcGFkZGluZzo0MHB4IDI4cHggODBweDsgfQoua2lja2VyIHsgZm9udC1zaXpl
OjExcHg7IGxldHRlci1zcGFjaW5nOjEuNXB4OyB0ZXh0LXRyYW5zZm9ybTp1cHBlcmNhc2U7CiAg
Y29sb3I6dmFyKC0tYWNjZW50KTsgZm9udC13ZWlnaHQ6NzAwOyBtYXJnaW4tYm90dG9tOjEycHg7
IH0KaDEgeyBmb250LXNpemU6MzZweDsgbGluZS1oZWlnaHQ6MS4xNTsgbGV0dGVyLXNwYWNpbmc6
LTAuOHB4OwogIG1hcmdpbjowIDAgMTRweDsgZm9udC13ZWlnaHQ6ODAwOyB9Ci5zdWJoZWFkIHsg
Zm9udC1zaXplOjE5cHg7IGNvbG9yOnZhcigtLW11dGVkMik7IG1hcmdpbjowIDAgMjhweDsgbGlu
ZS1oZWlnaHQ6MS41OyB9Ci5tZXRhIHsgZm9udC1zaXplOjEzcHg7IGNvbG9yOnZhcigtLW11dGVk
KTsgbWFyZ2luOjAgMCAzNnB4OwogIHBhZGRpbmctYm90dG9tOjI0cHg7IGJvcmRlci1ib3R0b206
MXB4IHNvbGlkIHZhcigtLWJvcmRlcik7IH0KcCB7IG1hcmdpbjowIDAgMThweDsgZm9udC1zaXpl
OjE3cHg7IGxpbmUtaGVpZ2h0OjEuNzsgfQpibG9ja3F1b3RlIHsgbWFyZ2luOjI0cHggMDsgcGFk
ZGluZzoxOHB4IDIycHg7IGJhY2tncm91bmQ6dmFyKC0tYWNjZW50LWJnKTsKICBib3JkZXItbGVm
dDozcHggc29saWQgdmFyKC0tYWNjZW50KTsgYm9yZGVyLXJhZGl1czo0cHg7CiAgZm9udC1zdHls
ZTppdGFsaWM7IGNvbG9yOnZhcigtLW11dGVkMik7IH0KYSB7IGNvbG9yOnZhcigtLWFjY2VudCk7
IHRleHQtZGVjb3JhdGlvbjpub25lOyB9CmE6aG92ZXIgeyB0ZXh0LWRlY29yYXRpb246dW5kZXJs
aW5lOyB9Ci5mb290ZXIgeyBtYXJnaW4tdG9wOjQ4cHg7IHBhZGRpbmctdG9wOjI0cHg7IGJvcmRl
ci10b3A6MXB4IHNvbGlkIHZhcigtLWJvcmRlcik7CiAgZm9udC1zaXplOjEzcHg7IGNvbG9yOnZh
cigtLW11dGVkKTsgfQoubmF2IHsgbWFyZ2luLWJvdHRvbToyNHB4OyBmb250LXNpemU6MTNweDsg
fQoubmF2IGEgeyBjb2xvcjp2YXIoLS1tdXRlZCk7IH0KPC9zdHlsZT4KPC9oZWFkPjxib2R5Pjxk
aXYgY2xhc3M9IndyYXAiPgo8ZGl2IGNsYXNzPSJuYXYiPjxhIGhyZWY9Ii9uZXdzIj4mbGFycjsg
QWxsIE5ld3M8L2E+PC9kaXY+CjxkaXYgY2xhc3M9ImtpY2tlciI+IiIiCgpfUEFHRV9CT0RZXzEg
PSAiIiI8L2Rpdj4KPGgxPiIiIgoKX1BBR0VfQk9EWV8yID0gIiIiPC9oMT4KPGRpdiBjbGFzcz0i
c3ViaGVhZCI+IiIiCgpfUEFHRV9CT0RZXzMgPSAiIiI8L2Rpdj4KPGRpdiBjbGFzcz0ibWV0YSI+
PHN0cm9uZz4iIiIKCl9QQUdFX0JPRFlfNCA9ICIiIjwvc3Ryb25nPjwvZGl2Pgo8ZGl2IGNsYXNz
PSJib2R5Ij4iIiIKCl9QQUdFX0JPRFlfNSA9ICIiIjwvZGl2Pgo8ZGl2IGNsYXNzPSJmb290ZXIi
PlB1Ymxpc2hlZCBieSBEQyBIdWIgJm1pZGRvdDsKPGEgaHJlZj0iaHR0cHM6Ly9kY2h1Yi5jbG91
ZCI+ZGNodWIuY2xvdWQ8L2E+ICZtaWRkb3Q7CjxhIGhyZWY9Ii9wcmVzcyI+UHJlc3MgUm9vbTwv
YT4gJm1pZGRvdDsKPGEgaHJlZj0iL2FwaS9wcmVzcy1yZWxlYXNlcy8iIiIKCl9QQUdFX0ZPT1RF
UiA9ICIiIlwiPkpTT048L2E+PC9kaXY+CjwvZGl2PjwvYm9keT48L2h0bWw+IiIiCgoKX05PVF9G
T1VORF8xID0gIiIiPCFkb2N0eXBlIGh0bWw+PGh0bWw+PGhlYWQ+CjxtZXRhIGNoYXJzZXQ9InV0
Zi04Ii8+PHRpdGxlPkFydGljbGUgTm90IEZvdW5kIC0gREMgSHViPC90aXRsZT4KPHN0eWxlPmJv
ZHl7Zm9udDoxNnB4LzEuNSAtYXBwbGUtc3lzdGVtLHNhbnMtc2VyaWY7YmFja2dyb3VuZDojMGEw
YTBmOwpjb2xvcjojZThlYWYwO3RleHQtYWxpZ246Y2VudGVyO3BhZGRpbmc6ODBweCAyMHB4fQpo
MXtjb2xvcjojOGI2ZmZmfWF7Y29sb3I6IzhiNmZmZn08L3N0eWxlPjwvaGVhZD48Ym9keT4KPGgx
PkFydGljbGUgbm90IGZvdW5kPC9oMT48cD5ObyBwcmVzcyByZWxlYXNlIHdpdGggc2x1ZyAnIiIi
CgpfTk9UX0ZPVU5EXzIgPSAiIiInIGV4aXN0cy48L3A+CjxwPjxhIGhyZWY9Ii9uZXdzIj4mbGFy
cjsgQmFjayB0byBhbGwgbmV3czwvYT48L3A+PC9ib2R5PjwvaHRtbD4iIiIKCgpkZWYgX2Zvcm1h
dF9kYXRlKGRhdGVfdmFsKToKICAgIGlmIG5vdCBkYXRlX3ZhbDoKICAgICAgICByZXR1cm4gIiIK
ICAgIHRyeToKICAgICAgICBpZiBoYXNhdHRyKGRhdGVfdmFsLCAic3RyZnRpbWUiKToKICAgICAg
ICAgICAgcmV0dXJuIGRhdGVfdmFsLnN0cmZ0aW1lKCIlQiAlZCwgJVkiKQogICAgICAgIHJldHVy
biBzdHIoZGF0ZV92YWwpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHJldHVybiBzdHIo
ZGF0ZV92YWwpCgoKZGVmIF9ib2R5X3RvX2h0bWwoYm9keV90ZXh0KToKICAgIGlmIG5vdCBib2R5
X3RleHQ6CiAgICAgICAgcmV0dXJuICIiCiAgICBwYXJ0cyA9IFtwLnN0cmlwKCkgZm9yIHAgaW4g
Ym9keV90ZXh0LnNwbGl0KCJcblxuIikgaWYgcC5zdHJpcCgpXQogICAgb3V0ID0gW10KICAgIGZv
ciBwIGluIHBhcnRzOgogICAgICAgIGVzYyA9IF9odG1sLmVzY2FwZShwKS5yZXBsYWNlKCJcbiIs
ICI8YnI+IikKICAgICAgICBmaXJzdCA9IGVzYy5sc3RyaXAoKVs6MTVdLmxvd2VyKCkKICAgICAg
ICBpZiBmaXJzdC5zdGFydHN3aXRoKCJxdW90ZSBmcm9tIikgb3IgZmlyc3Quc3RhcnRzd2l0aCgi
JnF1b3Q7Iik6CiAgICAgICAgICAgIG91dC5hcHBlbmQoIjxibG9ja3F1b3RlPiIgKyBlc2MgKyAi
PC9ibG9ja3F1b3RlPiIpCiAgICAgICAgZWxzZToKICAgICAgICAgICAgb3V0LmFwcGVuZCgiPHA+
IiArIGVzYyArICI8L3A+IikKICAgIHJldHVybiAiXG4iLmpvaW4ob3V0KQoKCmRlZiBfcmVuZGVy
X3BhZ2UodGl0bGUsIHN1YmhlYWRsaW5lLCBib2R5LCBjYXRlZ29yeSwgZGF0ZV9odW1hbiwgc2x1
ZywgbWV0YSk6CiAgICByZXR1cm4gKAogICAgICAgIF9QQUdFX0hFQURfMSArIF9odG1sLmVzY2Fw
ZSh0aXRsZSkgKwogICAgICAgIF9QQUdFX0hFQURfMiArIF9odG1sLmVzY2FwZShtZXRhKSArCiAg
ICAgICAgX1BBR0VfSEVBRF8zICsgX2h0bWwuZXNjYXBlKGNhdGVnb3J5LnVwcGVyKCkpICsKICAg
ICAgICBfUEFHRV9CT0RZXzEgKyBfaHRtbC5lc2NhcGUodGl0bGUpICsKICAgICAgICBfUEFHRV9C
T0RZXzIgKyBfaHRtbC5lc2NhcGUoc3ViaGVhZGxpbmUpICsKICAgICAgICBfUEFHRV9CT0RZXzMg
KyBfaHRtbC5lc2NhcGUoZGF0ZV9odW1hbikgKwogICAgICAgIF9QQUdFX0JPRFlfNCArIF9ib2R5
X3RvX2h0bWwoYm9keSkgKwogICAgICAgIF9QQUdFX0JPRFlfNSArIF9odG1sLmVzY2FwZShzbHVn
KSArCiAgICAgICAgX1BBR0VfRk9PVEVSCiAgICApCgoKZGVmIF9yZW5kZXJfbm90X2ZvdW5kKHNs
dWcpOgogICAgcmV0dXJuIF9OT1RfRk9VTkRfMSArIF9odG1sLmVzY2FwZShzbHVnKSArIF9OT1Rf
Rk9VTkRfMgoKCmRlZiByZWdpc3RlcihhcHAsIGdldF9wZ19jb25uLCByZXR1cm5fcGdfY29ubik6
CiAgICAiIiJSZWdpc3RlciB0aGUgL25ld3MvPHNsdWc+IHJvdXRlIG9uIHRoZSBnaXZlbiBGbGFz
ayBhcHAuIiIiCiAgICBAYXBwLnJvdXRlKCIvbmV3cy88c2x1Zz4iLCBtZXRob2RzPVsiR0VUIl0p
CiAgICBkZWYgbmV3c19zbHVnX3BhZ2Uoc2x1Zyk6CiAgICAgICAgaWYgc2x1Zy5zdGFydHN3aXRo
KCJkaWdlc3QtIik6CiAgICAgICAgICAgIHJldHVybiAiVXNlIC9uZXdzL2RpZ2VzdC1ZWVlZLU1N
LUREIGZvciBkYXRlLWJhc2VkIGRpZ2VzdHMiLCA0MDQKCiAgICAgICAgY29ubiA9IE5vbmUKICAg
ICAgICB0cnk6CiAgICAgICAgICAgIGNvbm4gPSBnZXRfcGdfY29ubigpCiAgICAgICAgICAgIGN1
ciA9IGNvbm4uY3Vyc29yKCkKICAgICAgICAgICAgY3VyLmV4ZWN1dGUoCiAgICAgICAgICAgICAg
ICAiU0VMRUNUIGlkLCBzbHVnLCB0aXRsZSwgc3ViaGVhZGxpbmUsIGJvZHksIGNhdGVnb3J5LCBk
YXRlLCAiCiAgICAgICAgICAgICAgICAibWV0YV9kZXNjcmlwdGlvbiBGUk9NIHByZXNzX3JlbGVh
c2VzIFdIRVJFIHNsdWcgPSAlcyBMSU1JVCAxIiwKICAgICAgICAgICAgICAgIChzbHVnLCksCiAg
ICAgICAgICAgICkKICAgICAgICAgICAgcm93ID0gY3VyLmZldGNob25lKCkKICAgICAgICAgICAg
cmV0dXJuX3BnX2Nvbm4oY29ubikKICAgICAgICAgICAgY29ubiA9IE5vbmUKCiAgICAgICAgICAg
IGlmIG5vdCByb3c6CiAgICAgICAgICAgICAgICByZXR1cm4gX3JlbmRlcl9ub3RfZm91bmQoc2x1
ZyksIDQwNAoKICAgICAgICAgICAgX2lkLCBfc2x1ZywgdGl0bGUsIHN1YmhlYWRsaW5lLCBib2R5
LCBjYXRlZ29yeSwgZGF0ZV92YWwsIG1ldGEgPSByb3cKICAgICAgICAgICAgcmV0dXJuIF9yZW5k
ZXJfcGFnZSgKICAgICAgICAgICAgICAgIHRpdGxlPXRpdGxlIG9yICIiLAogICAgICAgICAgICAg
ICAgc3ViaGVhZGxpbmU9c3ViaGVhZGxpbmUgb3IgIiIsCiAgICAgICAgICAgICAgICBib2R5PWJv
ZHkgb3IgIiIsCiAgICAgICAgICAgICAgICBjYXRlZ29yeT1jYXRlZ29yeSBvciAiUHJlc3MgUmVs
ZWFzZSIsCiAgICAgICAgICAgICAgICBkYXRlX2h1bWFuPV9mb3JtYXRfZGF0ZShkYXRlX3ZhbCks
CiAgICAgICAgICAgICAgICBzbHVnPV9zbHVnIG9yIHNsdWcsCiAgICAgICAgICAgICAgICBtZXRh
PShtZXRhIG9yIHN1YmhlYWRsaW5lIG9yIHRpdGxlIG9yICIiKVs6MzAwXSwKICAgICAgICAgICAg
KQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgdHJ5OgogICAgICAg
ICAgICAgICAgaWYgY29ubjoKICAgICAgICAgICAgICAgICAgICByZXR1cm5fcGdfY29ubihjb25u
KQogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICAgICAgcGFzcwogICAg
ICAgICAgICByZXR1cm4gX3JlbmRlcl9ub3RfZm91bmQoc2x1ZyArICIgKGVycm9yOiAiICsgc3Ry
KGUpWzoxMjBdICsgIikiKSwgNTAwCg==
"""

# ─── Step 1: write news_slug_route.py from base64 ──────────────────────
ROUTE_FILE.write_bytes(base64.b64decode(NEWS_MODULE_B64))
print(f"✓ Wrote {ROUTE_FILE} ({ROUTE_FILE.stat().st_size:,} bytes)")
try:
    py_compile.compile(str(ROUTE_FILE), doraise=True)
    print(f"✓ {ROUTE_FILE} syntax OK")
except py_compile.PyCompileError as e:
    print(f"✗ {ROUTE_FILE} syntax error: {e}")
    sys.exit(2)

# ─── Step 2: append one import + one register call to main.py ──────────
shutil.copy2(SRC, "main.py.bak.newsv3")
text = SRC.read_text()

if "news_slug_route" in text:
    print("· main.py already imports news_slug_route — nothing to append.")
    sys.exit(0)

addition = (
    "\n\n# ─── /news/<slug> renderer (added 2026-04-15) ─────────────────────────\n"
    "import news_slug_route as _news_slug\n"
    "_news_slug.register(app, get_pg_connection, return_pg_connection)\n"
)
text = text.rstrip() + addition + "\n"
SRC.write_text(text)
print(f"✓ Appended import + register call to {SRC}")

try:
    py_compile.compile(str(SRC), doraise=True)
    print("✓ main.py syntax OK — safe to commit.")
except py_compile.PyCompileError as e:
    print(f"✗ main.py syntax error: {e}")
    shutil.copy2("main.py.bak.newsv3", SRC)
    print("  Restored backup.")
    sys.exit(3)

print("\nNext:")
print("  git add main.py news_slug_route.py")
print("  git commit -m 'feat(news): add /news/<slug> renderer (separate module)'")
print("  git push")
print()
print("After Railway redeploys, verify ACTUAL article content:")
print("  curl -s 'https://dchub.cloud/news/dc-hub-global-infrastructure-1-29m-records-live' \\\n    | grep -E '1.29 Million|Digest Not Found' | head -3")
