#!/usr/bin/env python3
"""
patch_main_air_permitting.py — swap inline seed dicts for live data module.

What it does (in-place, idempotent):
  1. Inserts `from air_permitting_data import NONATTAINMENT, CLASS1 ...` near
     the top of the air-permitting block in main.py.
  2. Removes the big inline _AP_NONATTAINMENT = { ... } block (113 areas win).
  3. Removes the big inline _AP_CLASS1 = [ ... ] block (83 areas win).
  4. Leaves _AP_MONITORS = [ ... ] alone — you keep the 15 seed monitors until
     you set up the AQS API key.

Safe to run multiple times — already-patched files are detected and skipped.
Creates main.py.bak before touching anything.

Usage:
    python3 patch_main_air_permitting.py
"""
from __future__ import annotations
import re
import sys
import shutil
from pathlib import Path

SRC = Path("main.py")
if not SRC.exists():
    print("ERROR: main.py not found in current directory.")
    sys.exit(1)

# Back up first
BAK = SRC.with_suffix(".py.bak")
shutil.copy2(SRC, BAK)
print(f"✓ Backup: {BAK}")

text = SRC.read_text()
original_len = len(text)


def remove_balanced_block(s: str, marker: str, opener: str, closer: str) -> tuple[str, bool]:
    """Locate `marker` in s, then delete from its start through the matching
    `closer` (balanced). Returns (new_string, found_flag)."""
    idx = s.find(marker)
    if idx == -1:
        return s, False
    op = s.find(opener, idx)
    depth = 0
    i = op
    while i < len(s):
        c = s[i]
        if c == opener:
            depth += 1
        elif c == closer:
            depth -= 1
            if depth == 0:
                end = i + 1
                # eat trailing newlines so we don't leave blank gaps
                while end < len(s) and s[end] in "\r\n":
                    end += 1
                return s[:idx] + s[end:], True
        i += 1
    return s, False


# ─── Step 1: insert the import (if not already there) ──────────────────
IMPORT_BLOCK = """
# Live EPA data — replaces inline _AP_NONATTAINMENT and _AP_CLASS1 seeds
# (generated by upgrade_air_permitting.py; refresh via `python3 upgrade_air_permitting.py`)
from air_permitting_data import (
    NONATTAINMENT as _AP_NONATTAINMENT,
    CLASS1 as _AP_CLASS1,
)

"""
if "from air_permitting_data import" in text:
    print("· Import already present — skipping.")
else:
    # Anchor on the first line of the air-permitting block we previously added.
    # That block opens with `import time as _ap_time` (see air_permitting_patch.py).
    anchor = "import time as _ap_time"
    pos = text.find(anchor)
    if pos == -1:
        print("ERROR: can't find air-permitting block anchor 'import time as _ap_time'.")
        print("       main.py may have been reorganized. Aborting without writing.")
        sys.exit(2)
    # Insert on the line after the anchor
    eol = text.find("\n", pos)
    text = text[:eol + 1] + IMPORT_BLOCK + text[eol + 1:]
    print("✓ Inserted import block after air-permitting anchor")

# ─── Step 2: remove _AP_NONATTAINMENT block ────────────────────────────
text, found_na = remove_balanced_block(text, "_AP_NONATTAINMENT = {", "{", "}")
if found_na:
    print("✓ Removed inline _AP_NONATTAINMENT block")
else:
    print("· _AP_NONATTAINMENT already removed (or not found)")

# ─── Step 3: remove _AP_CLASS1 block ───────────────────────────────────
text, found_c1 = remove_balanced_block(text, "_AP_CLASS1 = [", "[", "]")
if found_c1:
    print("✓ Removed inline _AP_CLASS1 block")
else:
    print("· _AP_CLASS1 already removed (or not found)")

# ─── Write out ──────────────────────────────────────────────────────────
SRC.write_text(text)
new_len = len(text)
delta = original_len - new_len
print()
print(f"Before: {original_len:,} bytes")
print(f"After:  {new_len:,} bytes  ({'-' if delta >= 0 else '+'}{abs(delta):,})")

# Quick syntax validation so we don't push a broken main.py
import py_compile
try:
    py_compile.compile(str(SRC), doraise=True)
    print("✓ Syntax OK — safe to commit.")
except py_compile.PyCompileError as e:
    print(f"✗ SYNTAX ERROR in patched main.py:\n{e}")
    print(f"  Restoring backup from {BAK}...")
    shutil.copy2(BAK, SRC)
    print("  Done. main.py restored.")
    sys.exit(3)

print()
print("Next:")
print("    python3 -c \"import main\" 2>&1 | head   # smoke-test the import")
print("    git add main.py")
print("    git commit -m 'feat(air-permitting): wire live EPA data module (113 NA + 83 Class I)'")
print("    git push")
