"""
Tests for the two backend-generated A2A agent cards advertising the WorkOS
OAuth2 (authorization_code + RFC 7591 DCR) enterprise/marketplace path.

Regression guard for the Gemini Enterprise / Google Cloud Marketplace
Custom-MCP OAuth connect: the card that hosts actually fetch
(`/.well-known/agent-card.json`, generated by routes/agent_a2a.py) MUST
advertise the WorkOS OAuth2 endpoints, ADDITIVELY, without removing the
keyless free-tier / X-API-Key options.

Design constraints (reference_dchub_green_main_0709): NO import of main.py,
NO DB, NO network. Cards are plain dicts; routes are exercised against a
minimal local Flask app that registers ONLY the relevant blueprint.
"""
import json

import pytest

from flask import Flask

import routes.agent_a2a as agent_a2a

from workos_authkit import authkit_domain, AUTHKIT_SCOPES

# Derived, never pinned: this asserts the CARD matches the single origin,
# so a domain cutover does not have to be typed into the test as well.
WORKOS = authkit_domain()
EXPECTED_SCOPES = list(AUTHKIT_SCOPES)


# ── /.well-known/agent-card.json (routes/agent_a2a.py — the marketplace card) ─
def _agent_a2a_client():
    app = Flask(__name__)
    app.register_blueprint(agent_a2a.agent_a2a_bp)
    return app.test_client()


def test_agent_card_json_serializable():
    # _card() adds computed_at; whole thing must round-trip through JSON.
    json.dumps(agent_a2a._card())


def test_agent_card_advertises_workos_oauth2_authorization_code():
    oauth = agent_a2a.AGENT_CARD["auth"]["oauth2"]
    assert oauth["type"] == "oauth2"
    assert oauth["grant_type"] == "authorization_code"
    assert oauth["issuer"] == WORKOS
    assert oauth["authorization_endpoint"] == f"{WORKOS}/oauth2/authorize"
    assert oauth["token_endpoint"] == f"{WORKOS}/oauth2/token"
    # DCR (RFC 7591) — the field Gemini Enterprise / Marketplace requires.
    assert oauth["registration_endpoint"] == f"{WORKOS}/oauth2/register"
    assert oauth["scopes"] == EXPECTED_SCOPES
    # SH52-015: the RFC 8414 AS-metadata pointer MUST resolve. WorkOS AuthKit
    # is the real authorization server (matches the protected-resource doc's
    # authorization_servers[]), so it points at the issuer's own metadata —
    # NOT api.dchub.cloud, which serves no oauth-authorization-server doc (404)
    # and dead-ended header-less hosts that followed the pointer.
    assert oauth["authorization_server_metadata"] == \
        f"{WORKOS}/.well-known/oauth-authorization-server"
    assert "api.dchub.cloud" not in oauth["authorization_server_metadata"]
    # The RFC 9728 protected-resource doc IS served by the backend (200).
    assert oauth["metadata"] == \
        "https://api.dchub.cloud/.well-known/oauth-protected-resource"


def test_agent_card_free_tier_auth_intact():
    """OAuth2 must be ADDITIVE — free-tier keyless + X-API-Key untouched."""
    auth = agent_a2a.AGENT_CARD["auth"]
    assert auth["default"] == "none"
    assert "none" in auth["modes"]
    assert "api_key" in auth["modes"]
    assert "oauth2" in auth["modes"]
    # keyless free tier still explicitly declared
    assert auth["api_key"]["free_tier"]["no_signup"] is True
    assert auth["api_key"]["header"] == "X-API-Key"


def test_agent_card_marketplace_marker_and_tool_total():
    assert agent_a2a.AGENT_CARD["a2a_marketplace_ready"] is True
    # Honest tool total (live manifest = source of truth), skills are a subset.
    # ★ Assert the LINK to the canon, never a literal. This line read `== 74`
    # while the canon and live tools/list both said 82, so it went green for two
    # weeks and pinned the drift instead of catching it — a test that hard-codes
    # a published number becomes the reason the number can be wrong.
    from ai_surface_canon import PINNED as _canon
    assert agent_a2a.AGENT_CARD["mcp_tools"]["total"] == _canon["tools_advertised"]
    assert agent_a2a.AGENT_CARD["mcp_tools"]["skills_are_subset"] is True
    assert agent_a2a.AGENT_CARD["endpoints"]["mcp_manifest"] == \
        "https://dchub.cloud/.well-known/mcp.json"


#: Both A2A discovery paths: agent-card.json (A2A 0.3) and agent.json (0.2.x).
_A2A_PATHS = ("/.well-known/agent-card.json", "/.well-known/agent.json")


@pytest.mark.parametrize("path", _A2A_PATHS)
def test_agent_card_route_serves_oauth2(path):
    resp = _agent_a2a_client().get(path)
    assert resp.status_code == 200
    body = resp.get_json()
    assert body["auth"]["oauth2"]["registration_endpoint"] == f"{WORKOS}/oauth2/register"
    assert body["auth"]["default"] == "none"


# ── /.well-known/agent.json — the SAME card, not an alias of its own ─────────
def test_agent_json_is_the_same_card_as_agent_card_json():
    """One handler and one body behind both A2A discovery paths.

    ★ 2026-09-21. The OAuth2 scheme this file used to assert for agent.json
    lived on ai_agent_discovery.A2A_AGENT_CARD, on a blueprint main.py never
    registered. The public path meanwhile served an MCP server card with no
    auth block. Pinning the IDENTITY of the two paths means the OAuth2 fields
    asserted above cannot be true of one path and false of the other.
    """
    app = Flask(__name__)
    app.register_blueprint(agent_a2a.agent_a2a_bp)
    adapter = app.url_map.bind("dchub.cloud")
    endpoints = {p: adapter.match(p)[0] for p in _A2A_PATHS}
    assert len(set(endpoints.values())) == 1, endpoints

    client = app.test_client()
    card, alias = (client.get(p) for p in _A2A_PATHS)
    assert card.status_code == alias.status_code == 200
    card, alias = card.get_json(), alias.get_json()
    # computed_at is stamped per request; it is the ONLY field that may differ.
    assert "computed_at" in card and "computed_at" in alias
    card.pop("computed_at"), alias.pop("computed_at")
    assert alias == card, (
        "/.well-known/agent.json and /.well-known/agent-card.json serve "
        "different cards — two A2A cards again")
