"""
Tests for the two backend-generated A2A agent cards advertising the WorkOS
OAuth2 (authorization_code + RFC 7591 DCR) enterprise/marketplace path.

Regression guard for the Gemini Enterprise / Google Cloud Marketplace
Custom-MCP OAuth connect: the card that hosts actually fetch
(`/.well-known/agent-card.json`, generated by routes/agent_a2a.py) MUST
advertise the WorkOS OAuth2 endpoints, ADDITIVELY, without removing the
keyless free-tier / X-API-Key options.

Design constraints (reference_dchub_green_main_0709): NO import of main.py,
NO DB, NO network. Cards are plain dicts; routes are exercised against a
minimal local Flask app that registers ONLY the relevant blueprint.
"""
import json

from flask import Flask

import ai_agent_discovery
import routes.agent_a2a as agent_a2a

WORKOS = "https://beloved-stream-52.authkit.app"
EXPECTED_SCOPES = ["openid", "profile", "email", "offline_access"]


# ── /.well-known/agent-card.json (routes/agent_a2a.py — the marketplace card) ─
def _agent_a2a_client():
    app = Flask(__name__)
    app.register_blueprint(agent_a2a.agent_a2a_bp)
    return app.test_client()


def test_agent_card_json_serializable():
    # _card() adds computed_at; whole thing must round-trip through JSON.
    json.dumps(agent_a2a._card())


def test_agent_card_advertises_workos_oauth2_authorization_code():
    oauth = agent_a2a.AGENT_CARD["auth"]["oauth2"]
    assert oauth["type"] == "oauth2"
    assert oauth["grant_type"] == "authorization_code"
    assert oauth["issuer"] == WORKOS
    assert oauth["authorization_endpoint"] == f"{WORKOS}/oauth2/authorize"
    assert oauth["token_endpoint"] == f"{WORKOS}/oauth2/token"
    # DCR (RFC 7591) — the field Gemini Enterprise / Marketplace requires.
    assert oauth["registration_endpoint"] == f"{WORKOS}/oauth2/register"
    assert oauth["scopes"] == EXPECTED_SCOPES


def test_agent_card_free_tier_auth_intact():
    """OAuth2 must be ADDITIVE — free-tier keyless + X-API-Key untouched."""
    auth = agent_a2a.AGENT_CARD["auth"]
    assert auth["default"] == "none"
    assert "none" in auth["modes"]
    assert "api_key" in auth["modes"]
    assert "oauth2" in auth["modes"]
    # keyless free tier still explicitly declared
    assert auth["api_key"]["free_tier"]["no_signup"] is True
    assert auth["api_key"]["header"] == "X-API-Key"


def test_agent_card_marketplace_marker_and_tool_total():
    assert agent_a2a.AGENT_CARD["a2a_marketplace_ready"] is True
    # Honest tool total (live manifest = source of truth), skills are a subset.
    assert agent_a2a.AGENT_CARD["mcp_tools"]["total"] == 74
    assert agent_a2a.AGENT_CARD["mcp_tools"]["skills_are_subset"] is True
    assert agent_a2a.AGENT_CARD["endpoints"]["mcp_manifest"] == \
        "https://dchub.cloud/.well-known/mcp.json"


def test_agent_card_route_serves_oauth2():
    resp = _agent_a2a_client().get("/.well-known/agent-card.json")
    assert resp.status_code == 200
    body = resp.get_json()
    assert body["auth"]["oauth2"]["registration_endpoint"] == f"{WORKOS}/oauth2/register"
    assert body["auth"]["default"] == "none"


# ── /.well-known/agent.json (ai_agent_discovery.py — A2A 0.2.1 alias) ─────────
def test_discovery_card_oauth2_scheme_added_additively():
    schemes = ai_agent_discovery.A2A_AGENT_CARD["authentication"]["schemes"]
    names = [s["scheme"] for s in schemes]
    # apiKey scheme MUST remain (free tier keyless), oauth2 added alongside.
    assert "apiKey" in names
    assert "oauth2" in names
    apikey = next(s for s in schemes if s["scheme"] == "apiKey")
    assert apikey["name"] == "X-API-Key"
    oauth = next(s for s in schemes if s["scheme"] == "oauth2")
    assert oauth["flow"] == "authorizationCode"
    assert oauth["issuer"] == WORKOS
    assert oauth["authorizationUrl"] == f"{WORKOS}/oauth2/authorize"
    assert oauth["tokenUrl"] == f"{WORKOS}/oauth2/token"
    assert oauth["registrationUrl"] == f"{WORKOS}/oauth2/register"
    assert oauth["scopes"] == EXPECTED_SCOPES


def test_discovery_card_serializable():
    json.dumps(ai_agent_discovery.A2A_AGENT_CARD)
