#!/usr/bin/env python3
"""tests/test_api_contract_baseline_no_abs_paths.py — a DERIVED, COMMITTED
artifact must not record one machine's filesystem.

NO NETWORK, NO DB, NO APP BOOT. This imports scripts/api_response_contract.py,
which is stdlib-only by design and whose CLI sits behind
`if __name__ == "__main__"`, so importing it runs nothing.

What shipped
------------
contracts/api_response_surface.json is regenerated by

    python3 scripts/api_response_contract.py baseline

and committed. Its `parse_errors` array carried this into the repo:

    pipeline_drafts_api.py: [Errno 2] No such file or directory:
      '/private/tmp/claude-501/-Users-...-worktrees-admiring-mendel-99907d/
       .../wt-deadwriters/pipeline_drafts_api.py'

`git ls-files` still listed pipeline_drafts_api.py while ONE worktree had it
mid-delete, so that worktree's transient state became repo truth: a path that
exists on no other machine, sitting in the file every regeneration diffs
against. The extractor's `rel` was already repo-relative — the path came from
`str(e)` on the OSError, which appends `e.filename`. #3530 kept the reason and
dropped the machine.

Why three tests and not one
---------------------------
The artifact scan ALONE IS VACUOUS TODAY. `parse_errors` is `[]`, so "no entry
holds an absolute path" is true of zero entries, and it would stay green with
the detector broken, the hardening reverted, or the key renamed out from under
it. That is the exact shape tests/_scan_floors.py exists to stop. So:

  1. the detector is proved to FIRE, against the real string that shipped;
  2. the extractor is proved to PRODUCE a clean message for an unreadable
     file — this is the one that goes red if the hardening is reverted;
  3. only then is the committed artifact scanned.

(3) is the backstop, catching a leak that arrives by some route (2) does not
model. (1) and (2) are what stop (3) being decoration.
"""
import importlib.util
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load_extractor():
    """Load scripts/api_response_contract.py WITHOUT putting scripts/ on
    sys.path.

    `sys.path.insert(0, ".../scripts")` is session-global once any test does
    it. Five names under scripts/ used to collide with top-level repo modules
    (ai_wars_response_generator, eia_gas_bulk_loader, eia_generator_reseed,
    firstlight_fiber_seed, push_firstlight); those are gone as of #3536, and
    tests/test_no_root_scripts_module_shadowing.py now rejects any new one.

    The idiom here does not depend on that. Loading by path wants exactly one
    module and knows where it is, so it never mutates state the rest of the
    session inherits — which is the property worth keeping whether or not a
    collision happens to exist today.
    """
    path = os.path.join(ROOT, "scripts", "api_response_contract.py")
    spec = importlib.util.spec_from_file_location("_api_response_contract", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)   # safe: the CLI is behind `if __name__`
    return mod


G = _load_extractor()

BASELINE = os.path.join(ROOT, "contracts", "api_response_surface.json")

# An ABSOLUTE path, as distinct from the repo-relative `rel` the extractor is
# supposed to emit. The lookbehind is the whole trick: a relative path with
# nested directories ("routes/sub/foo.py") also contains "/seg/", but every
# slash in it FOLLOWS a word character. An absolute path's leading slash
# follows a quote, a space, or the start of the string.
_ABS_PATH_RE = re.compile(r"""(?<![\w.\-])(?:[A-Za-z]:[\\/]|/)[^\s'"]{2,}""")

# The real entry that shipped in the committed baseline, kept verbatim as the
# must-fail control. If the detector stops flagging THIS, it protects nothing.
_LEAKED_2026_08 = (
    "pipeline_drafts_api.py: [Errno 2] No such file or directory: "
    "'/private/tmp/claude-501/-Users-jonathanmartone-dchub-backend--claude-"
    "worktrees-admiring-mendel-99907d/1717cf85-6a03-4d7a-bae5-ea7d8cc74e0c/"
    "scratchpad/wt-deadwriters/pipeline_drafts_api.py'"
)


def _absolute_paths_in(message):
    """Every absolute-looking path in one parse_errors entry."""
    return _ABS_PATH_RE.findall(message)


# ── 1. the detector must be able to fire ────────────────────────────────────

def test_detector_flags_the_string_that_actually_shipped():
    hits = _absolute_paths_in(_LEAKED_2026_08)
    assert hits, (
        "the absolute-path detector no longer flags the exact entry that "
        "shipped in contracts/api_response_surface.json — every other "
        "assertion in this file is now vacuous"
    )
    assert any("wt-deadwriters" in h for h in hits), hits


def test_detector_does_not_flag_a_repo_relative_path():
    """A nested `rel` contains slashes too. Flagging it would make the fence
    cry wolf, and a fence that cries wolf gets deleted."""
    for benign in (
        "routes/sub/foo.py: [Errno 2] No such file or directory",
        "pipeline_drafts_api.py: [Errno 2] No such file or directory",
        "util/deals.py: invalid syntax (<unknown>, line 12)",
    ):
        assert _absolute_paths_in(benign) == [], benign


# ── 2. the extractor must not put one there in the first place ──────────────

def test_extractor_records_an_unreadable_file_without_the_machine_path():
    """The reproduction: `git ls-files` names a path that will not open.

    Nested on purpose — it proves the detector tolerates the slashes in `rel`
    while still catching an absolute path in the same string.
    """
    missing = "__no_such_dir_for_contract_test__/vanished.py"
    original = G._git_files
    try:
        G._git_files = lambda: [missing]
        surface = G.extract_surface()
    finally:
        G._git_files = original

    errors = surface["parse_errors"]
    assert len(errors) == 1, f"expected exactly one parse error, got {errors}"
    msg = errors[0]

    assert _absolute_paths_in(msg) == [], (
        f"the extractor put an absolute path back into parse_errors: {msg!r} "
        "— see the OSError branch of extract_surface(); str(e) appends "
        "e.filename, which is the absolute path it just tried to open"
    )
    assert G.REPO not in msg, (
        f"parse_errors leaks this machine's repo root: {msg!r}"
    )
    # Still USEFUL: it has to name the file and say why, or we have traded a
    # leak for an unactionable error.
    assert msg.startswith(missing + ":"), msg
    assert "No such file or directory" in msg, msg


# ── 3. the committed artifact, as the backstop ──────────────────────────────

def test_committed_baseline_carries_no_absolute_path():
    with open(BASELINE, "r", encoding="utf-8") as fh:
        surface = json.load(fh)

    offenders = [
        (entry, _absolute_paths_in(entry))
        for entry in surface.get("parse_errors", [])
        if _absolute_paths_in(entry)
    ]
    assert not offenders, (
        "contracts/api_response_surface.json records absolute path(s) from "
        f"the machine that regenerated it: {offenders}. Regenerate on a clean "
        "tree with: python3 scripts/api_response_contract.py baseline"
    )


def test_committed_baseline_parse_error_count_matches_the_list():
    """Not decoration: it is the only assertion in this file that is not
    trivially true when parse_errors is empty, and it fails if a regeneration
    ever writes the count and the list out of step."""
    with open(BASELINE, "r", encoding="utf-8") as fh:
        surface = json.load(fh)

    assert surface["stats"]["parse_errors"] == len(surface["parse_errors"]), (
        f"stats.parse_errors={surface['stats']['parse_errors']} but the list "
        f"holds {len(surface['parse_errors'])} entries"
    )
