"""Guards for recipe_lifecycle.py + the v4 report metric it feeds.

Perplexity round-5 (2026-07-30): recipe lifecycle becomes a first-class fact
(started/completed rows in recipe_executions) instead of an inference over
tool-call rows. The rules pinned here are the ones that made the schema worth
building — and the ones this repo has paid for before:

  1. the identity key is the EXECUTION ID, never session_id (rotates per
     connection, ~1.2 calls/session — keying on it was the exact defect this
     schema exists to avoid);
  2. lifecycle events must never become tool-call rows (they would inflate
     the episode metrics they replace) — the track dispatch runs BEFORE the
     tool check and before any call-table write;
  3. every SQL string that executes WITH bound params is emulated through
     psycopg2 substitution (a stray literal % eats an argument — the
     2026-07-17 /api/v1/map outage class);
  4. abandonment is DERIVED at read time from a missing completion, never
     written by inference;
  5. the rendered migration on disk matches the module (LIVE≠repo-DDL class)
     — hand-editing either drifts the other.

No DB, no network, no Flask app: fake cursors capture SQL + params.
"""
import json
import re
from pathlib import Path

import pytest

rl = pytest.importorskip("recipe_lifecycle")
asr = pytest.importorskip("routes.agent_success_report")
dl = pytest.importorskip("mcp_calls_deloop")

ROOT = Path(__file__).resolve().parent.parent


class _Cur:
    def __init__(self):
        self.executed = []

    def execute(self, sql, params=None):
        self.executed.append((sql, params))

    def __enter__(self):
        return self

    def __exit__(self, *a):
        return False


class _Conn:
    def __init__(self):
        self.cur = _Cur()

    def cursor(self):
        return self.cur


def _emulate(sql, params):
    """psycopg2-style substitution over the exact SQL we execute. The raise,
    if any, IS the assertion — it is what production would do. Returns the
    substituted text so callers can assert every arg landed."""
    sentinels = tuple(f"__ARG{i}__" for i in range(len(params)))
    out = sql % sentinels
    for s in sentinels:
        assert s in out, f"an argument never bound: {s}"
    return out


# ── rule 5: DDL owned by the module, migration derived ─────────────────────

def test_ddl_shape_and_identity_contract():
    ddl = rl.TABLE_DDL
    assert "CREATE TABLE IF NOT EXISTS recipe_executions" in ddl
    assert "recipe_execution_id TEXT PRIMARY KEY" in ddl
    # session_id present for forensics — but NEVER the key (rule 1). The DDL
    # has exactly one PRIMARY KEY and the line above pins whose it is.
    assert "session_id" in ddl
    assert ddl.count("PRIMARY KEY") == 1
    assert "started_at          TIMESTAMPTZ NOT NULL" in ddl
    for outcome in rl.VALID_OUTCOMES:
        assert f"'{outcome}'" in ddl, f"outcome CHECK missing {outcome!r}"
    # CREATE-only: the apply workflow refuses destructive verbs, so the
    # module must never render one.
    for stmt in rl.all_ddl_statements():
        assert not re.search(r"^\s*(DROP|DELETE|TRUNCATE|ALTER|GRANT)\b",
                             stmt, re.I | re.M), f"destructive verb in: {stmt[:80]}"


def test_migration_file_matches_the_module():
    """The migration on disk is RENDERED from the module — hand-editing
    either one drifts the other (the hand-carried-suffix failure the identity
    views hit in July)."""
    mig = (ROOT / "migrations" / "2026-07-30_recipe_executions.sql").read_text()
    assert "GENERATED by scripts/render_recipe_lifecycle_ddl.py" in mig
    for stmt in rl.all_ddl_statements():
        assert stmt.strip() in mig, "migration drifted from recipe_lifecycle.py"


def test_apply_workflow_exists_and_is_dispatch_only():
    """Applying needs DATABASE_URL (repo secrets) — CI is the auditable place.
    The workflow must be manual-only with the APPLY confirmation, never
    scheduled or push-triggered."""
    wf = (ROOT / ".github" / "workflows" / "apply-recipe-lifecycle.yml").read_text()
    assert "workflow_dispatch" in wf
    assert "schedule" not in wf
    assert '!= "APPLY"' in wf
    assert "render_recipe_lifecycle_ddl.py --apply" in wf
    assert "pg_get_constraintdef" in wf, "verify step lost the outcome-enum check"
    assert "indisprimary" in wf, "verify step lost the id-keyed check"


# ── writer validation: refuse, never coerce ────────────────────────────────

def test_record_refuses_bad_payloads():
    conn = _Conn()
    assert rl.record_lifecycle_event(None, {})[0] is False
    ok, err = rl.record_lifecycle_event(conn, {"phase": "started"})
    assert not ok and "recipe_execution_id" in err
    ok, err = rl.record_lifecycle_event(
        conn, {"recipe_execution_id": "x", "phase": "resumed"})
    assert not ok and "phase" in err
    # A mislabeled outcome is worse than a dropped event — refused outright,
    # so the started row stays and honestly reads as abandoned.
    ok, err = rl.record_lifecycle_event(
        conn, {"recipe_execution_id": "x", "phase": "completed",
               "outcome": "ok"})
    assert not ok and "outcome" in err
    assert conn.cur.executed == [], "a refused payload must write nothing"


def test_started_insert_is_idempotent_and_binds():
    conn = _Conn()
    ok, err = rl.record_lifecycle_event(conn, {
        "recipe_execution_id": "11111111-2222-3333-4444-555555555555",
        "phase": "started", "source": "execute_plan",
        "intent": "rank markets for a 200 MW AI campus",
        "intent_class": "market_ranking",
        "api_key": "dch_live_abc", "session_id": "sid-1",
        "platform": "perplexity", "user_agent": "node",
        "started_at": "2026-07-30T10:00:00Z",
    })
    assert ok and err is None
    (sql, params), = conn.cur.executed
    assert "ON CONFLICT (recipe_execution_id) DO NOTHING" in sql, \
        "a re-delivered started event must never duplicate or overwrite"
    out = _emulate(sql, params)
    assert "__ARG0__" in out  # the execution id bound first
    assert params[0] == "11111111-2222-3333-4444-555555555555"


def test_completed_upsert_finalizes_but_never_rewrites_identity():
    """Completion is an upsert so a LOST started event still yields a full
    row — but on conflict, only terminal fields update: the started row's
    identity and started_at win (completion finalizes; it never rewrites who
    started the recipe or when)."""
    conn = _Conn()
    ok, err = rl.record_lifecycle_event(conn, {
        "recipe_execution_id": "abc", "phase": "completed",
        "outcome": "completed", "started_at": "2026-07-30T10:00:00Z",
        "completed_at": "2026-07-30T10:00:21Z", "duration_ms": 21000,
        "steps_planned": 4,
        "status_counts": {"executed": 2, "gated_preview": 1,
                          "skipped_meta": 1, "skipped_unresolved": 1},
    })
    assert ok and err is None
    (sql, params), = conn.cur.executed
    assert "ON CONFLICT (recipe_execution_id) DO UPDATE SET" in sql
    set_clause = sql.split("DO UPDATE SET", 1)[1]
    for terminal in ("completed_at", "outcome", "duration_ms", "status_counts"):
        assert terminal in set_clause
    for frozen in ("api_key", "session_id", "platform", "user_agent",
                   "ip_address", "started_at", "intent"):
        assert not re.search(rf"^\s*{frozen}\s*=", set_clause, re.M), \
            f"completion must not rewrite {frozen} on an existing row"
    _emulate(sql, params)
    # steps derived from status_counts — skipped folds both skip kinds.
    assert params[-7:-1] == (4, 2, 1, 0, 0, 2)
    assert json.loads(params[-1])["executed"] == 2


def test_writer_sql_has_no_stray_percent():
    """Both writers always run WITH params — every % must be a %s."""
    for sql in (rl._INSERT_STARTED, rl._UPSERT_COMPLETED):
        assert sql.count("%") == sql.count("%s"), \
            "a literal % in a with-params query eats an argument (map-outage class)"


# ── rule 2: the track dispatch must precede every call-table write ─────────

def test_track_dispatch_runs_before_the_call_tables():
    """Textual placement pin over flask_mcp_endpoints.track_tool_call: the
    recipe_lifecycle dispatch (the CODE branch, not a comment) must sit
    before the missing-tool return and before both call-table INSERTs, so a
    lifecycle event can never be logged as a phantom tool call."""
    src = (ROOT / "flask_mcp_endpoints.py").read_text()
    h = src.index("def track_tool_call")
    dispatch = src.index('== "recipe_lifecycle"', h)
    record = src.index("record_lifecycle_event(_rl_conn, body)", h)
    missing_tool = src.index('"missing tool"', h)
    call_log = src.index("INSERT INTO mcp_call_log", h)
    legacy = src.index("INSERT INTO mcp_tool_calls", h)
    assert dispatch < missing_tool, "dispatch must precede the tool check"
    assert record < missing_tool
    assert dispatch < call_log and dispatch < legacy
    # skew-safety is the missing-tool return itself: the gateway payload
    # carries no `tool`, so a backend without the dispatch drops it there.


# ── the v4 report metric ───────────────────────────────────────────────────

def test_report_metric_sql_binds_and_carries_exclusions():
    """Same emulation + population discipline as the second-recipe query:
    4 placeholders, synthetic + crawler exclusions from the shared modules
    (never a third hand-kept list), regex form only next to params."""
    sql = asr._recipe_lifecycle_sql()
    assert "recipe_executions" in sql
    assert "mcp_call_log" not in sql and "mcp_tool_calls" not in sql
    assert dl.internal_tag_regex_predicate("platform") in sql
    assert dl.real_ua_predicate("user_agent") in sql
    assert "ILIKE" not in sql, "classifier fragments are unsafe next to params"
    out = _emulate(sql, ("__A__",) * 4)
    assert out.count("__ARG") >= 4


def test_report_metric_derives_abandonment_and_excludes_in_flight():
    """Rule 4: abandoned = outcome IS NULL past the threshold, computed in
    the read — and a fresh NULL is in_flight, excluded from the denominator
    (an execution started 30s before the build is not abandoned)."""
    sql = asr._recipe_lifecycle_sql()
    assert "outcome IS NULL" in sql
    assert "make_interval(mins => %s)" in sql
    assert "in_flight" in sql
    for outcome in ("completed", "failed", "abandoned"):
        assert f"'{outcome}'" in sql
    # rule 1 again, at the read layer: nothing in this query touches
    # session_id — the row IS the unit, identity columns are for joins.
    assert "session_id" not in sql


def test_report_metric_contract_declares_the_lifecycle_semantics():
    m = asr.METRICS["recipe_completion_rate"]
    assert m["definition_version"] == 1
    joined = " ".join([m["definition"], m["observation"]]
                      + list(m["assumptions"]))
    assert "abandoned" in joined
    assert ("in-flight" in joined.lower()) or ("in flight" in joined.lower())
    assert "session_id" in joined, \
        "the never-session_id identity rule must be declared, not remembered"
    assert "recipe_executions" in m["source"]
    assert any("Perplexity" in c for c in m["consumers"])


def test_envelope_v4_documents_the_addition():
    # >= not ==: v4 is where recipe lifecycle landed; later envelope versions
    # (v5 added the 07-31 partner-round metrics) must not retro-fail this pin.
    assert asr.REPORT_DEFINITION_VERSION >= 4
    entry = asr.REPORT_DEFINITION_CHANGELOG[4]
    assert "recipe_completion_rate" in entry
    assert "recipe_executions" in entry
    assert "second_recipe_take_up_pct" in entry, \
        "v4 must state the neighbouring metric did NOT move"


def test_offline_build_carries_the_metric_in_execution_quality(monkeypatch):
    """Degraded path: the new block must appear in execution_quality with an
    explicit non-value status — never a silent absence, never an invented 0."""
    monkeypatch.delenv("DATABASE_URL", raising=False)
    monkeypatch.delenv("NEON_DATABASE_URL", raising=False)
    p = asr._build_report()
    eq = next(s for s in p["sections"] if s["section"] == "execution_quality")
    block = eq["metrics"]["recipe_completion_rate"]
    assert block["value"] is None
    assert block["status"] in ("UNAVAILABLE", "UNMEASURED")
    conf = p["confidence"]["recipe_lifecycle_denominator"]
    assert conf["state"] == "unavailable" and conf["why"].strip()
