"""/connect is a HUB: cards and deep links. It does not carry install copy.

WHY THIS EXISTS. Four surfaces describe the same MCP install — /connect
(this repo), /connect-mcp (dchub-frontend), /install/<platform> (GENERATED by
dchub-frontend/scripts/generate-install-pages.py) and /integrations/<platform>.
The generator is the owner; its own source says why:

    windsurf uses `serverUrl`, NOT `url`
    cline    uses `type: "streamableHttp"`
    claude_desktop uses `transport: "http"`
    Hand-writing these from memory is how you ship a config that silently
    does not load.

/connect hand-wrote them anyway, and on 2026-09-08 all three of its client
configs disagreed with the canonical source (dchub-mcp-server server.mjs,
`persist_config.clients` — the same snippets claim_free_key hands agents):

  claude-desktop   "transport": "streamable-http"   canon: "http"
  cursor           "transport": "streamable-http"   canon: no transport key
  claude-code      --transport streamable-http      canon: --transport http

`streamable-http` appears ZERO times as a transport in the canonical source.
None of these fail loudly — a wrong transport is a connector that silently
does not load, on the page whose whole job is the first successful install.

WHAT THIS PINS. connect.html states no MCP client config. It may carry deep
links (cursor://, vscode:) and endpoint URLs; it may not restate the shape of
a config file, because this repo has no copy of the canon to check it against.
"""
import os
import re

_HERE = os.path.dirname(__file__)
_CONNECT = os.path.join(_HERE, "..", "static", "connect.html")

# ★ FLOOR. Every assertion below is "X is absent". Absence is also what a
# missing, emptied or renamed file looks like, and those must not read as a
# pass. Nothing here is a claim about the page's content — only that there IS
# a page, and that the picker it exists to serve is still in it.
_MIN_BYTES = 20_000
_MIN_INSTALL_LINKS = 8


def _html():
    with open(_CONNECT, encoding="utf-8") as f:
        return f.read()


def test_the_page_is_here_and_is_the_picker():
    """The floor. Without it, every guard below passes on an empty file."""
    html = _html()
    assert len(html) >= _MIN_BYTES, (
        "static/connect.html is %d bytes (floor %d) — the guards below assert "
        "ABSENCE and would all pass vacuously on a stub." % (len(html), _MIN_BYTES)
    )
    assert 'class="picker-card"' in html, (
        "the platform picker is gone from connect.html — this guard protects "
        "the picker's install copy and no longer knows what it is looking at"
    )


def test_connect_states_no_mcp_client_config():
    offenders = []
    if "mcpServers" in _html():
        offenders.append('an inline "mcpServers" config block')
    if re.search(r'"transport"\s*:', _html()):
        offenders.append('an inline "transport" key')
    if re.search(r"--transport\s+\S+", _html()):
        m = re.search(r"--transport\s+(\S+)", _html())
        # The CLI one-liner is allowed to name the transport, but only the
        # canonical value. `streamable-http` is the exact string that shipped.
        if m.group(1).strip("'\"") != "http":
            offenders.append("a --transport value of %r" % m.group(1))
    assert not offenders, (
        "connect.html restates MCP client config: " + "; ".join(offenders) +
        ". That shape is owned by dchub-frontend/scripts/generate-install-pages.py, "
        "which copies it from the canonical persist_config.clients. This repo "
        "cannot check a hand-written copy against canon, so it must not carry one — "
        "link to /install/<platform> instead."
    )


def test_streamable_http_is_never_named_as_a_transport():
    """The exact wrong value that shipped, pinned by name."""
    assert "streamable-http" not in _html(), (
        "'streamable-http' is back in connect.html. It is not a transport value "
        "the Claude CLI or claude_desktop_config.json accepts — canon is 'http' "
        "— and it appears ZERO times in dchub-mcp-server's persist_config."
    )


def test_the_picker_sends_people_to_the_generated_pages():
    links = set(re.findall(r"/install/([a-z0-9-]+)", _html()))
    assert len(links) >= _MIN_INSTALL_LINKS, (
        "connect.html links to only %d /install/ pages (floor %d): %s. The "
        "generator serves twelve; a platform with no link here is a platform "
        "whose install page nobody can reach from the hub."
        % (len(links), _MIN_INSTALL_LINKS, sorted(links))
    )
    # These five had NO route from the picker at all before 2026-09-08.
    for slug in ("claude-desktop", "windsurf", "cline", "gemini-cli", "antigravity"):
        assert slug in links, (
            "/install/%s is served by the generator but is unreachable from "
            "the /connect picker" % slug
        )
