-- GENERATED by scripts/render_recipe_lifecycle_ddl.py from recipe_lifecycle.py — do not hand-edit; edit the module and re-render.

CREATE TABLE IF NOT EXISTS recipe_executions (
    -- gateway-minted UUID; both lifecycle events carry it, so either event
    -- arriving first (or alone) still yields exactly one row
    recipe_execution_id TEXT PRIMARY KEY,
    source              TEXT NOT NULL DEFAULT 'execute_plan',
    intent              TEXT,
    intent_class        TEXT,
    planner_version     TEXT,
    -- identity components of the agent-day unit (durable api_key first).
    -- session_id is forensics/fallback ONLY — it rotates per connection and
    -- must never be used as the identity key (measured 2026-07-01).
    api_key             TEXT,
    session_id          TEXT,
    platform            TEXT,
    client_name         TEXT,
    user_agent          TEXT,
    ip_address          TEXT,
    tier                TEXT,
    started_at          TIMESTAMPTZ NOT NULL,
    completed_at        TIMESTAMPTZ,
    -- NULL while in flight; a NULL older than the abandonment threshold
    -- reads as 'abandoned' (derived at read time, never backfilled)
    outcome             TEXT CHECK (outcome IN ('completed','abandoned','failed')),
    duration_ms         INTEGER,
    steps_planned       INTEGER,
    steps_executed      INTEGER,
    steps_gated         INTEGER,
    steps_failed        INTEGER,
    steps_not_run       INTEGER,
    steps_skipped       INTEGER,
    -- raw per-status counts from the gateway — survives new step statuses
    -- without a schema change (the derived columns above just miss them)
    status_counts       JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_recipe_executions_started_at ON recipe_executions (started_at);

CREATE INDEX IF NOT EXISTS idx_recipe_executions_api_key_started ON recipe_executions (api_key, started_at) WHERE api_key IS NOT NULL;
