"""brain_codegen_expose.py — Brain CODEGEN: auto-expose a dataset as a read API.

The first FEATURE recipe (L22 only had MECHANICAL fix recipes). When a dataset the
brain tracks has no public read API, the brain writes the COMPLETE additive route
(not a skeleton), SELF-TESTS it against the live DB, ast-validates the result, and
opens a READY (CI-green, one-click-merge) PR for the operator. It NEVER merges —
the operator presses the button (Option A: "auto-prepare the safe ones to the
gate", respecting brain_self_director's hard line: no autonomous merge authority).

Safety:
  • ADDITIVE-ONLY: appends ONE route function to an ALREADY-REGISTERED blueprint
    file (no main.py edit, no new blueprint, no edit to existing code/behavior).
  • SELF-TEST GATE: runs the generated SELECT against the live DB; ABORTS if it
    errors or returns 0 rows — never opens a PR for a broken endpoint.
  • AST-VALIDATED: the modified file must ast.parse cleanly before any commit.
  • Allowlisted recipes only (EXPOSURE_BACKLOG), per-run CAP, kill switch.
  • Ships DARK: BRAIN_CODEGEN_EXPOSE_ENABLED default OFF → opens NO PR (dry-run
    returns the generated code + self-test so a human can inspect first).
"""
import ast
import datetime
import logging
import os

import psycopg2
from flask import Blueprint, jsonify, request
from utc_clock import utc_now

log = logging.getLogger("brain_codegen_expose")
codegen_expose_bp = Blueprint("brain_codegen_expose", __name__)

_CAP_PER_RUN = 1


def _dsn() -> str:
    return os.environ.get("DATABASE_URL") or os.environ.get("NEON_DATABASE_URL") or ""


def _enabled() -> bool:
    return str(os.environ.get("BRAIN_CODEGEN_EXPOSE_ENABLED", "")).lower() in ("1", "true", "yes")


def _admin_ok() -> bool:
    expected = os.environ.get("DCHUB_ADMIN_KEY") or os.environ.get("DCHUB_INTERNAL_KEY")
    provided = request.headers.get("X-Admin-Key") or request.args.get("admin_key") or ""
    return bool(expected) and provided == expected


# ── The recipe backlog: datasets to expose. One row per dataset. ────────────
# Each appends a read route to an ALREADY-REGISTERED blueprint file (additive).
EXPOSURE_BACKLOG = [
    {
        "key": "generator_inventory",
        "table": "generator_inventory",
        "source_filter": "source = 'eia860m'",
        "route_path": "/api/v1/generator-inventory",
        "func_name": "get_generator_inventory_public",
        "target_file": "routes/generation_pipeline_ingest.py",
        "blueprint": "gen_pipeline_ingest_bp",
        "anchor": "def register_generation_pipeline_ingest(app):",
        "return_cols": ["plant_name", "entity_name", "state", "ba_code",
                        "technology", "energy_source", "capacity_mw", "status"],
        "order_by": "capacity_mw DESC NULLS LAST",
        "filters": [
            ("state", "UPPER(state) = %s", "upper2"),
            ("ba", "UPPER(ba_code) = %s", "upper"),
            ("technology", "technology ILIKE %s", "ilike"),
            ("status", "status ILIKE %s", "ilike"),
            ("min_mw", "capacity_mw >= %s", "float"),
        ],
        "title": "operable US generator inventory by balancing authority (EIA-860M)",
    },
]


def _gen_route_code(spec: dict) -> str:
    """Build the COMPLETE additive route function source (string)."""
    cols = ", ".join(spec["return_cols"])
    flines = []
    for param, sql, kind in spec["filters"]:
        if kind == "upper2":
            flines.append(f'    if args.get("{param}"):\n'
                          f'        where.append("{sql}"); params.append(args["{param}"].upper()[:2])')
        elif kind == "upper":
            flines.append(f'    if args.get("{param}"):\n'
                          f'        where.append("{sql}"); params.append(args["{param}"].upper()[:20])')
        elif kind == "ilike":
            flines.append(f'    if args.get("{param}"):\n'
                          f'        where.append("{sql}"); params.append("%" + args["{param}"] + "%")')
        elif kind == "float":
            flines.append(f'    if args.get("{param}"):\n'
                          f'        try:\n'
                          f'            where.append("{sql}"); params.append(float(args["{param}"]))\n'
                          f'        except ValueError:\n'
                          f'            pass')
    filt = "\n".join(flines)
    return f'''

@{spec["blueprint"]}.route("{spec["route_path"]}", methods=["GET"])
def {spec["func_name"]}():
    """Public read API for {spec["title"]}.
    Auto-generated by brain_codegen_expose (self-tested against the live DB).
    Filters: {", ".join(p for p, _, _ in spec["filters"])}, limit (max 5000)."""
    import os as _os
    import psycopg2 as _pg
    dsn = _os.environ.get("DATABASE_URL") or _os.environ.get("NEON_DATABASE_URL") or ""
    if not dsn:
        return jsonify(ok=False, error="no DATABASE_URL"), 503
    args = request.args
    where = ["{spec["source_filter"]}"]
    params = []
{filt}
    try:
        limit = min(int(args.get("limit", 1000)), 5000)
    except (TypeError, ValueError):
        limit = 1000
    sql = ("SELECT {cols} FROM {spec["table"]} WHERE " + " AND ".join(where) +
           " ORDER BY {spec["order_by"]} LIMIT %s")
    params.append(limit)
    try:
        with _pg.connect(dsn, sslmode="require", connect_timeout=8) as c:
            with c.cursor() as cur:
                cur.execute(sql, params)
                cnames = [d[0] for d in cur.description]
                rows = [dict(zip(cnames, r)) for r in cur.fetchall()]
    except Exception as e:
        return jsonify(ok=False, error=str(e)[:160]), 500
    for r in rows:
        for k, v in list(r.items()):
            if v is not None and not isinstance(v, (int, float, bool, str)):
                try:
                    r[k] = float(v)
                except (TypeError, ValueError):
                    r[k] = str(v)
    resp = jsonify(ok=True, count=len(rows),
                   source="{spec["title"]} (DC Hub, dchub.cloud)", rows=rows)
    resp.headers["Cache-Control"] = "public, max-age=3600"
    return resp
'''


def _self_test(spec: dict) -> dict:
    """Run the generated base SELECT against the live DB. Pass = >=1 row, no error."""
    dsn = _dsn()
    if not dsn:
        return {"ok": False, "error": "no DATABASE_URL"}
    cols = ", ".join(spec["return_cols"])
    sql = (f"SELECT {cols} FROM {spec['table']} WHERE {spec['source_filter']} "
           f"ORDER BY {spec['order_by']} LIMIT 1")
    try:
        with psycopg2.connect(dsn, sslmode="require", connect_timeout=8) as c:
            with c.cursor() as cur:
                cur.execute(sql)
                row = cur.fetchone()
                cur.execute(f"SELECT COUNT(*) FROM {spec['table']} WHERE {spec['source_filter']}")
                total = cur.fetchone()[0]
        if not row or not total:
            return {"ok": False, "error": "0 rows — refusing to expose an empty endpoint"}
        return {"ok": True, "total_rows": int(total), "sample_cols": len(spec["return_cols"])}
    except Exception as e:
        return {"ok": False, "error": str(e)[:160]}


def _build_one(spec: dict, dry_run: bool) -> dict:
    out = {"key": spec["key"], "route": spec["route_path"]}
    # 1) self-test the SELECT against the live DB
    st = _self_test(spec)
    out["self_test"] = st
    if not st.get("ok"):
        out["status"] = "aborted_self_test"
        return out
    # 2) generate + ast-validate the MODIFIED target file
    try:
        from routes.brain_pr_opener import _get_file
    except Exception as e:
        out["status"] = "no_pr_opener"; out["error"] = str(e)[:100]; return out
    cur_content, cur_sha = _get_file(spec["target_file"])
    if not cur_content:
        out["status"] = "target_unreadable"; return out
    if f'def {spec["func_name"]}(' in cur_content or spec["route_path"] in cur_content:
        out["status"] = "already_exposed"; return out
    new_func = _gen_route_code(spec)
    anchor = spec["anchor"]
    if anchor not in cur_content:
        out["status"] = "anchor_missing"; return out
    modified = cur_content.replace(anchor, new_func.rstrip() + "\n\n\n" + anchor, 1)
    try:
        ast.parse(modified)
    except SyntaxError as e:
        out["status"] = "ast_invalid"; out["error"] = str(e)[:120]; return out
    out["ast_valid"] = True
    out["generated_lines"] = new_func.count("\n")
    if dry_run or not _enabled():
        out["status"] = "dry_run" if dry_run else "disabled_ships_dark"
        out["generated_code"] = new_func.strip()
        return out
    # 3) open a READY PR (additive; one route appended; CI must pass; human merges)
    try:
        from routes.brain_pr_opener import (_get_default_branch_sha, _create_branch,
                                            _commit_file, _open_pr)
    except Exception as e:
        out["status"] = "no_pr_opener"; out["error"] = str(e)[:100]; return out
    base = _get_default_branch_sha()
    if not base:
        out["status"] = "no_base_sha"; return out
    ts = utc_now().strftime("%Y%m%d%H%M%S")
    branch = f"brain-codegen/expose-{spec['key']}-{ts}"
    if not _create_branch(branch, base):
        out["status"] = "branch_failed"; return out
    msg = f"feat(api): expose {spec['key']} as {spec['route_path']} (brain codegen, self-tested)"
    if not _commit_file(spec["target_file"], modified, msg, branch, cur_sha):
        out["status"] = "commit_failed"; return out
    body = (
        f"## Brain codegen — dataset exposure (READY for your one-click merge)\n\n"
        f"The brain wrote a **complete, additive** read API for `{spec['key']}` and "
        f"**self-tested it against the live DB** before opening this PR.\n\n"
        f"- **Route:** `GET {spec['route_path']}`  (filters: "
        f"{', '.join(p for p, _, _ in spec['filters'])}, limit)\n"
        f"- **Self-test:** {st.get('total_rows'):,} rows in `{spec['table']}` — the SELECT runs clean.\n"
        f"- **Change:** one route function appended to `{spec['target_file']}` "
        f"(already-registered blueprint `{spec['blueprint']}`). No `main.py` edit, "
        f"no edits to existing code — purely additive.\n"
        f"- **AST-validated.** CI must pass before merge.\n\n"
        f"Auto-prepared by `routes/brain_codegen_expose.py` (Option A: the brain prepares "
        f"safe code to the gate; **you** press merge). Kill switch: "
        f"`BRAIN_CODEGEN_EXPOSE_ENABLED=0`.\n"
    )
    pr = _open_pr(msg, branch, body)
    if not pr:
        out["status"] = "pr_failed"; out["branch"] = branch; return out
    out["status"] = "pr_opened_ready"
    out["pr_url"] = pr.get("html_url")
    out["pr_number"] = pr.get("number")
    return out


def run_codegen_expose(dry_run: bool = True) -> dict:
    """Process the backlog (capped). Default dry-run. Real PRs only when
    BRAIN_CODEGEN_EXPOSE_ENABLED=1 AND dry_run is explicitly false."""
    results = []
    done = 0
    for spec in EXPOSURE_BACKLOG:
        if done >= _CAP_PER_RUN:
            break
        try:
            r = _build_one(spec, dry_run)
            results.append(r)
            if r.get("status") in ("pr_opened_ready",):
                done += 1
        except Exception as e:
            results.append({"key": spec.get("key"), "status": "error", "error": str(e)[:140]})
    return {"ok": True, "enabled": _enabled(), "dry_run": dry_run or not _enabled(),
            "cap_per_run": _CAP_PER_RUN, "results": results}


@codegen_expose_bp.route("/api/v1/admin/brain/codegen-expose/run", methods=["POST", "GET"])
def codegen_expose_run():
    if not _admin_ok():
        return jsonify(ok=False, error="admin key required"), 401
    dry = request.args.get("dry_run", "1") != "0"
    return jsonify(run_codegen_expose(dry_run=dry)), 200


def register_codegen_expose(app):
    try:
        app.register_blueprint(codegen_expose_bp)
    except Exception as e:
        log.warning(f"brain_codegen_expose registration: {e}")
