"""
media_showcase.py — DC Hub Media auto-showcase (2026-06-30).
=============================================================

WHY
---
An external AI (Grok), handed DC Hub's tools, produced a sharper data showcase
than DC Hub's own media machine — BUT it hallucinated: it claimed ERCOT is "77%
data-center share" (real: 52.7%), "317 DCPI markets" (real: 311), and "4x YoY"
(not in the data). The existing media machine, meanwhile, is data-signal-driven,
contracting, and has no way to publish a compelling market-pulse or a milestone.

This module is the fix: produce the Grok-style, data-rich showcase content the
machine SHOULD write — but COMPELLING **and** VERIFIED. The differentiator vs a
raw LLM (Grok) is structural:

  · Every number is PULLED LIVE from DC Hub's own endpoints (gather_facts), never
    generated by a model. The composer interpolates verified figures into a
    punchy template — so it cannot hallucinate a 77% that's really 53%.
  · A numeric FACT-CHECK gate (_factcheck) scans the rendered post and rejects any
    number that isn't traceable to a gathered fact — a hard guarantee that the
    "compelling" copy never drifts from the truth.

ROUTES (admin-gated):
  GET  /api/v1/admin/media/showcase/preview?kind=market_pulse|milestone
       → generate + return the post + the verified facts (NO publish)
  POST /api/v1/admin/media/showcase/publish  {kind, [platform, detail]}
       → generate, fact-check, and publish via the existing LinkedIn poster
         (gated by can-publish + the content-quality floor). Never auto-fires;
         a human/cron triggers it.

Kill switch: MEDIA_SHOWCASE_DISABLED=1.
"""
from __future__ import annotations

import json
import logging
import os
import re
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone

from flask import Blueprint, jsonify, request
from routes._swallowed_writes import note_swallowed_write

logger = logging.getLogger(__name__)
media_showcase_bp = Blueprint("media_showcase", __name__)

_BASE = os.environ.get("DCHUB_BACKEND_BASE",
                       "https://dchub-backend-production.up.railway.app")
_ISOS = ["ERCOT", "PJM", "MISO", "SPP"]
# The AI platforms verified as live MCP/data consumers (the moat headline).
_PLATFORMS = ["Claude", "ChatGPT", "Gemini", "Perplexity", "Copilot", "Meta AI", "Grok"]

# Dedup guard: in-process last-published epoch per kind (fast-path only). The
# AUTHORITATIVE guard is now DB-backed (_showcase_last_published_ago / _mark_...)
# so it survives restarts/redeploys AND is shared across replicas — the old
# in-memory-only dict reset on every deploy and wasn't cross-worker, so a
# post-deploy or multi-replica fire republished the same generic card (Cause B
# of the media variety audit). Pass {"force": true} to override for manual posts.
_LAST_PUBLISH: dict[str, float] = {}


def _showcase_conn():
    try:
        import psycopg2
        dsn = os.environ.get("DATABASE_URL") or os.environ.get("NEON_DATABASE_URL")
        if not dsn:
            return None
        c = psycopg2.connect(dsn, sslmode="require", connect_timeout=6)
        c.autocommit = True
        return c
    except Exception:
        return None


def _ensure_showcase_ledger(cur) -> None:
    cur.execute("""
        CREATE TABLE IF NOT EXISTS media_showcase_publishes (
            kind          TEXT PRIMARY KEY,
            last_post     TEXT,
            published_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)


def _showcase_last_published_ago(kind: str) -> float | None:
    """Seconds since this kind last published (DB-backed, cross-worker,
    survives restart). None when never published or DB unavailable."""
    c = _showcase_conn()
    if c is None:
        return None
    try:
        with c.cursor() as cur:
            _ensure_showcase_ledger(cur)
            cur.execute(
                "SELECT EXTRACT(EPOCH FROM (NOW() - published_at)) "
                "  FROM media_showcase_publishes WHERE kind = %s", (kind,))
            row = cur.fetchone()
            return float(row[0]) if row and row[0] is not None else None
    except Exception:
        return None
    finally:
        try: c.close()
        except Exception: pass


def _mark_showcase_published(kind: str, post: str = "") -> None:
    c = _showcase_conn()
    if c is None:
        return
    try:
        with c.cursor() as cur:
            _ensure_showcase_ledger(cur)
            cur.execute("""
                INSERT INTO media_showcase_publishes (kind, last_post, published_at)
                VALUES (%s, %s, NOW() ON CONFLICT DO NOTHING)
                ON CONFLICT (kind) DO UPDATE SET
                    last_post = EXCLUDED.last_post,
                    published_at = NOW()
            """, (kind, (post or "")[:800]))
    except Exception:
        note_swallowed_write("media_showcase_publishes", where="media_showcase._mark_showcase_published")
        pass
    finally:
        try: c.close()
        except Exception: pass


# ── auth + helpers ────────────────────────────────────────────────────
def _admin_key() -> str | None:
    return os.environ.get("DCHUB_ADMIN_KEY") or os.environ.get("DCHUB_INTERNAL_KEY")


def _admin_ok() -> bool:
    import hmac
    ak = (_admin_key() or "").strip()
    ik = (os.environ.get("DCHUB_INTERNAL_KEY") or "").strip()
    got_admin = (request.headers.get("X-Admin-Key") or request.args.get("admin_key") or "").strip()
    got_internal = (request.headers.get("X-Internal-Key") or "").strip()
    if ak and got_admin and hmac.compare_digest(got_admin, ak):
        return True
    # Accept the internal key too, so the server-side heartbeat cron can publish.
    if ik and got_internal and hmac.compare_digest(got_internal, ik):
        return True
    return False


def _disabled() -> bool:
    return str(os.environ.get("MEDIA_SHOWCASE_DISABLED", "")).lower() in ("1", "true", "yes")


def _call(path: str, timeout: int = 20):
    url = _BASE.rstrip("/") + path
    try:
        req = urllib.request.Request(url, method="GET")
        req.add_header("X-DC-Probe", "media-showcase")
        ak = _admin_key()
        if ak:
            req.add_header("X-Admin-Key", ak)
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.loads(r.read().decode("utf-8", "replace"))
    except Exception:
        return {}


def _num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def _fmt(v, unit=""):
    n = _num(v)
    if n is None:
        return None
    s = f"{int(round(n)):,}" if abs(n - round(n)) < 0.05 else f"{n:,.1f}"
    return s + unit


# ── gather VERIFIED facts (every number is live, never model-generated) ──
def gather_showcase_facts() -> dict:
    facts = {"as_of": datetime.now(timezone.utc).isoformat(),
             "verified_numbers": set(), "isos": [], "build_markets": [], "errors": []}

    def _track(*vals):
        for v in vals:
            n = _num(v)
            if n is not None:
                facts["verified_numbers"].add(int(round(n)))

    stats = _call("/api/v1/stats")
    facts["markets"] = stats.get("markets")
    facts["facilities"] = stats.get("facilities")
    facts["fiber_routes"] = stats.get("fiber_routes")
    facts["gas_pipelines"] = stats.get("gas_pipelines")
    _track(facts["markets"], facts["facilities"], facts["fiber_routes"], facts["gas_pipelines"])

    for iso in _ISOS:
        d = _call("/api/v1/interconnection-queue/by-iso?iso=" + iso)
        if not d or d.get("error"):
            continue
        total = _num(d.get("queued_load_total_gw"))
        dc = _num(d.get("queued_load_data_center_gw"))
        share = round(100 * dc / total, 1) if (total and dc) else None
        row = {"iso": iso, "total_gw": total, "dc_gw": dc, "dc_share_pct": share,
               "projects": d.get("project_count")}
        facts["isos"].append(row)
        _track(total, dc, share, d.get("project_count"))

    # ★2026-08-13 — THE QUALIFIER IS THE FACT. /api/v1/ai-capacity-index returns
    # deployable_mw as {"value": 500.0, "note": "Estimate from market depth —
    # refined via ISO interconnect queue join (Q3 2026)."}. This used to read
    # .value and DROP .note, turning an estimate of MARKET DEPTH into a published
    # claim of available power. On 2026-08-13 that shipped to LinkedIn as
    # "Where AI compute can actually land in 90 days: Ashburn ~500 MW" — there is
    # no such capacity in Ashburn, and the number never meant that.
    #
    # ★Same shape as the two failures fixed on 2026-08-12: _internal() collapsing
    # a failure into {} and _fetch_findings() collapsing unmeasured into []. In
    # all three the producer modelled the caveat correctly and the CONSUMER threw
    # away the half that carried the truth. A qualified value must arrive here
    # qualified or not at all.
    cap = _call("/api/v1/ai-capacity-index?horizon=90")
    for m in (cap.get("markets") or [])[:4]:
        dep = m.get("deployable_mw")
        dep_v, dep_note = (dep.get("value"), dep.get("note")) \
            if isinstance(dep, dict) else (dep, None)
        facts["build_markets"].append({"market": m.get("city") or m.get("market"),
                                       "state": m.get("state"), "deployable_mw": _num(dep_v),
                                       "deployable_mw_note": dep_note,
                                       "facility_count": m.get("facility_count")})
        _track(dep_v, m.get("facility_count"))

    facts["platforms"] = _PLATFORMS
    facts["platform_count"] = len(_PLATFORMS)
    _track(len(_PLATFORMS), 7)  # 7 = US ISO count, a stated constant
    return facts


# ── composition-time honesty gate (r-media-canon-gate, 2026-07-02) ────
def _media_gate_denies(text: str, platform: str = "linkedin") -> tuple[bool, list]:
    """Run the one-call pre-queue gate (routes.media_fact_check_guard.
    gate_media_text) BEFORE publishing — the corroboration pass the "86 AI
    agents … up 41% week-over-week" post never went through. Activation
    follows the guard module's own kill-switch (MEDIA_FACT_CHECK_GUARD_ENABLED,
    default OFF) so rollout is a Railway env flip, not a deploy.

    Returns (denied, reasons). With the flag ON, a gate crash fails CLOSED —
    an unprovable number must never ship because a checker hiccuped. With the
    guard module unimportable the gate fails OPEN only because the
    content_publisher drain gate still runs its own checks downstream."""
    try:
        from routes.media_fact_check_guard import _enabled, gate_media_text
    except Exception as e:  # guard missing → publish path unchanged
        logger.warning("[media_showcase] fact-check guard unavailable: %s", str(e)[:120])
        return False, []
    try:
        if not _enabled():
            return False, []
    except Exception:
        return False, []
    # Own autocommit connection for the guard's dedup/quality SELECTs, so a
    # failed query can never poison another transaction (the _live_as_of trap).
    conn = None
    cur = None
    try:
        import psycopg2
        dsn = os.environ.get("DATABASE_URL") or os.environ.get("NEON_DATABASE_URL")
        if dsn:
            conn = psycopg2.connect(dsn, sslmode="require", connect_timeout=6)
            conn.autocommit = True
            cur = conn.cursor()
    except Exception:
        conn = cur = None  # gate_media_text tolerates cur=None (guard 1 surfaces it)
    try:
        res = gate_media_text(cur, text or "", platform)
        return (not res.get("allow", False)), list(res.get("reasons") or [])
    except Exception as e:
        return True, [f"gate raised — failing closed ({str(e)[:100]})"]
    finally:
        try:
            if conn is not None:
                conn.close()
        except Exception:
            pass


# ── the anti-hallucination gate ───────────────────────────────────────
def _factcheck(post: str, facts: dict) -> tuple[bool, list]:
    """Reject the post if it contains a number not traceable to a gathered fact.
    This is the structural guarantee Grok lacked: the compelling copy can never
    drift from the verified data. Tolerant of rounding (+/-1) + ignores years/%
    that are themselves facts."""
    allowed = set(facts.get("verified_numbers") or set())
    # also allow small structural constants used in copy (counts, the year)
    allowed |= {7, 8, 90, 170, 300, 2026}
    bad = []
    for raw in re.findall(r"(?<![\w.])(\d[\d,]*\.?\d*)", post):
        n = _num(raw.replace(",", ""))
        if n is None:
            continue
        ni = int(round(n))
        if any(abs(ni - a) <= 1 for a in allowed):
            continue
        # allow exact decimals that match a fact (e.g. 52.7)
        if any(abs(n - a) < 0.15 for a in allowed):
            continue
        bad.append(raw)
    return (len(bad) == 0), bad


# ── composers (interpolate VERIFIED facts into punchy copy) ───────────
def compose_market_pulse(facts: dict) -> str:
    """★2026-08-13 — rewritten after this composer published a false claim.

    It shipped "Where AI compute can actually land in 90 days: Ashburn ~500 MW"
    to LinkedIn. There is no such available capacity in Ashburn. The number came
    from /api/v1/ai-capacity-index deployable_mw, which the API returns QUALIFIED:

        {"value": 500.0,
         "note": "Estimate from market depth - refined via ISO interconnect
                  queue join (Q3 2026)."}

    The ingest read .value and dropped .note, so an estimate of MARKET DEPTH was
    published as available power, under a 90-day energisation headline the
    platform cannot support at all (DCPI time_to_power floors at 12 months).

    ★Third instance of one shape in two days: _internal() collapsed a failure
    into {}, _fetch_findings() collapsed unmeasured into [], and this collapsed
    a qualified estimate into a bare number. Each time the producer modelled the
    caveat correctly and the CONSUMER discarded the half carrying the truth.

    Built from an explicit parts list rather than one long implicit-concat
    expression, so a future edit cannot silently reattach a claim to a number.
    """
    bm = [b for b in facts.get("build_markets", []) if b.get("deployable_mw")][:3]
    bm_line = " · ".join(f"{b['market']} ~{_fmt(b['deployable_mw'])} MW"
                         for b in bm) or "—"
    # If the SOURCE qualified the number, the copy carries the qualifier.
    note = next((b.get("deployable_mw_note") for b in bm
                 if b.get("deployable_mw_note")), None)

    iso_lines = []
    for r in facts.get("isos", []):
        seg = f"{r['iso']}: {_fmt(r['total_gw'])} GW queued"
        if r.get("dc_share_pct") is not None:
            seg += f", {_fmt(r['dc_share_pct'])}% data-center load"
        if r.get("projects"):
            seg += f" ({_fmt(r['projects'])} projects)"
        iso_lines.append("• " + seg)

    mk = _fmt(facts.get("markets")) or "300+"
    fac = _fmt(facts.get("facilities")) or "15,000+"
    plats = ", ".join(facts.get("platforms", [])[:6]) + " + more"

    parts = ["⚡ DC Hub — US Power Market Pulse · verified live\n\n"]
    # ★NOT "where AI compute can actually land in 90 days". horizon=90 is a
    # capacity-index horizon, not a delivery promise, and no DCPI field can
    # express a sub-12-month time to power.
    parts.append("Deepest AI-ready market depth right now:\n")
    parts.append(f"🟢 {bm_line}\n")
    if note:
        parts.append(f"  ({note})\n")
    parts.append("\n")
    parts.append("The interconnection wall (live ISO queues):\n")
    parts.append("\n".join(iso_lines) + "\n\n")
    parts.append(f"That's {mk} power markets, {fac} facilities, and 7 live US "
                 "ISO queues — ")
    # "not a guess" cannot stand in the same sentence as a modelled estimate.
    parts.append("every figure pulled live and cited, with modelled inputs "
                 "labelled as such, not a quarterly PDF.\n\n" if note else
                 "every figure pulled live and cited, not a guess and not a "
                 "quarterly PDF.\n\n")
    parts.append(f"Queried by {plats} as structured, callable data.\n")
    parts.append("→ dchub.cloud/mcp")
    return "".join(parts)

def compose_milestone(facts: dict, platform: str = "Grok", detail: str = "") -> str:
    ercot = next((r for r in facts.get("isos", []) if r["iso"] == "ERCOT"), {})
    pjm = next((r for r in facts.get("isos", []) if r["iso"] == "PJM"), {})
    others = ", ".join([p for p in facts.get("platforms", []) if p.lower() != platform.lower()][:5])
    n = facts.get("platform_count") or len(_PLATFORMS)
    lines = [f"🤖 {platform} just connected to DC Hub."]
    lines.append("")
    lines.append(f"{platform} is now live on DC Hub's MCP server — joining {others} "
                 "as AI agents that query DC Hub's live data layer instead of guessing "
                 "from stale training data.")
    lines.append("")
    lines.append("Minutes after connecting, it was pulling ground truth and citing it:")
    if ercot:
        seg = f"⚡ ERCOT: {_fmt(ercot.get('total_gw'))} GW in the interconnection queue"
        if ercot.get("dc_share_pct") is not None:
            seg += f", {_fmt(ercot.get('dc_share_pct'))}% data-center load"
        lines.append(seg)
    if pjm:
        lines.append(f"⚡ PJM: {_fmt(pjm.get('total_gw'))} GW queued ({_fmt(pjm.get('projects'))} projects)")
    bm = [b for b in facts.get("build_markets", []) if b.get("deployable_mw")][:3]
    if bm:
        lines.append("⚡ Top deployable markets: " +
                     " · ".join(f"{b['market']} ~{_fmt(b['deployable_mw'])} MW" for b in bm))
    lines.append("")
    mk = _fmt(facts.get("markets")) or "300+"
    fac = _fmt(facts.get("facilities")) or "15,000+"
    lines.append(f"{fac} facilities, {mk} power markets, live queues across 7 US ISOs — "
                 "structured, cited, callable by any agent.")
    lines.append(f"\n{n} AI platforms. One data layer. Live, cited, no PDFs. → dchub.cloud/mcp")
    return "\n".join(lines)


def _build(kind: str, platform: str, detail: str) -> dict:
    facts = gather_showcase_facts()
    post = compose_milestone(facts, platform, detail) if kind == "milestone" \
        else compose_market_pulse(facts)
    ok, bad = _factcheck(post, facts)
    facts_out = {k: (sorted(v) if isinstance(v, set) else v) for k, v in facts.items()}
    return {"kind": kind, "post": post, "char_count": len(post),
            "factcheck_passed": ok, "unverified_numbers": bad,
            "facts": facts_out}


# ── endpoints ─────────────────────────────────────────────────────────
@media_showcase_bp.route("/api/v1/admin/media/showcase/preview", methods=["GET"])
def showcase_preview():
    if not _admin_ok():
        return jsonify(error="unauthorized"), 401
    kind = request.args.get("kind", "market_pulse")
    platform = request.args.get("platform", "Grok")
    out = _build(kind, platform, request.args.get("detail", ""))
    return jsonify(ok=True, **out), 200


@media_showcase_bp.route("/api/v1/admin/media/showcase/publish", methods=["POST"])
def showcase_publish():
    if not _admin_ok():
        return jsonify(error="unauthorized"), 401
    if _disabled():
        return jsonify(skipped="MEDIA_SHOWCASE_DISABLED"), 200
    body = request.get_json(silent=True) or {}
    kind = body.get("kind") or "market_pulse"
    # Dedup: don't republish the same kind within the window (guards cron
    # double-fire AND post-deploy / multi-replica refires). DB-backed so it
    # survives restarts and is shared across workers; the in-memory dict is only
    # a fast local shortcut. 2026-07-03: widen the window to 48h — this generic
    # branded card is near-identical each publish (Cause B), so once/2d is plenty.
    now_ts = time.time()
    try:
        _win_h = max(1, int(os.environ.get("MEDIA_SHOWCASE_DEDUP_HOURS", "48")))
    except Exception:
        _win_h = 48
    _win_s = _win_h * 3600
    if not body.get("force"):
        _db_ago = _showcase_last_published_ago(kind)
        _mem_ago = now_ts - _LAST_PUBLISH.get(kind, 0) if kind in _LAST_PUBLISH else None
        _ago = min([a for a in (_db_ago, _mem_ago) if a is not None], default=None)
        if _ago is not None and _ago < _win_s:
            return jsonify(ok=True, published=False, skipped="deduped_within_window",
                           window_hours=_win_h, seconds_since_last=int(_ago)), 200
    out = _build(kind, body.get("platform", "Grok"), body.get("detail", ""))
    if not out["factcheck_passed"]:
        # The hard guarantee: never publish copy with an unverifiable number.
        return jsonify(ok=False, published=False, reason="factcheck_failed",
                       unverified_numbers=out["unverified_numbers"], post=out["post"]), 200
    # r-media-canon-gate (2026-07-02): the one-call corroboration gate, run
    # BEFORE the post leaves this process. On denial: ONE log line + drop the
    # whole post — never publish a stripped version.
    _denied, _greasons = _media_gate_denies(out["post"], "linkedin")
    if _denied:
        logger.warning("[media_showcase] media gate denied %s: %s",
                       kind, "; ".join(_greasons)[:400])
        return jsonify(ok=False, published=False, reason="media_gate_denied",
                       gate_reasons=_greasons[:8], post=out["post"]), 200
    # Publish via the existing LinkedIn poster (same path the daily quad uses).
    try:
        from linkedin_poster import post_to_linkedin
        raw = post_to_linkedin(text=out["post"], link_url="https://dchub.cloud/mcp",
                               link_title="DC Hub Media",
                               link_desc="Live data-center & power intelligence · dchub.cloud",
                               image_bytes=None)
        # linkedin_poster returns a (ok, dict) TUPLE — the ok flag is [0], NOT
        # inside the dict. A post_urn means LinkedIn accepted the share.
        if isinstance(raw, tuple):
            _flag = bool(raw[0])
            res = raw[1] if (len(raw) > 1 and isinstance(raw[1], dict)) else {}
        else:
            res = raw if isinstance(raw, dict) else {}
            _flag = bool(res.get("ok"))
        published = _flag or bool(res.get("post_urn"))
        if published:
            _LAST_PUBLISH[kind] = now_ts
            _mark_showcase_published(kind, out.get("post", ""))
        return jsonify(ok=True, published=published,
                       post_urn=(res or {}).get("post_urn"),
                       error=(res or {}).get("error"), post=out["post"]), 200
    except Exception as e:
        return jsonify(ok=False, published=False,
                       error=f"{type(e).__name__}: {str(e)[:160]}", post=out["post"]), 200
