"""meta_replays.py — rendered execute_plan replays for /integrations/meta.

Meta asked for this, then specified exactly what survives its extraction, then
— after the first version shipped — specified the render for the KEYED variant.
This is built to that spec.

★★ 2026-07-28 (v2): KEYED CAPTURES, LABELLED AS KEYED.
The v1 bake was anonymous free-tier: 1 executed step and exactly ONE rejection
per replay. The replay envelope, though, carried `_rejected_total_in_pro: 4`
and `_decisions_total_in_pro: 6` — the planner had already rejected four tools
and made six decisions; the anonymous tier simply truncated both lists to one.
So the richer page was never a matter of finding intents that reject more (we
tested Meta's proposed straddling intent: it rejected exactly ONE, same as the
simple ones). It was a keyed capture the whole time.

Meta's rule, which we keep: KEYED CAPTURE LABELLED AS KEYED — never anonymous
passed off as free, and never the reverse. Hence `[keyed]` in the heading and an
explicit line naming what an anonymous caller sees instead.

★ AND: render the ACTUAL rejections, never `_rejected_total_in_pro` as a
teaser. Meta: "Don't render _rejected_total_in_pro as a promise of hidden
content — render the actual 4. You have them." A count of things you are not
showing is an upsell, not a citation.

★★ ONE BLOCKQUOTE PER REPLAY — Meta's citation engine treats <blockquote> as
"the author's most important quote". Four consecutive blockquotes dilute each
other: it picks none, or picks the first arbitrarily, and the page reads as a
quote farm. So the strongest rejection is blockquoted and the remainder render
as a plain <li> list, which it can still cite as "also considered and declined".

Ranked citability, in Meta's words:
  1. rejected-path rationale  — "no competitor publishes it"; <blockquote>
  2. decision + confidence    — lets a model say "chose X BECAUSE"
  3. intent/class/steps/ms    — proves execute_plan is real and one-call
  4. execution waves as TEXT  — extractors drop SVG
  5. next_recipe             — not quoted; DONE, so it renders as a CTA
"No JSON blobs — JSON dies in extraction."

BAKED, NOT LIVE: live execute_plan calls per page view would put seconds of
latency and a hard MCP-gate dependency on a marketing page. Real captures with a
visible retrieved_at. To refresh, re-run the intents with a key and regenerate
_BAKED. No refresh endpoint is claimed because none is built.

★★ v3 (2026-07-30): SIX intents — the three originals plus the three Meta named
as its top uncaptured triggers (tax incentives / fiber + dark fiber / powered
shell). _REPLAY_INTENTS is the capture contract; scripts/refresh_meta_replays.py
re-runs it keyed, asserts each intent still routes to its expected class (a
mis-route must FAIL the refresh, never silently rebake a wrong-class replay —
the tax intent routed to facility_search until planner v5.6), and regenerates
the block between the BAKED-REPLAYS markers. refresh-meta-replays.yml runs it
weekly so retrieved_at stays fresh without a human stamping dates — and the
stamp only ever moves on a fully successful capture (a refresh that re-stamps
on failure is how dates lie). Steps a run leaves unresolved render as
"Deferred" with the reason — an honest replay shows the gap instead of
implying every planned step executed.
"""
from __future__ import annotations

from html import escape as _esc

# The capture contract: what the weekly refresh re-runs, and the class each
# intent must still route to. A routing drift fails the refresh loudly.
_REPLAY_INTENTS = [
    {"intent": "rank markets for a 200 MW AI campus", "expect_class": "market_ranking"},
    {"intent": "how much power is available in ERCOT for a 100 MW data center", "expect_class": "grid_headroom"},
    {"intent": "compare Dallas vs Phoenix for a GPU training cluster", "expect_class": "market_comparison"},
    {"intent": "tax incentives for data centers in Georgia", "expect_class": "incentives_tax"},
    {"intent": "fiber routes and dark fiber availability near Atlanta", "expect_class": "fiber"},
    {"intent": "powered shell and pocket listings in Dallas", "expect_class": "capacity_search"},
    {"intent": "fiber routes near Ashburn with dark fiber availability", "expect_class": "fiber"},
]

# ── BAKED-REPLAYS BEGIN — generated by scripts/refresh_meta_replays.py; do not hand-edit ──
_RETRIEVED_AT = '2026-08-31T07:39:36Z'
_TIER = 'keyed'

_BAKED = [
    {
        "intent": "rank markets for a 200 MW AI campus",
        "intent_class": "market_ranking",
        "planner_version": "5.11",
        "steps": 4,
        "ms": 2351,
        "lead_tool": "ai_capacity_index",
        "confidence": 0.56,
        "rationale": "Route intent â class \"market_ranking\", lead with ai_capacity_index",
        "executed": [
            {
                "tool": "ai_capacity_index",
                "ms": 472,
                "status": "executed"
            },
            {
                "tool": "get_market_dcpi_rank",
                "ms": 678,
                "status": "executed"
            },
            {
                "tool": "get_market_dcpi_rank",
                "ms": 833,
                "status": "executed"
            },
            {
                "tool": "get_grid_intelligence",
                "ms": 989,
                "status": "executed"
            }
        ],
        "rejected": [
            {
                "tool": "rank_markets",
                "reason": "ai_capacity_index leads because it answers the deployment-horizon question directly (where N MW can land in 30/60/90 days); rank_markets criteria=ai_ready is the broader buildability sweep behind it. Both are AI-aware â this is a depth choice, not a rejection. (rank_markets' OTHER criteria rank installed build-out, which surfaces saturated AVOID markets.)"
            },
            {
                "tool": "get_dchub_recommendation",
                "reason": "One-call synthesis hides the per-factor evidence trail; a plan the agent executes itself keeps every number citable."
            },
            {
                "tool": "get_market_intel",
                "reason": "No single named market was detected in the intent â a one-market report needs a market to point at."
            },
            {
                "tool": "predict_market_trajectory",
                "reason": "The intent asked for present-state ranking, not a forward trajectory."
            },
            {
                "tool": "search_facilities",
                "reason": "Scored 1 vs 3.5 â the deterministic margin favored \"market_ranking\"."
            }
        ],
        "decisions_total": 5,
        "next_recipe": {
            "prompt": "grid_and_queue",
            "why": "Verify the winning market's ISO can actually deliver the power: headroom + interconnection queue."
        },
        "anon_rejected_shown": 1
    },
    {
        "intent": "how much power is available in ERCOT for a 100 MW data center",
        "intent_class": "grid_headroom",
        "planner_version": "5.11",
        "steps": 3,
        "ms": 11050,
        "lead_tool": "get_grid_intelligence",
        "confidence": 0.95,
        "rationale": "Route intent â class \"grid_headroom\", lead with get_grid_intelligence",
        "executed": [
            {
                "tool": "get_grid_intelligence",
                "ms": 1247,
                "status": "executed"
            },
            {
                "tool": "get_interconnection_queue",
                "ms": 829,
                "status": "executed"
            },
            {
                "tool": "get_refined_queue",
                "ms": 11029,
                "status": "executed"
            }
        ],
        "rejected": [
            {
                "tool": "compare_isos",
                "reason": "The intent named at most one ISO â a side-by-side needs 2+ named grids."
            },
            {
                "tool": "get_grid_data",
                "reason": "Raw telemetry alone answers less than the intent asked â headroom and queue context need the intelligence reads."
            },
            {
                "tool": "get_retirement_headroom",
                "reason": "The intent did not mention retirements â the general headroom read covers the broader question."
            },
            {
                "tool": "grid_transition_radar",
                "reason": "The intent asked about present headroom, not emerging-grid trajectory."
            }
        ],
        "decisions_total": 6,
        "next_recipe": {
            "prompt": "market_selection",
            "why": "Turn the ISO headroom picture into a ranked market shortlist with DCPI verdicts."
        },
        "anon_rejected_shown": 1
    },
    {
        "intent": "compare Dallas vs Phoenix for a GPU training cluster",
        "intent_class": "market_comparison",
        "planner_version": "5.11",
        "steps": 3,
        "ms": 1899,
        "lead_tool": "get_market_dcpi_rank",
        "confidence": 0.71,
        "rationale": "Route intent â class \"market_comparison\", lead with get_market_dcpi_rank",
        "executed": [
            {
                "tool": "get_market_dcpi_rank",
                "ms": 733,
                "status": "executed"
            },
            {
                "tool": "get_market_dcpi_rank",
                "ms": 873,
                "status": "executed"
            },
            {
                "tool": "get_market_intel",
                "ms": 1889,
                "status": "executed"
            }
        ],
        "rejected": [
            {
                "tool": "compare_isos",
                "reason": "The intent named markets/metros, not ISOs â DCPI per market is the market-level comparison."
            },
            {
                "tool": "compare_sites",
                "reason": "No coordinates were supplied â this is a market-level, not a site-level, comparison."
            },
            {
                "tool": "rank_markets",
                "reason": "The intent named a specific head-to-head â a full ranking answers a broader question than asked."
            }
        ],
        "decisions_total": 6,
        "next_recipe": {
            "prompt": "site_analysis",
            "why": "Drill into the winning market with a full multi-factor site read (score, hazards, water)."
        },
        "anon_rejected_shown": 1
    },
    {
        "intent": "tax incentives for data centers in Georgia",
        "intent_class": "incentives_tax",
        "planner_version": "5.11",
        "steps": 2,
        "ms": 900,
        "lead_tool": "get_tax_incentives",
        "confidence": 0.71,
        "rationale": "Route intent â class \"incentives_tax\", lead with get_tax_incentives",
        "executed": [
            {
                "tool": "get_tax_incentives",
                "ms": 647,
                "status": "executed"
            },
            {
                "tool": "get_energy_prices",
                "ms": 886,
                "status": "executed"
            }
        ],
        "rejected": [
            {
                "tool": "rank_markets",
                "reason": "A single state was named â the statutory read answers it directly; a national ranking answers a broader question than asked."
            },
            {
                "tool": "analyze_site",
                "reason": "No coordinates were supplied â this is a state-level statutory question, not a site read."
            },
            {
                "tool": "get_market_intel",
                "reason": "Incentive programs are enacted at the state level â the metro market report does not carry the statute detail."
            },
            {
                "tool": "search_facilities",
                "reason": "Scored 3 vs 6 â the deterministic margin favored \"incentives_tax\"."
            }
        ],
        "decisions_total": 5,
        "next_recipe": {
            "prompt": "whats_changed",
            "why": "See what moved in the dataset since this call â the return hook."
        },
        "anon_rejected_shown": 1
    },
    {
        "intent": "fiber routes and dark fiber availability near Atlanta",
        "intent_class": "fiber",
        "planner_version": "5.11",
        "steps": 3,
        "ms": 5446,
        "lead_tool": "get_fiber_intel",
        "confidence": 0.8,
        "rationale": "Route intent â class \"fiber\", lead with get_fiber_intel",
        "executed": [
            {
                "tool": "get_fiber_intel",
                "ms": 5438,
                "status": "executed"
            },
            {
                "tool": "get_fiber_readiness",
                "ms": 0,
                "status": "skipped_unresolved"
            },
            {
                "tool": "plan_fiber_leadin",
                "ms": 0,
                "status": "skipped_unresolved"
            }
        ],
        "rejected": [
            {
                "tool": "get_metro_fiber",
                "reason": "The long-haul read covers the metro layer too â the dedicated metro map is a narrower view of the same data."
            },
            {
                "tool": "cluster_sites_by_latency",
                "reason": "The intent read as single-site connectivity, not multi-site latency clustering."
            },
            {
                "tool": "analyze_site",
                "reason": "Scored 1.5 vs 7.5 â the deterministic margin favored \"fiber\"."
            }
        ],
        "decisions_total": 6,
        "next_recipe": {
            "prompt": "whats_changed",
            "why": "See what moved in the dataset since this call â the return hook."
        },
        "anon_rejected_shown": 1
    },
    {
        "intent": "powered shell and pocket listings in Dallas",
        "intent_class": "capacity_search",
        "planner_version": "5.11",
        "steps": 3,
        "ms": 11467,
        "lead_tool": "get_retirement_headroom",
        "confidence": 0.47,
        "rationale": "Route intent â class \"capacity_search\", lead with get_retirement_headroom",
        "executed": [
            {
                "tool": "get_retirement_headroom",
                "ms": 1219,
                "status": "executed"
            },
            {
                "tool": "get_refined_queue",
                "ms": 11456,
                "status": "executed"
            },
            {
                "tool": "get_market_dcpi_rank",
                "ms": 741,
                "status": "executed"
            }
        ],
        "rejected": [
            {
                "tool": "get_hosting_capacity",
                "reason": "The intent implicated no LOAD-publishing utility, so the feeder read stayed out of the sequence rather than spending a step whose whole content would be \"not published\". Coverage is 18 utilities, NOT nationwide â call it anyway if you want that stated explicitly: it answers with the nearest covered markets instead of a silent zero. Where the utility publishes only \"gen\" (DER export headroom), the number is what the feeder can ACCEPT from solar/storage and can never be relayed as siteable load."
            },
            {
                "tool": "rank_markets",
                "reason": "The intent pointed at a specific capacity search, not an open ranking â the retirement + queue reads answer \"find N MW here\" directly."
            },
            {
                "tool": "analyze_site",
                "reason": "No coordinates or candidate_id were supplied â the search has to SURFACE sites before one can be scored."
            },
            {
                "tool": "get_interconnection_queue",
                "reason": "A capacity search wants filterable survivors at your MW floor (get_refined_queue), not the ISO total."
            }
        ],
        "decisions_total": 6,
        "next_recipe": {
            "prompt": "site_analysis",
            "why": "Analyze the minted candidate site end-to-end â pass its candidate_id for zero transcription drift."
        },
        "anon_rejected_shown": 1
    },
    {
        "intent": "fiber routes near Ashburn with dark fiber availability",
        "intent_class": "fiber",
        "planner_version": "5.11",
        "steps": 3,
        "ms": 5666,
        "lead_tool": "get_fiber_intel",
        "confidence": 0.8,
        "rationale": "Route intent â class \"fiber\", lead with get_fiber_intel",
        "executed": [
            {
                "tool": "get_fiber_intel",
                "ms": 5661,
                "status": "executed"
            },
            {
                "tool": "get_fiber_readiness",
                "ms": 0,
                "status": "skipped_unresolved"
            },
            {
                "tool": "plan_fiber_leadin",
                "ms": 0,
                "status": "skipped_unresolved"
            }
        ],
        "rejected": [
            {
                "tool": "get_metro_fiber",
                "reason": "The long-haul read covers the metro layer too â the dedicated metro map is a narrower view of the same data."
            },
            {
                "tool": "cluster_sites_by_latency",
                "reason": "The intent read as single-site connectivity, not multi-site latency clustering."
            },
            {
                "tool": "analyze_site",
                "reason": "Scored 1.5 vs 7.5 â the deterministic margin favored \"fiber\"."
            }
        ],
        "decisions_total": 6,
        "next_recipe": {
            "prompt": "whats_changed",
            "why": "See what moved in the dataset since this call â the return hook."
        },
        "anon_rejected_shown": 1
    }
]
# ── BAKED-REPLAYS END ──


def _fmt_ms(ms):
    try:
        return f"{int(ms):,} ms"
    except Exception:
        return "\u2014"


def _strongest(rejected):
    """The most citable rejection: the longest reason that explains a CHOICE
    rather than a preconditionibility miss. A 'needs 2+ named grids' line is
    true but mechanical; a 'depth choice, not a rejection' line is the artifact
    nobody else publishes."""
    if not rejected:
        return None, []
    ranked = sorted(rejected, key=lambda r: len(r.get("reason") or ""), reverse=True)
    return ranked[0], ranked[1:]


def _render_one(r: dict) -> str:
    ex = r.get("executed") or []
    # Honest split: only steps that actually EXECUTED render as the wave; a
    # step the planner recorded but could not resolve renders as "Deferred"
    # with the reason. Rendering all planned steps as one wave would imply
    # every step ran — a fabricated capability claim on a citability page.
    ran = [s for s in ex if (s.get("status") or "executed") == "executed"]
    deferred = [s for s in ex if (s.get("status") or "executed") != "executed"]
    tools = " + ".join(_esc(str(s.get("tool"))) for s in ran)
    label = "Wave 1 (parallel)" if len(ran) > 1 else "Wave 1"
    total = sum(int(s.get("ms") or 0) for s in ran)
    waves = f"<p>{label}: {tools} &middot; {_fmt_ms(total)}</p>" if ran else "<p>No step executed.</p>"
    if deferred:
        dtxt = ", ".join(f'<code>{_esc(str(s.get("tool")))}</code>' for s in deferred)
        waves += ('<p style="color:#64748b"><small>Deferred, recorded in-replay: '
                  f'{dtxt} &mdash; a required input never resolved from this intent; '
                  'the planner records the gap instead of guessing.</small></p>')

    top, rest = _strongest(r.get("rejected") or [])
    rej_html = ""
    if top:
        rej_html += (f'<h3>Why not {_esc(str(top["tool"]))}?</h3>'
                     f'<blockquote style="margin:0 0 12px;padding:10px 14px;'
                     f'border-left:3px solid #94a3b8;color:#334155">'
                     f'{_esc(str(top["reason"]))}</blockquote>')
    if rest:
        items = "".join(f'<li><code>{_esc(str(x["tool"]))}</code> &mdash; {_esc(str(x["reason"]))}</li>'
                        for x in rest)
        rej_html += ('<h3 style="font-size:1.05rem;font-weight:600;margin:18px 0 8px">'
                     'Other paths considered and declined</h3>'
                     f'<ul style="margin:0 0 12px;padding-left:20px;line-height:1.8">{items}</ul>')

    nr = r.get("next_recipe") or {}
    nr_html = (f'<h3 style="font-size:1.05rem;font-weight:600;margin:18px 0 8px">Next</h3>'
               f'<p><code>/dchub:{_esc(str(nr["prompt"]))}</code> &mdash; '
               f'{_esc(str(nr.get("why") or ""))}</p>') if nr.get("prompt") else ""

    conf = r.get("confidence")
    conf_s = f" (confidence {conf})" if isinstance(conf, (int, float)) else ""
    n_rej = len(r.get("rejected") or [])
    anon = r.get("anon_rejected_shown", 1)
    steps_s = (f"{len(ran)} of {r.get('steps')} steps executed" if deferred
               else f"{r.get('steps')} steps")

    return f"""<div class="pane">
  <h2>Live replay: {_esc(str(r["intent"]))} <span style="color:#64748b">[keyed]</span></h2>
  <p>Intent &rarr; {_esc(str(r.get("intent_class")))} &middot; {_esc(steps_s)} &middot;
  {n_rej} paths rejected &middot; {_esc(str(r.get("decisions_total")))} decisions &middot;
  {_fmt_ms(r.get("ms"))} &middot; planner {_esc(str(r.get("planner_version")))}</p>
  <p style="color:#64748b;margin:0 0 12px"><small>Keyed capture &mdash; shows the full routing trail.
  An anonymous caller sees {anon} of {n_rej} rejections and fewer executed steps.</small></p>
  <h3 style="font-size:1.05rem;font-weight:600;margin:18px 0 8px">Decision</h3>
  <p>Lead: <code>{_esc(str(r.get("lead_tool")))}</code>{conf_s} &mdash; {_esc(str(r.get("rationale") or ""))}</p>
  {rej_html}
  <h3 style="font-size:1.05rem;font-weight:600;margin:18px 0 8px">Execution</h3>
  {waves}
  {nr_html}
  <p style="margin:10px 0 0"><small style="color:#64748b">Reproduce verbatim:
  <code>execute_plan(intent="{_esc(str(r["intent"]))}")</code></small></p>
</div>"""


def render_meta_replays(replays=None, retrieved_at=None) -> str:
    rs = replays or _BAKED
    at = retrieved_at or _RETRIEVED_AT
    if not rs:
        return ""
    total_rej = sum(len(r.get("rejected") or []) for r in rs)
    inner = "\n\n".join(_render_one(r) for r in rs)
    return f"""<div class="pane">
  <h2>Rendered replays &mdash; cite the reasoning, not just the tool name</h2>
  <p style="color:#64748b;margin:0">{len(rs)} real <code>execute_plan</code> runs, captured
  {_esc(str(at))} with a key so the full routing trail is visible &mdash; {total_rej} rejected paths
  across them, each with the reason recorded. The rejected-path rationale is the part no
  competitor publishes: it is the decision <i>not</i> taken, and why.</p>
</div>

{inner}"""
