"""Phase FF+25-followup-r7 (2026-05-20) — monthly trend outreach.
==========================================================================

The flow:
  · 1st of every month at 00:05 UTC, GitHub cron POSTs:
      /api/v1/reports/monthly/archive      (snapshot prior month)
      /api/v1/reports/monthly/send-outreach (email it to journalists)
  · This module owns the send + the log.
  · Brain detector check_monthly_trend_unsent_3d (in brain_consistency_
    radar.py) reads our monthly_outreach_log table to determine whether
    the prior-month snapshot has been emailed yet. If 3+ days into the
    new month with no send recorded, autopilot fires the send endpoint
    itself — backstop in case the GitHub cron failed.

Endpoints:
  POST /api/v1/reports/monthly/send-outreach    (admin) fire the campaign
  GET  /api/v1/reports/monthly/outreach-status   (admin) "has X been sent"

Reuses the existing _JOURNALISTS list and _compose_pitch / Resend-based
send machinery from routes/media_outreach.py. Composes a monthly-trend-
specific story dict so the pitch body links to /reports/monthly/<Y>-<M>
+ embeds the press-kit quotes generated by routes/monthly_trend.py.
"""
import os
import json
import logging
import datetime
from flask import Blueprint, jsonify, request

logger = logging.getLogger(__name__)
monthly_outreach_bp = Blueprint("monthly_outreach", __name__)


# ── Auth ─────────────────────────────────────────────────────────────
_INTERNAL_KEYS = {"dchub-internal-sync-2026"}
for _n in ("DCHUB_INTERNAL_KEY", "INTERNAL_KEY", "DCHUB_ADMIN_KEY"):
    _v = os.environ.get(_n)
    if _v:
        _INTERNAL_KEYS.add(_v)


def _admin_ok():
    sent = (request.headers.get("X-Internal-Key")
            or request.headers.get("X-Admin-Key")
            or request.args.get("admin_key") or "").strip()
    return sent in _INTERNAL_KEYS


# ── DB ───────────────────────────────────────────────────────────────
def _get_db():
    try:
        from main import get_db
        return get_db()
    except Exception:
        return None


def _ensure_log_table():
    """Track which (year, month) outreach campaigns have been sent
    and to how many recipients. Detector reads this to know whether
    the prior-month snapshot has been distributed.
    FIX r10: explicit c.commit() after DDL — get_db() returns non-
    autocommit connections so the CREATE TABLE was rolling back."""
    c = _get_db()
    if c is None: return False
    try:
        with c.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS monthly_outreach_log (
                    year         INT NOT NULL,
                    month        INT NOT NULL,
                    sent_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    recipients   INT NOT NULL DEFAULT 0,
                    succeeded    INT NOT NULL DEFAULT 0,
                    failed       INT NOT NULL DEFAULT 0,
                    permalink    TEXT,
                    triggered_by TEXT,
                    notes        TEXT,
                    PRIMARY KEY (year, month)
                )
            """)
        try: c.commit()
        except Exception: pass
        return True
    except Exception as e:
        logger.warning(f"[monthly-outreach] table create failed: {e}")
        try: c.rollback()
        except Exception: pass
        return False
    finally:
        try: c.close()
        except Exception: pass


def _prior_month(today: datetime.date) -> tuple[int, int]:
    if today.month == 1:
        return today.year - 1, 12
    return today.year, today.month - 1


# ── Story compose ───────────────────────────────────────────────────
def _build_story(year: int, month: int, snapshot: dict) -> dict:
    """Compose the story dict media_outreach._compose_pitch consumes.
    Pulls headline + top-deal + AI-traffic from the snapshot so each
    sentence is grounded in real data (no inventing)."""
    label = datetime.date(year, month, 1).strftime("%B %Y")
    permalink = f"https://dchub.cloud/reports/monthly/{year}-{month:02d}"
    h     = snapshot.get("headline")     or {}
    df    = snapshot.get("deal_flow")    or {}
    curr  = df.get("current")            or {}
    ai    = snapshot.get("ai_traffic")   or {}
    top_d = (snapshot.get("top_deals")   or [])

    # Story paragraph — the one section the recipient reads first
    paragraph_parts = [
        f"Our {label} monthly trend snapshot just dropped at {permalink}."
    ]
    if h.get("facilities_total") and h.get("total_mw"):
        paragraph_parts.append(
            f"Live data: {h['facilities_total']:,} facilities, "
            f"{h['total_mw']/1000:,.1f} GW tracked."
        )
    if curr.get("count") and (curr.get("value") or 0) > 0:
        paragraph_parts.append(
            f"{curr['count']} M&A transactions worth "
            f"${curr['value']/1e3:.1f}B in the month."  # value is in $millions
        )
    if ai.get("tool_calls_month") and ai.get("mom_pct") is not None:
        d = "up" if ai["mom_pct"] >= 0 else "down"
        paragraph_parts.append(
            f"AI-agent queries against our research API "
            f"{d} {abs(ai['mom_pct']):.1f}% MoM."
        )
    story_paragraph = " ".join(paragraph_parts)

    # Three angles — pulled from real data, dropped if missing
    angles = []
    if h.get("facilities_mom_pct") is not None:
        d = "up" if h["facilities_mom_pct"] >= 0 else "down"
        angles.append(
            f"Facility discovery {d} {abs(h['facilities_mom_pct']):.1f}% MoM — "
            f"the inflection JLL/CBRE quarterly reports will catch in 60 days"
        )
    if top_d and top_d[0].get("buyer") and (top_d[0].get("value") or 0) > 0:
        td = top_d[0]
        angles.append(
            f"Biggest deal: {td['buyer']} → {td.get('seller','?')} at "
            f"${td['value']/1e3:.1f}B ({(td.get('mw') or 0):,.0f} MW)"  # value is in $millions
        )
    if df.get("deals_mom_pct") is not None:
        d = "up" if df["deals_mom_pct"] >= 0 else "down"
        angles.append(
            f"Deal count {d} {abs(df['deals_mom_pct']):.1f}% MoM — "
            f"capital is {('moving faster' if df['deals_mom_pct']>0 else 'pulling back')} "
            f"than last month suggested"
        )
    while len(angles) < 3:
        angles.append(
            f"Full {label} report with MoM + YoY deltas at {permalink}"
        )

    return {
        "headline":         f"DC Hub {label} monthly trend",
        "story_paragraph":  story_paragraph,
        "data_url":         permalink,
        "methodology_url":  "https://dchub.cloud/dcpi/methodology",
        "angle_1": angles[0],
        "angle_2": angles[1],
        "angle_3": angles[2],
    }


# ── POST /api/v1/reports/monthly/send-outreach ───────────────────────
@monthly_outreach_bp.route("/api/v1/reports/monthly/send-outreach",
                            methods=["POST", "GET"])
def send_outreach():
    """Fire the monthly trend outreach campaign.

    Query params:
      ?year=2026&month=5  — which month's snapshot to pitch (default: prior month)
      ?dry_run=1          — compose pitches + log intent, no actual sends
      ?triggered_by=cron  — accountability label (cron / autopilot / manual)
    """
    if not _admin_ok():
        return jsonify(ok=False, error="forbidden"), 403
    _ensure_log_table()

    today = datetime.date.today()
    try:
        year  = int(request.args.get("year")  or _prior_month(today)[0])
        month = int(request.args.get("month") or _prior_month(today)[1])
    except ValueError:
        return jsonify(ok=False, error="invalid_year_or_month"), 400
    if month < 1 or month > 12:
        return jsonify(ok=False, error="invalid_month"), 400

    dry_run = request.args.get("dry_run") in ("1", "true", "yes")
    triggered_by = (request.args.get("triggered_by") or "manual")[:30]

    # Pull the snapshot data for story composition.
    try:
        from routes.monthly_trend import _compute_report
        snapshot = _compute_report(year, month)
    except Exception as e:
        return jsonify(ok=False, error=f"snapshot_failed: {str(e)[:120]}"), 500

    story = _build_story(year, month, snapshot)

    # Reuse the journalist list + Resend send machinery from media_outreach.
    try:
        from routes.media_outreach import (_JOURNALISTS, _compose_pitch,
                                             _conn as _mo_conn,
                                             _ensure_schema as _mo_ensure)
    except Exception as e:
        return jsonify(ok=False, error=f"media_outreach unavailable: {e}"), 503

    _RESEND_KEY = (os.environ.get("DCHUB_RESEND_API_KEY") or "").strip()
    if not dry_run and not _RESEND_KEY:
        return jsonify(
            ok=False,
            error="DCHUB_RESEND_API_KEY not set",
            hint="Set DCHUB_RESEND_API_KEY in Railway env vars, or "
                 "pass ?dry_run=1 to compose-only.",
        ), 503

    _mo_ensure()

    results = []
    succeeded = 0
    failed    = 0

    for recipient in _JOURNALISTS:
        subject, body = _compose_pitch("monthly_trend", story, recipient)
        if dry_run:
            results.append({
                "to": recipient["email"],
                "publication": recipient.get("publication"),
                "subject": subject,
                "would_send": True,
            })
            succeeded += 1
            continue

        # Skip if same recipient was emailed in the last 7 days (cooldown
        # convention from media_outreach.pitch_send).
        try:
            cc = _mo_conn()
            cur = cc.cursor()
            cur.execute(
                "SELECT MAX(sent_at) FROM media_outreach_log "
                "WHERE recipient_email = %s "
                "  AND sent_at > NOW() - INTERVAL '7 days'",
                (recipient["email"],),
            )
            r = cur.fetchone()
            if r and r[0]:
                results.append({"to": recipient["email"],
                                "skipped": "cooldown_7d",
                                "last_sent": str(r[0])[:19]})
                cc.close()
                continue
            cc.close()
        except Exception:
            try: cc.close()
            except Exception: pass

        # Send via Resend
        try:
            import urllib.request, urllib.error
            payload = json.dumps({
                "from":    "DC Hub <press@dchub.cloud>",
                "to":      [recipient["email"]],
                "subject": subject,
                "text":    body,
                "reply_to": "jonathan@dchub.cloud",
            }).encode()
            req = urllib.request.Request(
                "https://api.resend.com/emails", data=payload,
                method="POST",
                headers={"Authorization": f"Bearer {_RESEND_KEY}",
                          "Content-Type": "application/json"},
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                resp_body = resp.read().decode("utf-8", errors="replace")
                rd = json.loads(resp_body) if resp_body else {}
                resend_id = rd.get("id")
            # Log into media_outreach_log
            try:
                cc = _mo_conn()
                cur = cc.cursor()
                cur.execute(
                    "INSERT INTO media_outreach_log "
                    "(recipient_email, recipient_name, publication, "
                    " subject, body, pitch_topic, resend_id) "
                    "VALUES (%s,%s,%s,%s,%s,%s,%s)",
                    (recipient["email"], recipient.get("name"),
                     recipient.get("publication"), subject, body,
                     f"monthly_trend_{year}_{month:02d}", resend_id),
                )
                try: cc.commit()
                except Exception: pass
                cc.close()
            except Exception:
                try: cc.close()
                except Exception: pass
            succeeded += 1
            results.append({"to": recipient["email"], "resend_id": resend_id})
        except Exception as e:
            failed += 1
            results.append({"to": recipient["email"], "error": str(e)[:200]})

    # Record the campaign run
    permalink = f"https://dchub.cloud/reports/monthly/{year}-{month:02d}"
    c = _get_db()
    if c is not None:
        try:
            with c.cursor() as cur:
                cur.execute("""
                    INSERT INTO monthly_outreach_log
                      (year, month, recipients, succeeded, failed,
                       permalink, triggered_by, sent_at)
                    VALUES (%s,%s,%s,%s,%s,%s,%s,NOW())
                    ON CONFLICT (year, month) DO UPDATE SET
                      recipients   = monthly_outreach_log.recipients + EXCLUDED.recipients,
                      succeeded    = monthly_outreach_log.succeeded  + EXCLUDED.succeeded,
                      failed       = monthly_outreach_log.failed     + EXCLUDED.failed,
                      sent_at      = NOW(),
                      triggered_by = EXCLUDED.triggered_by
                """, (year, month, len(_JOURNALISTS), succeeded, failed,
                       permalink, triggered_by))
        except Exception as e:
            logger.warning(f"[monthly-outreach] log insert failed: {e}")
        finally:
            try: c.close()
            except Exception: pass

    return jsonify(
        ok=True,
        year=year, month=month,
        month_label=snapshot.get("month_label"),
        permalink=permalink,
        triggered_by=triggered_by,
        dry_run=dry_run,
        attempted=len(_JOURNALISTS),
        succeeded=succeeded,
        failed=failed,
        results=results[:30],   # truncate so the response stays sane
    )


# ── GET /api/v1/reports/monthly/outreach-status ──────────────────────
@monthly_outreach_bp.route("/api/v1/reports/monthly/outreach-status",
                            methods=["GET"])
def outreach_status():
    """Has a given (year, month) outreach been sent? Used by the brain
    detector to decide whether to fire the backstop."""
    if not _admin_ok():
        return jsonify(ok=False, error="forbidden"), 403
    _ensure_log_table()

    today = datetime.date.today()
    try:
        year  = int(request.args.get("year")  or _prior_month(today)[0])
        month = int(request.args.get("month") or _prior_month(today)[1])
    except ValueError:
        return jsonify(ok=False, error="invalid_year_or_month"), 400

    c = _get_db()
    if c is None:
        return jsonify(ok=False, error="no_db"), 503
    try:
        with c.cursor() as cur:
            cur.execute("""
                SELECT recipients, succeeded, failed, sent_at,
                       triggered_by, permalink
                  FROM monthly_outreach_log
                 WHERE year = %s AND month = %s
            """, (year, month))
            r = cur.fetchone()
            if not r:
                return jsonify(
                    ok=True, year=year, month=month,
                    sent=False,
                    days_since_month_close=(today - datetime.date(
                        year, month, 1).replace(day=28)).days,
                )
            return jsonify(
                ok=True, year=year, month=month,
                sent=True,
                recipients=int(r[0] or 0),
                succeeded=int(r[1] or 0),
                failed=int(r[2] or 0),
                sent_at=str(r[3]) if r[3] else None,
                triggered_by=r[4],
                permalink=r[5],
            )
    except Exception as e:
        return jsonify(ok=False, error=str(e)[:200]), 500
    finally:
        try: c.close()
        except Exception: pass


def _smoke():
    logger.info("[monthly-outreach] ready · POST /send-outreach "
                 "+ GET /outreach-status")

_smoke()
