import sqlite3, uuid, json, requests, time, re
from datetime import datetime

EXPANDED_FACILITIES = [
    {"name": "Telia Helsinki Data Center", "provider": "Telia", "city": "Helsinki", "country": "FI", "latitude": 60.1699, "longitude": 24.9384},
    {"name": "Telia Stockholm Data Center", "provider": "Telia", "city": "Stockholm", "country": "SE", "latitude": 59.3293, "longitude": 18.0686},
    {"name": "Telia Oslo Data Center", "provider": "Telia", "city": "Oslo", "country": "NO", "latitude": 59.9139, "longitude": 10.7522},
    {"name": "Telia Espoo Data Center", "provider": "Telia", "city": "Espoo", "country": "FI", "latitude": 60.2055, "longitude": 24.6559},
    {"name": "DigiPlex Oslo DC", "provider": "DigiPlex", "city": "Oslo", "country": "NO", "latitude": 59.9139, "longitude": 10.7522},
    {"name": "DigiPlex Fetsund DC", "provider": "DigiPlex", "city": "Fetsund", "country": "NO", "latitude": 59.9271, "longitude": 11.1528},
    {"name": "DigiPlex Stockholm DC", "provider": "DigiPlex", "city": "Stockholm", "country": "SE", "latitude": 59.3293, "longitude": 18.0686},
    {"name": "DigiPlex Roost DC", "provider": "DigiPlex", "city": "Roost", "country": "NO", "latitude": 64.1247, "longitude": 13.0861},
    {"name": "Green Mountain DC1-Stavanger", "provider": "Green Mountain", "city": "Rennesøy", "country": "NO", "latitude": 59.1300, "longitude": 5.7600},
    {"name": "Green Mountain DC2-Telemark", "provider": "Green Mountain", "city": "Rjukan", "country": "NO", "latitude": 59.8789, "longitude": 8.5900},
    {"name": "Green Mountain DC3-Oslo", "provider": "Green Mountain", "city": "Enebakk", "country": "NO", "latitude": 59.7500, "longitude": 11.1500},
    {"name": "Green Mountain DC4-Kalberg", "provider": "Green Mountain", "city": "Kalberg", "country": "NO", "latitude": 58.9600, "longitude": 5.7300},
    {"name": "Bulk Infrastructure N01 Oslo", "provider": "Bulk Infrastructure", "city": "Oslo", "country": "NO", "latitude": 59.9139, "longitude": 10.7522},
    {"name": "Bulk Infrastructure DK01 Esbjerg", "provider": "Bulk Infrastructure", "city": "Esbjerg", "country": "DK", "latitude": 55.4700, "longitude": 8.4517},
    {"name": "Conapto Stockholm North", "provider": "Conapto", "city": "Stockholm", "country": "SE", "latitude": 59.4050, "longitude": 18.0000},
    {"name": "Conapto Stockholm South", "provider": "Conapto", "city": "Stockholm", "country": "SE", "latitude": 59.2800, "longitude": 18.0700},
    {"name": "Bahnhof Pionen Stockholm", "provider": "Bahnhof", "city": "Stockholm", "country": "SE", "latitude": 59.3293, "longitude": 18.0686},
    {"name": "Bahnhof Thule Stockholm", "provider": "Bahnhof", "city": "Stockholm", "country": "SE", "latitude": 59.3400, "longitude": 18.0500},
    {"name": "atNorth ICE01 Reykjavik", "provider": "atNorth", "city": "Reykjavik", "country": "IS", "latitude": 64.1466, "longitude": -21.9426},
    {"name": "atNorth ICE02 Akureyri", "provider": "atNorth", "city": "Akureyri", "country": "IS", "latitude": 65.6835, "longitude": -18.0878},
    {"name": "atNorth SWE01 Stockholm", "provider": "atNorth", "city": "Stockholm", "country": "SE", "latitude": 59.3293, "longitude": 18.0686},
    {"name": "atNorth DEN01 Copenhagen", "provider": "atNorth", "city": "Copenhagen", "country": "DK", "latitude": 55.6761, "longitude": 12.5683},
    {"name": "atNorth FIN01 Helsinki", "provider": "atNorth", "city": "Helsinki", "country": "FI", "latitude": 60.1699, "longitude": 24.9384},
    {"name": "Verne Global Keflavik", "provider": "Verne Global", "city": "Keflavik", "country": "IS", "latitude": 63.9850, "longitude": -22.6050},
    {"name": "Etix Everywhere Luxembourg", "provider": "Etix Everywhere", "city": "Luxembourg", "country": "LU", "latitude": 49.6116, "longitude": 6.1319},
    {"name": "Etix Everywhere Marseille", "provider": "Etix Everywhere", "city": "Marseille", "country": "FR", "latitude": 43.2965, "longitude": 5.3698},
    {"name": "Etix Everywhere Johannesburg", "provider": "Etix Everywhere", "city": "Johannesburg", "country": "ZA", "latitude": -26.2041, "longitude": 28.0473},
    {"name": "LuxConnect DC1 Bettembourg", "provider": "LuxConnect", "city": "Bettembourg", "country": "LU", "latitude": 49.5166, "longitude": 6.1050},
    {"name": "LuxConnect DC2 Bissen", "provider": "LuxConnect", "city": "Bissen", "country": "LU", "latitude": 49.7870, "longitude": 6.0600},
    {"name": "DEAC Riga DC", "provider": "DEAC", "city": "Riga", "country": "LV", "latitude": 56.9496, "longitude": 24.1052},
    {"name": "DEAC Vilnius DC", "provider": "DEAC", "city": "Vilnius", "country": "LT", "latitude": 54.6872, "longitude": 25.2797},
    {"name": "DEAC Moscow DC", "provider": "DEAC", "city": "Moscow", "country": "RU", "latitude": 55.7558, "longitude": 37.6173},
    {"name": "DEAC Tallinn DC", "provider": "DEAC", "city": "Tallinn", "country": "EE", "latitude": 59.4370, "longitude": 24.7536},
    {"name": "Telehouse Frankfurt", "provider": "KDDI Telehouse", "city": "Frankfurt", "country": "DE", "latitude": 50.1109, "longitude": 8.6821},
    {"name": "Telehouse Paris Voltaire", "provider": "KDDI Telehouse", "city": "Paris", "country": "FR", "latitude": 48.8566, "longitude": 2.3522},
    {"name": "Telehouse Paris Magny", "provider": "KDDI Telehouse", "city": "Magny-les-Hameaux", "country": "FR", "latitude": 48.7308, "longitude": 2.0694},
    {"name": "Telehouse New York Chelsea", "provider": "KDDI Telehouse", "city": "New York", "state": "NY", "country": "US", "latitude": 40.7282, "longitude": -74.0010},
    {"name": "Telehouse Hong Kong CCC", "provider": "KDDI Telehouse", "city": "Hong Kong", "country": "HK", "latitude": 22.3193, "longitude": 114.1694},
    {"name": "Telehouse Beijing", "provider": "KDDI Telehouse", "city": "Beijing", "country": "CN", "latitude": 39.9042, "longitude": 116.4074},
    {"name": "Telehouse Shanghai", "provider": "KDDI Telehouse", "city": "Shanghai", "country": "CN", "latitude": 31.2304, "longitude": 121.4737},
    {"name": "Telehouse Singapore", "provider": "KDDI Telehouse", "city": "Singapore", "country": "SG", "latitude": 1.3521, "longitude": 103.8198},
    {"name": "Telehouse Vietnam Hanoi", "provider": "KDDI Telehouse", "city": "Hanoi", "country": "VN", "latitude": 21.0278, "longitude": 105.8342},
    {"name": "Telehouse Vietnam HCMC", "provider": "KDDI Telehouse", "city": "Ho Chi Minh City", "country": "VN", "latitude": 10.8231, "longitude": 106.6297},
    {"name": "TRUE IDC Bangkok", "provider": "TRUE IDC", "city": "Bangkok", "country": "TH", "latitude": 13.7563, "longitude": 100.5018},
    {"name": "TRUE IDC Bangkok 2", "provider": "TRUE IDC", "city": "Bangkok", "country": "TH", "latitude": 13.7560, "longitude": 100.5015},
    {"name": "TRUE IDC Rama 9", "provider": "TRUE IDC", "city": "Bangkok", "country": "TH", "latitude": 13.7575, "longitude": 100.5652},
    {"name": "CAT Telecom Bangkok DC", "provider": "CAT Telecom", "city": "Bangkok", "country": "TH", "latitude": 13.7610, "longitude": 100.5385},
    {"name": "VNPT Data Center Hanoi", "provider": "VNPT", "city": "Hanoi", "country": "VN", "latitude": 21.0278, "longitude": 105.8342},
    {"name": "VNPT Data Center HCMC", "provider": "VNPT", "city": "Ho Chi Minh City", "country": "VN", "latitude": 10.8231, "longitude": 106.6297},
    {"name": "FPT Data Center Hanoi", "provider": "FPT Telecom", "city": "Hanoi", "country": "VN", "latitude": 21.0140, "longitude": 105.8039},
    {"name": "FPT Data Center HCMC", "provider": "FPT Telecom", "city": "Ho Chi Minh City", "country": "VN", "latitude": 10.8420, "longitude": 106.6690},
    {"name": "Viettel IDC Hanoi", "provider": "Viettel", "city": "Hanoi", "country": "VN", "latitude": 21.0050, "longitude": 105.8070},
    {"name": "Viettel IDC Ho Chi Minh City", "provider": "Viettel", "city": "Ho Chi Minh City", "country": "VN", "latitude": 10.8300, "longitude": 106.6600},
    {"name": "PLDT Vitro Makati", "provider": "PLDT", "city": "Makati", "country": "PH", "latitude": 14.5547, "longitude": 121.0244},
    {"name": "PLDT Vitro Clark", "provider": "PLDT", "city": "Clark", "country": "PH", "latitude": 15.1851, "longitude": 120.5587},
    {"name": "Globe Telecom DC Manila", "provider": "Globe Telecom", "city": "Manila", "country": "PH", "latitude": 14.5995, "longitude": 120.9842},
    {"name": "Beeinfotech Makati DC", "provider": "Beeinfotech", "city": "Makati", "country": "PH", "latitude": 14.5547, "longitude": 121.0244},
    {"name": "Converge ICT Manila DC", "provider": "Converge ICT", "city": "Quezon City", "country": "PH", "latitude": 14.6760, "longitude": 121.0437},
    {"name": "Telkom Indonesia Sentul DC", "provider": "Telkom Indonesia", "city": "Sentul", "country": "ID", "latitude": -6.5900, "longitude": 106.8700},
    {"name": "Telkom Indonesia Surabaya DC", "provider": "Telkom Indonesia", "city": "Surabaya", "country": "ID", "latitude": -7.2575, "longitude": 112.7521},
    {"name": "Biznet Technovillage Jakarta", "provider": "Biznet", "city": "Jakarta", "country": "ID", "latitude": -6.2880, "longitude": 106.7190},
    {"name": "NeutraDC Jakarta", "provider": "NeutraDC", "city": "Jakarta", "country": "ID", "latitude": -6.2200, "longitude": 106.8300},
    {"name": "NeutraDC Bekasi", "provider": "NeutraDC", "city": "Bekasi", "country": "ID", "latitude": -6.2349, "longitude": 106.9896},
    {"name": "PDG Jakarta DC1", "provider": "Princeton Digital Group", "city": "Jakarta", "country": "ID", "latitude": -6.2088, "longitude": 106.8456},
    {"name": "PDG Singapore DC1", "provider": "Princeton Digital Group", "city": "Singapore", "country": "SG", "latitude": 1.3521, "longitude": 103.8198},
    {"name": "PDG Beijing DC1", "provider": "Princeton Digital Group", "city": "Beijing", "country": "CN", "latitude": 39.9042, "longitude": 116.4074},
    {"name": "PDG Tokyo DC1", "provider": "Princeton Digital Group", "city": "Tokyo", "country": "JP", "latitude": 35.6762, "longitude": 139.6503},
    {"name": "PDG Mumbai DC1", "provider": "Princeton Digital Group", "city": "Mumbai", "state": "Maharashtra", "country": "IN", "latitude": 19.0760, "longitude": 72.8777},
    {"name": "SpaceDC Jakarta JKT1", "provider": "SpaceDC", "city": "Jakarta", "country": "ID", "latitude": -6.2088, "longitude": 106.8456},
    {"name": "SpaceDC Jakarta JKT2", "provider": "SpaceDC", "city": "Jakarta", "country": "ID", "latitude": -6.2086, "longitude": 106.8453},
    {"name": "SpaceDC Singapore SG1", "provider": "SpaceDC", "city": "Singapore", "country": "SG", "latitude": 1.3521, "longitude": 103.8198},
    {"name": "Chunghwa Telecom Taipei IDC", "provider": "Chunghwa Telecom", "city": "Taipei", "country": "TW", "latitude": 25.0330, "longitude": 121.5654},
    {"name": "Chunghwa Telecom Banqiao IDC", "provider": "Chunghwa Telecom", "city": "Banqiao", "country": "TW", "latitude": 25.0144, "longitude": 121.4670},
    {"name": "Chief Telecom Taipei IDC", "provider": "Chief Telecom", "city": "Taipei", "country": "TW", "latitude": 25.0375, "longitude": 121.5637},
    {"name": "Chief Telecom Taoyuan IDC", "provider": "Chief Telecom", "city": "Taoyuan", "country": "TW", "latitude": 24.9936, "longitude": 121.3010},
    {"name": "CITIC Telecom Sha Tin DC", "provider": "CITIC Telecom", "city": "Hong Kong", "country": "HK", "latitude": 22.3893, "longitude": 114.1950},
    {"name": "NTT Tokyo Mitaka DC", "provider": "NTT Communications", "city": "Tokyo", "country": "JP", "latitude": 35.6835, "longitude": 139.5595},
    {"name": "NTT Osaka Saito DC", "provider": "NTT Communications", "city": "Osaka", "country": "JP", "latitude": 34.8350, "longitude": 135.4860},
    {"name": "KDDI Tama DC", "provider": "KDDI", "city": "Tokyo", "country": "JP", "latitude": 35.6360, "longitude": 139.4440},
    {"name": "KDDI Osaka DC", "provider": "KDDI", "city": "Osaka", "country": "JP", "latitude": 34.6920, "longitude": 135.5020},
    {"name": "SoftBank Tokai DC", "provider": "SoftBank", "city": "Nagoya", "country": "JP", "latitude": 35.1815, "longitude": 136.9066},
    {"name": "SoftBank Osaka DC", "provider": "SoftBank", "city": "Osaka", "country": "JP", "latitude": 34.6937, "longitude": 135.5023},
    {"name": "IIJ Shiroi DC", "provider": "IIJ", "city": "Shiroi", "state": "Chiba", "country": "JP", "latitude": 35.7915, "longitude": 140.0564},
    {"name": "IIJ Matsue DC", "provider": "IIJ", "city": "Matsue", "state": "Shimane", "country": "JP", "latitude": 35.4723, "longitude": 133.0505},
    {"name": "SK Broadband Seoul DC", "provider": "SK Broadband", "city": "Seoul", "country": "KR", "latitude": 37.5665, "longitude": 126.9780},
    {"name": "SK Broadband Pangyo DC", "provider": "SK Broadband", "city": "Seongnam", "country": "KR", "latitude": 37.3940, "longitude": 127.1110},
    {"name": "LG CNS Busan DC", "provider": "LG CNS", "city": "Busan", "country": "KR", "latitude": 35.1796, "longitude": 129.0756},
    {"name": "LG CNS Sangam DC Seoul", "provider": "LG CNS", "city": "Seoul", "country": "KR", "latitude": 37.5770, "longitude": 126.8910},
    {"name": "Naver Cloud Chuncheon DC", "provider": "Naver", "city": "Chuncheon", "country": "KR", "latitude": 37.8813, "longitude": 127.7300},
    {"name": "Naver Cloud Sejong DC", "provider": "Naver", "city": "Sejong", "country": "KR", "latitude": 36.4800, "longitude": 127.0000},
    {"name": "Kakao Ansan DC", "provider": "Kakao", "city": "Ansan", "country": "KR", "latitude": 37.3219, "longitude": 126.8309},
    {"name": "Alibaba Cloud Zhangbei DC", "provider": "Alibaba Cloud", "city": "Zhangbei", "state": "Hebei", "country": "CN", "latitude": 41.1613, "longitude": 114.7162},
    {"name": "Alibaba Cloud Hangzhou DC", "provider": "Alibaba Cloud", "city": "Hangzhou", "state": "Zhejiang", "country": "CN", "latitude": 30.2741, "longitude": 120.1551},
    {"name": "Alibaba Cloud Shanghai DC", "provider": "Alibaba Cloud", "city": "Shanghai", "country": "CN", "latitude": 31.2304, "longitude": 121.4737},
    {"name": "Alibaba Cloud Shenzhen DC", "provider": "Alibaba Cloud", "city": "Shenzhen", "country": "CN", "latitude": 22.5431, "longitude": 114.0579},
    {"name": "Alibaba Cloud Qingdao DC", "provider": "Alibaba Cloud", "city": "Qingdao", "country": "CN", "latitude": 36.0671, "longitude": 120.3826},
    {"name": "Alibaba Cloud Ulanqab DC", "provider": "Alibaba Cloud", "city": "Ulanqab", "state": "Inner Mongolia", "country": "CN", "latitude": 40.9926, "longitude": 113.1140},
    {"name": "Alibaba Cloud Singapore DC", "provider": "Alibaba Cloud", "city": "Singapore", "country": "SG", "latitude": 1.3521, "longitude": 103.8198},
    {"name": "Alibaba Cloud Jakarta DC", "provider": "Alibaba Cloud", "city": "Jakarta", "country": "ID", "latitude": -6.2088, "longitude": 106.8456},
    {"name": "Alibaba Cloud Tokyo DC", "provider": "Alibaba Cloud", "city": "Tokyo", "country": "JP", "latitude": 35.6762, "longitude": 139.6503},
    {"name": "Alibaba Cloud Frankfurt DC", "provider": "Alibaba Cloud", "city": "Frankfurt", "country": "DE", "latitude": 50.1109, "longitude": 8.6821},
    {"name": "Alibaba Cloud London DC", "provider": "Alibaba Cloud", "city": "London", "country": "GB", "latitude": 51.5074, "longitude": -0.1278},
    {"name": "Alibaba Cloud Dubai DC", "provider": "Alibaba Cloud", "city": "Dubai", "country": "AE", "latitude": 25.2048, "longitude": 55.2708},
    {"name": "Alibaba Cloud Mumbai DC", "provider": "Alibaba Cloud", "city": "Mumbai", "state": "Maharashtra", "country": "IN", "latitude": 19.0760, "longitude": 72.8777},
    {"name": "Tencent Cloud Guangzhou DC", "provider": "Tencent Cloud", "city": "Guangzhou", "country": "CN", "latitude": 23.1291, "longitude": 113.2644},
    {"name": "Tencent Cloud Shanghai DC", "provider": "Tencent Cloud", "city": "Shanghai", "country": "CN", "latitude": 31.2304, "longitude": 121.4737},
    {"name": "Tencent Cloud Beijing DC", "provider": "Tencent Cloud", "city": "Beijing", "country": "CN", "latitude": 39.9042, "longitude": 116.4074},
    {"name": "Tencent Cloud Chengdu DC", "provider": "Tencent Cloud", "city": "Chengdu", "country": "CN", "latitude": 30.5728, "longitude": 104.0668},
    {"name": "Tencent Cloud Chongqing DC", "provider": "Tencent Cloud", "city": "Chongqing", "country": "CN", "latitude": 29.4316, "longitude": 106.9123},
    {"name": "Tencent Cloud Nanjing DC", "provider": "Tencent Cloud", "city": "Nanjing", "country": "CN", "latitude": 32.0603, "longitude": 118.7969},
    {"name": "Tencent Cloud Hong Kong DC", "provider": "Tencent Cloud", "city": "Hong Kong", "country": "HK", "latitude": 22.3193, "longitude": 114.1694},
    {"name": "Tencent Cloud Singapore DC", "provider": "Tencent Cloud", "city": "Singapore", "country": "SG", "latitude": 1.3521, "longitude": 103.8198},
    {"name": "Tencent Cloud Tokyo DC", "provider": "Tencent Cloud", "city": "Tokyo", "country": "JP", "latitude": 35.6762, "longitude": 139.6503},
    {"name": "Tencent Cloud Seoul DC", "provider": "Tencent Cloud", "city": "Seoul", "country": "KR", "latitude": 37.5665, "longitude": 126.9780},
    {"name": "Tencent Cloud Frankfurt DC", "provider": "Tencent Cloud", "city": "Frankfurt", "country": "DE", "latitude": 50.1109, "longitude": 8.6821},
    {"name": "Tencent Cloud Silicon Valley DC", "provider": "Tencent Cloud", "city": "Santa Clara", "state": "CA", "country": "US", "latitude": 37.3541, "longitude": -121.9552},
    {"name": "Tencent Cloud Mumbai DC", "provider": "Tencent Cloud", "city": "Mumbai", "state": "Maharashtra", "country": "IN", "latitude": 19.0760, "longitude": 72.8777},
    {"name": "Tencent Cloud Bangkok DC", "provider": "Tencent Cloud", "city": "Bangkok", "country": "TH", "latitude": 13.7563, "longitude": 100.5018},
    {"name": "Tencent Cloud Sao Paulo DC", "provider": "Tencent Cloud", "city": "Sao Paulo", "state": "SP", "country": "BR", "latitude": -23.5505, "longitude": -46.6333},
    {"name": "Huawei Cloud Shanghai DC", "provider": "Huawei Cloud", "city": "Shanghai", "country": "CN", "latitude": 31.2304, "longitude": 121.4737},
    {"name": "Huawei Cloud Beijing DC", "provider": "Huawei Cloud", "city": "Beijing", "country": "CN", "latitude": 39.9042, "longitude": 116.4074},
    {"name": "Huawei Cloud Guangzhou DC", "provider": "Huawei Cloud", "city": "Guangzhou", "country": "CN", "latitude": 23.1291, "longitude": 113.2644},
    {"name": "Huawei Cloud Ulanqab DC", "provider": "Huawei Cloud", "city": "Ulanqab", "state": "Inner Mongolia", "country": "CN", "latitude": 40.9926, "longitude": 113.1140},
    {"name": "Huawei Cloud Singapore DC", "provider": "Huawei Cloud", "city": "Singapore", "country": "SG", "latitude": 1.3521, "longitude": 103.8198},
    {"name": "Huawei Cloud Bangkok DC", "provider": "Huawei Cloud", "city": "Bangkok", "country": "TH", "latitude": 13.7563, "longitude": 100.5018},
    {"name": "Huawei Cloud Jakarta DC", "provider": "Huawei Cloud", "city": "Jakarta", "country": "ID", "latitude": -6.2088, "longitude": 106.8456},
    {"name": "Huawei Cloud Johannesburg DC", "provider": "Huawei Cloud", "city": "Johannesburg", "country": "ZA", "latitude": -26.2041, "longitude": 28.0473},
    {"name": "Huawei Cloud Istanbul DC", "provider": "Huawei Cloud", "city": "Istanbul", "country": "TR", "latitude": 41.0082, "longitude": 28.9784},
    {"name": "Huawei Cloud Dublin DC", "provider": "Huawei Cloud", "city": "Dublin", "country": "IE", "latitude": 53.3498, "longitude": -6.2603},
    {"name": "Huawei Cloud Sao Paulo DC", "provider": "Huawei Cloud", "city": "Sao Paulo", "state": "SP", "country": "BR", "latitude": -23.5505, "longitude": -46.6333},
    {"name": "Huawei Cloud Mexico DC", "provider": "Huawei Cloud", "city": "Queretaro", "country": "MX", "latitude": 20.5888, "longitude": -100.3899},
    {"name": "Huawei Cloud Santiago DC", "provider": "Huawei Cloud", "city": "Santiago", "country": "CL", "latitude": -33.4489, "longitude": -70.6693},
    {"name": "Huawei Cloud Riyadh DC", "provider": "Huawei Cloud", "city": "Riyadh", "country": "SA", "latitude": 24.7136, "longitude": 46.6753},
    {"name": "Huawei Cloud Cairo DC", "provider": "Huawei Cloud", "city": "Cairo", "country": "EG", "latitude": 30.0444, "longitude": 31.2357},
    {"name": "STC Data Center Riyadh", "provider": "STC", "city": "Riyadh", "country": "SA", "latitude": 24.7136, "longitude": 46.6753},
    {"name": "STC Data Center Jeddah", "provider": "STC", "city": "Jeddah", "country": "SA", "latitude": 21.5433, "longitude": 39.1728},
    {"name": "STC Data Center Dammam", "provider": "STC", "city": "Dammam", "country": "SA", "latitude": 26.3927, "longitude": 49.9777},
    {"name": "Center3 Riyadh DC", "provider": "Center3", "city": "Riyadh", "country": "SA", "latitude": 24.7136, "longitude": 46.6753},
    {"name": "Khazna Data Centers Abu Dhabi 2", "provider": "Khazna", "city": "Abu Dhabi", "country": "AE", "latitude": 24.4537, "longitude": 54.3770},
    {"name": "Khazna Data Centers Dubai", "provider": "Khazna", "city": "Dubai", "country": "AE", "latitude": 25.0711, "longitude": 55.1323},
    {"name": "Moro Hub Dubai DC", "provider": "Moro Hub", "city": "Dubai", "country": "AE", "latitude": 25.2048, "longitude": 55.2708},
    {"name": "Etisalat SmartHub Dubai", "provider": "Etisalat", "city": "Dubai", "country": "AE", "latitude": 25.2048, "longitude": 55.2708},
    {"name": "Ooredoo Data Center Doha", "provider": "Ooredoo", "city": "Doha", "country": "QA", "latitude": 25.2854, "longitude": 51.5310},
    {"name": "Meeza Data Center Doha M-Vault", "provider": "Meeza", "city": "Doha", "country": "QA", "latitude": 25.2854, "longitude": 51.5310},
    {"name": "Beyon Connect Bahrain DC", "provider": "Beyon Connect", "city": "Manama", "country": "BH", "latitude": 26.2285, "longitude": 50.5860},
    {"name": "Turkcell Data Center Istanbul", "provider": "Turkcell", "city": "Istanbul", "country": "TR", "latitude": 41.0082, "longitude": 28.9784},
    {"name": "Turkcell Data Center Ankara", "provider": "Turkcell", "city": "Ankara", "country": "TR", "latitude": 39.9334, "longitude": 32.8597},
    {"name": "Turk Telekom Data Center Istanbul", "provider": "Turk Telekom", "city": "Istanbul", "country": "TR", "latitude": 41.0082, "longitude": 28.9784},
    {"name": "Bezeq Data Center Tel Aviv", "provider": "Bezeq", "city": "Tel Aviv", "country": "IL", "latitude": 32.0853, "longitude": 34.7818},
    {"name": "Med-1 Data Center Petach Tikva", "provider": "Med-1", "city": "Petach Tikva", "country": "IL", "latitude": 32.0840, "longitude": 34.8878},
    {"name": "Telecom Egypt Cairo DC", "provider": "Telecom Egypt", "city": "Cairo", "country": "EG", "latitude": 30.0444, "longitude": 31.2357},
    {"name": "Orange Egypt Smart Village DC", "provider": "Orange Egypt", "city": "Cairo", "country": "EG", "latitude": 30.0711, "longitude": 31.0175},
    {"name": "Maroc Telecom Rabat DC", "provider": "Maroc Telecom", "city": "Rabat", "country": "MA", "latitude": 34.0209, "longitude": -6.8416},
    {"name": "N+ONE Casablanca DC", "provider": "N+ONE", "city": "Casablanca", "country": "MA", "latitude": 33.5731, "longitude": -7.5898},
    {"name": "Rack Centre Lagos DC", "provider": "Rack Centre", "city": "Lagos", "country": "NG", "latitude": 6.5244, "longitude": 3.3792},
    {"name": "MainOne MDXi Lagos", "provider": "MainOne", "city": "Lagos", "country": "NG", "latitude": 6.4400, "longitude": 3.4190},
    {"name": "MainOne MDXi Accra", "provider": "MainOne", "city": "Accra", "country": "GH", "latitude": 5.6037, "longitude": -0.1870},
    {"name": "MainOne MDXi Abidjan", "provider": "MainOne", "city": "Abidjan", "country": "CI", "latitude": 5.3600, "longitude": -4.0083},
    {"name": "Paratus Windhoek DC", "provider": "Paratus", "city": "Windhoek", "country": "NA", "latitude": -22.5597, "longitude": 17.0832},
    {"name": "BSO Network Mauritius DC", "provider": "BSO", "city": "Ebene", "country": "MU", "latitude": -20.2455, "longitude": 57.4876},
    {"name": "Data Center Madagascar Antananarivo", "provider": "DC Madagascar", "city": "Antananarivo", "country": "MG", "latitude": -18.8792, "longitude": 47.5079},
    {"name": "iColo Mombasa DC", "provider": "iColo", "city": "Mombasa", "country": "KE", "latitude": -4.0435, "longitude": 39.6682},
    {"name": "Liquid Intelligent Tech Johannesburg", "provider": "Liquid Intelligent Tech", "city": "Johannesburg", "country": "ZA", "latitude": -26.2041, "longitude": 28.0473},
    {"name": "Liquid Intelligent Tech Nairobi", "provider": "Liquid Intelligent Tech", "city": "Nairobi", "country": "KE", "latitude": -1.2921, "longitude": 36.8219},
    {"name": "Liquid Intelligent Tech Kigali", "provider": "Liquid Intelligent Tech", "city": "Kigali", "country": "RW", "latitude": -1.9706, "longitude": 30.1044},
    {"name": "Claro Sao Paulo DC", "provider": "Claro", "city": "Sao Paulo", "state": "SP", "country": "BR", "latitude": -23.5505, "longitude": -46.6333},
    {"name": "Claro Rio DC", "provider": "Claro", "city": "Rio de Janeiro", "state": "RJ", "country": "BR", "latitude": -22.9068, "longitude": -43.1729},
    {"name": "Cirion Buenos Aires DC", "provider": "Cirion Technologies", "city": "Buenos Aires", "country": "AR", "latitude": -34.6037, "longitude": -58.3816},
    {"name": "Cirion Santiago DC", "provider": "Cirion Technologies", "city": "Santiago", "country": "CL", "latitude": -33.4489, "longitude": -70.6693},
    {"name": "Cirion Bogota DC", "provider": "Cirion Technologies", "city": "Bogota", "country": "CO", "latitude": 4.7110, "longitude": -74.0721},
    {"name": "Cirion Lima DC", "provider": "Cirion Technologies", "city": "Lima", "country": "PE", "latitude": -12.0464, "longitude": -77.0428},
    {"name": "Cirion Sao Paulo DC", "provider": "Cirion Technologies", "city": "Sao Paulo", "state": "SP", "country": "BR", "latitude": -23.5505, "longitude": -46.6333},
    {"name": "Cirion Mexico City DC", "provider": "Cirion Technologies", "city": "Mexico City", "country": "MX", "latitude": 19.4326, "longitude": -99.1332},
    {"name": "Odata SP02 Sao Paulo", "provider": "Odata", "city": "Sao Paulo", "state": "SP", "country": "BR", "latitude": -23.4700, "longitude": -46.6100},
    {"name": "Odata MX01 Queretaro", "provider": "Odata", "city": "Queretaro", "country": "MX", "latitude": 20.5888, "longitude": -100.3899},
    {"name": "Odata CO01 Bogota", "provider": "Odata", "city": "Bogota", "country": "CO", "latitude": 4.7110, "longitude": -74.0721},
    {"name": "GTD Santiago DC", "provider": "GTD", "city": "Santiago", "country": "CL", "latitude": -33.4489, "longitude": -70.6693},
    {"name": "ENTEL Santiago DC", "provider": "ENTEL", "city": "Santiago", "country": "CL", "latitude": -33.4489, "longitude": -70.6693},
    {"name": "IFX Networks Bogota DC", "provider": "IFX Networks", "city": "Bogota", "country": "CO", "latitude": 4.7110, "longitude": -74.0721},
    {"name": "IFX Networks Buenos Aires DC", "provider": "IFX Networks", "city": "Buenos Aires", "country": "AR", "latitude": -34.6037, "longitude": -58.3816},
    {"name": "IFX Networks Santiago DC", "provider": "IFX Networks", "city": "Santiago", "country": "CL", "latitude": -33.4489, "longitude": -70.6693},
    {"name": "IFX Networks Lima DC", "provider": "IFX Networks", "city": "Lima", "country": "PE", "latitude": -12.0464, "longitude": -77.0428},
    {"name": "IFX Networks Mexico City DC", "provider": "IFX Networks", "city": "Mexico City", "country": "MX", "latitude": 19.4326, "longitude": -99.1332},
    {"name": "Nabiax Madrid DC", "provider": "Nabiax", "city": "Madrid", "country": "ES", "latitude": 40.4168, "longitude": -3.7038},
    {"name": "Nabiax Barcelona DC", "provider": "Nabiax", "city": "Barcelona", "country": "ES", "latitude": 41.3851, "longitude": 2.1734},
    {"name": "Adam DC Amsterdam", "provider": "Adam", "city": "Amsterdam", "country": "NL", "latitude": 52.3676, "longitude": 4.9041},
    {"name": "Cyxtera AMS1 Amsterdam", "provider": "Cyxtera", "city": "Amsterdam", "country": "NL", "latitude": 52.3676, "longitude": 4.9041},
    {"name": "Cyxtera BOS1 Boston", "provider": "Cyxtera", "city": "Boston", "state": "MA", "country": "US", "latitude": 42.3601, "longitude": -71.0589},
    {"name": "Cyxtera LAX1 Los Angeles", "provider": "Cyxtera", "city": "Los Angeles", "state": "CA", "country": "US", "latitude": 34.0522, "longitude": -118.2437},
    {"name": "Cyxtera SFO1 San Francisco", "provider": "Cyxtera", "city": "San Francisco", "state": "CA", "country": "US", "latitude": 37.7749, "longitude": -122.4194},
    {"name": "Cyxtera DFW1 Dallas", "provider": "Cyxtera", "city": "Dallas", "state": "TX", "country": "US", "latitude": 32.7767, "longitude": -96.7970},
    {"name": "Cyxtera SIN1 Singapore", "provider": "Cyxtera", "city": "Singapore", "country": "SG", "latitude": 1.3521, "longitude": 103.8198},
    {"name": "Cyxtera LHR1 London", "provider": "Cyxtera", "city": "London", "country": "GB", "latitude": 51.5074, "longitude": -0.1278},
    {"name": "OVHcloud Beauharnois Canada", "provider": "OVHcloud", "city": "Beauharnois", "state": "QC", "country": "CA", "latitude": 45.3050, "longitude": -73.8680},
    {"name": "OVHcloud Strasbourg SBG", "provider": "OVHcloud", "city": "Strasbourg", "country": "FR", "latitude": 48.5734, "longitude": 7.7521},
    {"name": "OVHcloud London UK", "provider": "OVHcloud", "city": "London", "country": "GB", "latitude": 51.5074, "longitude": -0.1278},
    {"name": "OVHcloud Frankfurt DE", "provider": "OVHcloud", "city": "Frankfurt", "country": "DE", "latitude": 50.1109, "longitude": 8.6821},
    {"name": "OVHcloud Warsaw PL", "provider": "OVHcloud", "city": "Warsaw", "country": "PL", "latitude": 52.2297, "longitude": 21.0122},
    {"name": "OVHcloud Singapore SG", "provider": "OVHcloud", "city": "Singapore", "country": "SG", "latitude": 1.3521, "longitude": 103.8198},
    {"name": "OVHcloud Sydney AU", "provider": "OVHcloud", "city": "Sydney", "state": "NSW", "country": "AU", "latitude": -33.8688, "longitude": 151.2093},
    {"name": "OVHcloud Virginia US", "provider": "OVHcloud", "city": "Vint Hill", "state": "VA", "country": "US", "latitude": 38.7430, "longitude": -77.7292},
    {"name": "OVHcloud Hillsboro US", "provider": "OVHcloud", "city": "Hillsboro", "state": "OR", "country": "US", "latitude": 45.5229, "longitude": -122.9898},
    {"name": "Hetzner Nuremberg DC", "provider": "Hetzner", "city": "Nuremberg", "country": "DE", "latitude": 49.4521, "longitude": 11.0767},
    {"name": "Hetzner Helsinki DC", "provider": "Hetzner", "city": "Helsinki", "country": "FI", "latitude": 60.1699, "longitude": 24.9384},
    {"name": "Hetzner Ashburn US DC", "provider": "Hetzner", "city": "Ashburn", "state": "VA", "country": "US", "latitude": 39.0438, "longitude": -77.4874},
    {"name": "Hetzner Hillsboro US DC", "provider": "Hetzner", "city": "Hillsboro", "state": "OR", "country": "US", "latitude": 45.5229, "longitude": -122.9898},
    {"name": "Hetzner Singapore DC", "provider": "Hetzner", "city": "Singapore", "country": "SG", "latitude": 1.3521, "longitude": 103.8198},
    {"name": "Scaleway Paris DC6", "provider": "Scaleway", "city": "Paris", "country": "FR", "latitude": 48.9200, "longitude": 2.3500},
    {"name": "Scaleway Amsterdam AMS1", "provider": "Scaleway", "city": "Amsterdam", "country": "NL", "latitude": 52.3676, "longitude": 4.9041},
    {"name": "Scaleway Warsaw WAW1", "provider": "Scaleway", "city": "Warsaw", "country": "PL", "latitude": 52.2297, "longitude": 21.0122},
    {"name": "Leaseweb Amsterdam AMS1", "provider": "Leaseweb", "city": "Amsterdam", "country": "NL", "latitude": 52.3676, "longitude": 4.9041},
    {"name": "Leaseweb Frankfurt FRA1", "provider": "Leaseweb", "city": "Frankfurt", "country": "DE", "latitude": 50.1109, "longitude": 8.6821},
    {"name": "Leaseweb Washington DC US", "provider": "Leaseweb", "city": "Manassas", "state": "VA", "country": "US", "latitude": 38.7509, "longitude": -77.4753},
    {"name": "Leaseweb San Francisco US", "provider": "Leaseweb", "city": "San Francisco", "state": "CA", "country": "US", "latitude": 37.7749, "longitude": -122.4194},
    {"name": "Leaseweb Singapore SG", "provider": "Leaseweb", "city": "Singapore", "country": "SG", "latitude": 1.3521, "longitude": 103.8198},
    {"name": "Leaseweb Hong Kong HK", "provider": "Leaseweb", "city": "Hong Kong", "country": "HK", "latitude": 22.3193, "longitude": 114.1694},
    {"name": "Leaseweb Sydney AU", "provider": "Leaseweb", "city": "Sydney", "state": "NSW", "country": "AU", "latitude": -33.8688, "longitude": 151.2093},
    {"name": "Hivelocity Tampa FL DC", "provider": "Hivelocity", "city": "Tampa", "state": "FL", "country": "US", "latitude": 27.9506, "longitude": -82.4572},
    {"name": "Hivelocity New York DC", "provider": "Hivelocity", "city": "New York", "state": "NY", "country": "US", "latitude": 40.7128, "longitude": -74.0060},
    {"name": "Hivelocity Los Angeles DC", "provider": "Hivelocity", "city": "Los Angeles", "state": "CA", "country": "US", "latitude": 34.0522, "longitude": -118.2437},
    {"name": "Hivelocity Dallas DC", "provider": "Hivelocity", "city": "Dallas", "state": "TX", "country": "US", "latitude": 32.7767, "longitude": -96.7970},
    {"name": "365 Data Centers Nashville TN", "provider": "365 Data Centers", "city": "Nashville", "state": "TN", "country": "US", "latitude": 36.1627, "longitude": -86.7816},
    {"name": "365 Data Centers Indianapolis IN", "provider": "365 Data Centers", "city": "Indianapolis", "state": "IN", "country": "US", "latitude": 39.7684, "longitude": -86.1581},
    {"name": "365 Data Centers Buffalo NY", "provider": "365 Data Centers", "city": "Buffalo", "state": "NY", "country": "US", "latitude": 42.8864, "longitude": -78.8784},
    {"name": "365 Data Centers Detroit MI", "provider": "365 Data Centers", "city": "Detroit", "state": "MI", "country": "US", "latitude": 42.3314, "longitude": -83.0458},
    {"name": "365 Data Centers Philadelphia PA", "provider": "365 Data Centers", "city": "Philadelphia", "state": "PA", "country": "US", "latitude": 39.9526, "longitude": -75.1652},
    {"name": "US Signal Grand Rapids MI", "provider": "US Signal", "city": "Grand Rapids", "state": "MI", "country": "US", "latitude": 42.9634, "longitude": -85.6681},
    {"name": "US Signal Lansing MI", "provider": "US Signal", "city": "Lansing", "state": "MI", "country": "US", "latitude": 42.7325, "longitude": -84.5555},
    {"name": "US Signal Detroit MI", "provider": "US Signal", "city": "Detroit", "state": "MI", "country": "US", "latitude": 42.3314, "longitude": -83.0458},
    {"name": "Evoque Chandler AZ", "provider": "Evoque", "city": "Chandler", "state": "AZ", "country": "US", "latitude": 33.3062, "longitude": -111.8413},
    {"name": "Evoque Chicago IL", "provider": "Evoque", "city": "Chicago", "state": "IL", "country": "US", "latitude": 41.8781, "longitude": -87.6298},
    {"name": "Evoque Dallas TX", "provider": "Evoque", "city": "Dallas", "state": "TX", "country": "US", "latitude": 32.7767, "longitude": -96.7970},
    {"name": "Evoque Ashburn VA", "provider": "Evoque", "city": "Ashburn", "state": "VA", "country": "US", "latitude": 39.0438, "longitude": -77.4874},
    {"name": "zColo Ashburn VA", "provider": "zColo", "city": "Ashburn", "state": "VA", "country": "US", "latitude": 39.0438, "longitude": -77.4874},
    {"name": "zColo Seattle WA", "provider": "zColo", "city": "Seattle", "state": "WA", "country": "US", "latitude": 47.6062, "longitude": -122.3321},
    {"name": "zColo London UK", "provider": "zColo", "city": "London", "country": "GB", "latitude": 51.5074, "longitude": -0.1278},
    {"name": "ServerFarm Chicago IL", "provider": "ServerFarm", "city": "Chicago", "state": "IL", "country": "US", "latitude": 41.8781, "longitude": -87.6298},
    {"name": "ServerFarm Los Angeles CA", "provider": "ServerFarm", "city": "Los Angeles", "state": "CA", "country": "US", "latitude": 34.0522, "longitude": -118.2437},
    {"name": "ServerFarm London UK", "provider": "ServerFarm", "city": "London", "country": "GB", "latitude": 51.5074, "longitude": -0.1278},
    {"name": "ServerFarm Paris FR", "provider": "ServerFarm", "city": "Paris", "country": "FR", "latitude": 48.8566, "longitude": 2.3522},
]

def insert_expanded():
    conn = sqlite3.connect('dc_nexus.db', timeout=30)
    conn.execute('PRAGMA journal_mode=WAL')
    c = conn.cursor()
    
    c.execute('SELECT COUNT(*) FROM facilities')
    before = c.fetchone()[0]
    
    existing = set()
    c.execute('SELECT LOWER(name) FROM facilities')
    for row in c.fetchall():
        existing.add(row[0])
    
    now = datetime.utcnow().isoformat()
    rows = []
    for fac in EXPANDED_FACILITIES:
        name = fac.get('name', '').strip()
        if not name or len(name) < 2 or name.lower() in existing:
            continue
        existing.add(name.lower())
        rows.append((str(uuid.uuid4())[:12], name, fac.get('provider',''), fac.get('city',''),
                     fac.get('state',''), fac.get('country',''), fac.get('latitude'), fac.get('longitude'),
                     'Operational', 'global_directory', '', f"gd_{name[:40]}", now, now))
    
    c.executemany('''INSERT OR IGNORE INTO facilities 
        (id, name, provider, city, state, country, latitude, longitude, status, 
         source, source_url, source_id, first_seen, last_updated)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)''', rows)
    conn.commit()
    
    c.execute('SELECT COUNT(*) FROM facilities')
    after = c.fetchone()[0]
    conn.close()
    print(f'Inserted {len(rows)} new facilities. Database: {before} -> {after} (+{after-before})')
    return len(rows)

if __name__ == '__main__':
    insert_expanded()
