// Railway Infrastructure as Code for dchub-backend's services.
//
// Replaces Config as Code, which Railway stops reading on 2026-12-01. Every
// Config-as-Code file in this repo is gone (2026-09-26): root railway.toml /
// railway.json (#5606), services/daily/railway.json (#5620) and
// railway-extractor.toml (after the desirable-playfulness block was applied
// and its Config File cleared). Every service here runs on these settings;
// tests/test_web_dockerfile.py fails if any of those files comes back.
// Evaluated by the Railway CLI (`railway config plan` / `apply`), NOT at deploy
// time: merging a change here does nothing until it is applied.
//
// Declared here: dchub-backend (web), dchub-worker, dchub-daily,
// desirable-playfulness (extractor cron).
//
// ★ partial: this repo owns ONLY the services it declares. Project
// resourceful-essence also holds dchub-mcp-server (owned by partial
// "dchub-mcp-server" in that repo), render-pdf, function-bun and
// dchub-mpp-sidecar. Without a named partial an apply from here would delete them.
//
// ★ env: every variable is preserve() (value stays in Railway, never in git).
// A service() block with no env entry for a variable PLANS TO DELETE IT, and a
// missing `source` plans to disconnect the repo. Add new variables here as
// preserve() when you create them in Railway, or the next apply removes them.
import { defineRailway, github, preserve, project, service } from "railway/iac";

export const partial = "dchub-backend";

export default defineRailway(() => {
  // dchub-backend (web) and dchub-worker — values carried over from the root
  // railway.toml (deleted 2026-09-26), applied and verified 2026-09-26. Same image and
  // start command; DCHUB_ROLE=worker is what makes the worker a worker.
  // r-2026-07-15: web MUST run >= 2 replicas (single-replica outage). The worker
  // has run 2 as well, because the toml's numReplicas applies to it too.
  // restartPolicyType is omitted on purpose: ON_FAILURE is Railway's default and
  // is stored as null, so declaring it leaves a diff that never converges.
  const dchubBackendRepo = github("azmartone67/dchub-backend", { checkSuites: false });

  const web = service("dchub-backend", {
    source: dchubBackendRepo,
    // ★ DOCKERFILE + Dockerfile.web: the fix for the worker crashloop (#3222
    // 08-26, #5544 09-24) — under Railpack the venv's python and the runtime's
    // drifted apart. Losing these two lines brings that failure class back.
    build: { builder: "DOCKERFILE", dockerfilePath: "Dockerfile.web" },
    start: "bash start_web.sh",
    healthcheck: "/api/health",
    healthcheckTimeout: 900,
    replicas: { "us-west2": 2 },
    deploy: { numReplicas: 2, restartPolicyMaxRetries: 3, ipv6EgressEnabled: true },
    env: {
      ACTION_CLASSES_ENABLED: preserve(),
      ACTIVATION_NUDGE_ARM: preserve(),
      ADMIN_API_KEY: preserve(),
      ADMIN_INBOX_EMAIL: preserve(),
      ADMIN_SECRET: preserve(),
      AGENTIC_LOOP_ARM: preserve(),
      AGENT_REQUESTS_WRITER_ENABLE: preserve(),
      AIR_PERMIT_INGEST_ARM: preserve(),
      AI_PLATFORM_ONBOARDER_CRON_DISABLE: preserve(),
      AI_SURFACE_SENTINEL_AUTOFIX: preserve(),
      AI_SURFACE_SENTINEL_ENABLED: preserve(),
      ANTHROPIC_API_KEY: preserve(),
      ANTHROPIC_BASE_URL: preserve(),
      API_SECRET: preserve(),
      AUTOPOST_ENABLED: preserve(),
      AUTOPOST_SIZE: preserve(),
      AUTOPOST_THEME: preserve(),
      BLUESKY_APP_PASSWORD: preserve(),
      BLUESKY_HANDLE: preserve(),
      BRAIN_ADMIN_KEY: preserve(),
      BRAIN_AUTOMERGE_DRY_RUN: preserve(),
      BRAIN_AUTOMERGE_ENABLED: preserve(),
      BRAIN_AUTOMERGE_MAX_PER_RUN: preserve(),
      BRAIN_AUTONOMY_ENABLED: preserve(),
      BRAIN_CAPABILITY_LEDGER_ENABLED: preserve(),
      BRAIN_CAUSAL_ENABLE: preserve(),
      BRAIN_CAUSAL_ENABLED: preserve(),
      BRAIN_CODEGEN_EXPOSE_ENABLED: preserve(),
      BRAIN_DATA_GATHER_ENABLED: preserve(),
      BRAIN_DIGEST_EMAIL: preserve(),
      BRAIN_ENHANCER_ENABLED: preserve(),
      BRAIN_FIX_VERIFY: preserve(),
      BRAIN_FORECAST_FINDINGS_ENABLED: preserve(),
      BRAIN_INNOVATION_EMAIL_ENABLED: preserve(),
      BRAIN_INVESTIGATOR_ENABLED: preserve(),
      BRAIN_JANITOR_VERIFY_COMPLETED: preserve(),
      BRAIN_L22_HANDOFF_ENABLE: preserve(),
      BRAIN_MEDIA_BRIDGE_ENABLED: preserve(),
      BRAIN_MEMORY_RECALL_GATE_ENABLED: preserve(),
      BRAIN_NARRATIVE_ENABLED: preserve(),
      BRAIN_ORCHESTRATOR_ENABLED: preserve(),
      BRAIN_PROMOTE_ON_FAILURE_ENABLED: preserve(),
      BRAIN_PR_JANITOR_ENABLED: preserve(),
      BRAIN_RAG_ENABLED: preserve(),
      BRAIN_REASONING_LANE_ENABLED: preserve(),
      BRAIN_SELF_DIRECT_DAILY_CAP: preserve(),
      BRAIN_SELF_DIRECT_ENABLED: preserve(),
      BRAIN_SPEC_PROMOTE_ENABLED: preserve(),
      BRAIN_STRATEGIC_LEDGER_FEEDBACK_ENABLED: preserve(),
      BRAIN_VERIFY_RESOLVE_ENABLE: preserve(),
      CF_ACCOUNT_ID: preserve(),
      CF_ANALYTICS_READ_TOKEN: preserve(),
      CF_RULESET_TOKEN: preserve(),
      CF_WAF_EDIT_TOKEN: preserve(),
      CHUB_PREVIEW_ISERROR: preserve(),
      CLARITY_API_TOKEN: preserve(),
      CLOUDFLARE_ACCOUNT_ID: preserve(),
      CLOUDFLARE_API_TOKEN: preserve(),
      CLOUDFLARE_KV_NAMESPACE: preserve(),
      CLOUDFLARE_PROJECT_NAME: preserve(),
      CLOUDFLARE_ZONE_ID: preserve(),
      COHERE_API_KEY: preserve(),
      CONTENT_QUALITY_MIN: preserve(),
      CRAWLER_SCHEDULE: preserve(),
      CRM_PROVIDER: preserve(),
      CUSTOMER_WHITE_GLOVE_ACT: preserve(),
      DAILY_ADMIN_KEY: preserve(),
      DAILY_SVC_URL: preserve(),
      DATABASE_URL: preserve(),
      DB_POOL_MAX: preserve(),
      DB_POOL_MIN: preserve(),
      DCHUB_ADMIN_KEY: preserve(),
      DCHUB_ADMIN_SECRET: preserve(),
      DCHUB_AGENT_DIGEST_DRY_RUN: preserve(),
      DCHUB_API_BASE: preserve(),
      DCHUB_API_KEY: preserve(),
      DCHUB_API_KEYS: preserve(),
      DCHUB_API_URL: preserve(),
      DCHUB_AUTOPUB_LEGACY: preserve(),
      DCHUB_BIND_RECEIPT_ARM: preserve(),
      DCHUB_BRAIN_1M_CONTEXT: preserve(),
      DCHUB_BRAIN_L5_CONF_MIN: preserve(),
      DCHUB_BRAIN_MODEL_CHALLENGER: preserve(),
      DCHUB_BRAIN_MODEL_INSPECTOR: preserve(),
      DCHUB_BRAIN_MODEL_REASONING: preserve(),
      DCHUB_BRAIN_PREFER_FABLE: preserve(),
      DCHUB_BRAIN_STRATEGIC_DRAFT_PR: preserve(),
      DCHUB_BRIEFING_EMAIL: preserve(),
      DCHUB_CLAIM_NOTIFY: preserve(),
      DCHUB_CLAIM_NOTIFY_ON_MINT: preserve(),
      DCHUB_EDGE_KEY: preserve(),
      DCHUB_ENT_KEY: preserve(),
      DCHUB_FORCE_IPV4: preserve(),
      DCHUB_FROM_EMAIL: preserve(),
      DCHUB_FRONTEND_RO_TOKEN: preserve(),
      DCHUB_GAS_INDEX_ENABLED: preserve(),
      DCHUB_GRID_HEADROOM_TIER: preserve(),
      DCHUB_HEAL_CACHE_TTL: preserve(),
      DCHUB_HIGH_INTENT_THRESHOLD: preserve(),
      DCHUB_INCONTEXT_CLAIM: preserve(),
      DCHUB_INTERNAL_API: preserve(),
      DCHUB_INTERNAL_BOT_RATE_LIMIT_PER_MIN: preserve(),
      DCHUB_INTERNAL_KEY: preserve(),
      DCHUB_L22_REAL_PR: preserve(),
      DCHUB_MEDIA_AI_IMAGES: preserve(),
      DCHUB_OUTREACH_FROM_EMAIL: preserve(),
      DCHUB_PACK5_URL: preserve(),
      DCHUB_PREVIEW_ISERROR: preserve(),
      DCHUB_RESEND_API_KEY: preserve(),
      DCHUB_RETENTION_PITCH_ENABLED: preserve(),
      DCHUB_ROLE: preserve(),
      DCHUB_SELF_TRAFFIC_SESSIONS: preserve(),
      DCHUB_SESSION_SECRET: preserve(),
      DCHUB_SMOKE_ENTERPRISE_KEY: preserve(),
      DCHUB_STRIPE_DEVELOPER_LINK: preserve(),
      DCHUB_SYNC_KEY: preserve(),
      DCHUB_TRIAL_TOOL_DAILY_FULL: preserve(),
      DCHUB_UPGRADE_PATH_PREFIX: preserve(),
      DCHUB_WORKER_INTERNAL_URL: preserve(),
      DCHUB_WORKOS_AUD_ENFORCE: preserve(),
      DCHUB_WORKOS_OAUTH_ENABLED: preserve(),
      DCM_CRAWL_ENABLED: preserve(),
      DETECTOR_SCOUT_ENABLED: preserve(),
      DRY_RUN: preserve(),
      EIA_API_KEY: preserve(),
      ENTSOE_API_TOKEN: preserve(),
      EPA_AQS_API_EMAIL: preserve(),
      EPA_AQS_API_KEY: preserve(),
      ERCOT_API_KEY: preserve(),
      ERCOT_CLIENT_ID: preserve(),
      ERCOT_GEN_PRODUCT_ID: preserve(),
      ERCOT_LOAD_PRODUCT_ID: preserve(),
      ERCOT_PASSWORD: preserve(),
      ERCOT_USERNAME: preserve(),
      FCC_BDC_TOKEN: preserve(),
      FCC_BDC_USERNAME: preserve(),
      FIRMS_MAP_KEY: preserve(),
      FIRST_CALL_KEY_SURFACE_ENABLED: preserve(),
      FLYWHEEL_DISABLED: preserve(),
      FOUNDING_CUSTOMERS_CAP: preserve(),
      FRONTEND_RELIABILITY_MASTER_ARM: preserve(),
      GEMINI_API_KEY: preserve(),
      GEO_AUTOPUBLISH_ENABLED: preserve(),
      GITHUB_TOKEN: preserve(),
      GOOGLE_AI_KEY: preserve(),
      GOOGLE_CLIENT_ID: preserve(),
      GOOGLE_CLIENT_SECRET: preserve(),
      GOOGLE_SERVICE_ACCOUNT_JSON: preserve(),
      GRIDSTATUS_API_KEY: preserve(),
      GROQ_API_KEY: preserve(),
      HEALTH_AUTORESET_ENABLE: preserve(),
      HUBSPOT_API_KEY: preserve(),
      HUNTER_API_KEY: preserve(),
      INTERNAL_AUTH_LEGACY_OK: preserve(),
      INTERNAL_SYNC_SECRET: preserve(),
      IPINFO_TOKEN: preserve(),
      ISONE_PASSWORD: preserve(),
      ISONE_USERNAME: preserve(),
      JWT_SECRET: preserve(),
      L22_AUTO_MERGE_ENABLE: preserve(),
      LINKEDIN_ACCESS_TOKEN: preserve(),
      LINKEDIN_ATTACH_IMAGES: preserve(),
      LINKEDIN_CLIENT_ID: preserve(),
      LINKEDIN_CLIENT_SECRET: preserve(),
      LINKEDIN_COMPANY_ID: preserve(),
      LINKEDIN_ORG_ID: preserve(),
      LINKEDIN_PERSON_URN: preserve(),
      LINKEDIN_REDIRECT_URI: preserve(),
      LINKEDIN_RENDER_DRIFT_PROBE: preserve(),
      LOOP_CLOSURE_ARM: preserve(),
      MAP_ANON_COORD_DP: preserve(),
      MASTODON_ACCESS_TOKEN: preserve(),
      MCP_API_KEY: preserve(),
      MCP_OAUTH_ADVERTISE: preserve(),
      MEDIA_CLAIM_VERIFY: preserve(),
      MEDIA_DATA_STORY_FACTORY_ENABLED: preserve(),
      MEDIA_ENTITY_WINDOW_DAYS: preserve(),
      MEDIA_FACT_CHECK_GUARD_ENABLED: preserve(),
      MEDIA_GROWTH_ACT_ENABLED: preserve(),
      MEDIA_KIND_COOLDOWN_DAYS: preserve(),
      MEDIA_REACTIVE_AUTOPOST_ON_APPROVE: preserve(),
      MEDIA_REACTIVE_NEWS_ENABLED: preserve(),
      MEMORY_GC_LIMIT_MB: preserve(),
      MISTRAL_API_KEY: preserve(),
      MODELREL_KEY_COHERE: preserve(),
      MODELREL_KEY_DEEPSEEK: preserve(),
      MODELREL_KEY_GEMINI: preserve(),
      MODELREL_KEY_META: preserve(),
      MODELREL_KEY_MISTRAL: preserve(),
      MODELREL_KEY_MOONSHOT: preserve(),
      MODELREL_KEY_OPENAI: preserve(),
      MODELREL_KEY_PERPLEXITY: preserve(),
      MODELREL_KEY_QWEN: preserve(),
      MODELREL_KEY_XAI: preserve(),
      MODELREL_KEY_ZAI: preserve(),
      MONETIZE_GRID_FIBER_FREE_CALLS_7D: preserve(),
      MONTHLY_QUOTA_ENFORCE: preserve(),
      MOONSHOT_API_KEY: preserve(),
      MPP_FLAGSHIP_PREMIUM_ACK: preserve(),
      NEON_API_KEY: preserve(),
      NEON_DATABASE_URL: preserve(),
      NEON_REPLICA_URL: preserve(),
      NEWS_NER_LLM: preserve(),
      NEWS_VIA_CRON: preserve(),
      NREL_API_KEY: preserve(),
      OPENAI_API_KEY: preserve(),
      OPENAI_BASE_URL: preserve(),
      OPTIN_CTA_ENABLED: preserve(),
      OUTREACH_FROM_EMAIL: preserve(),
      OUTREACH_GENERATE_ENABLED: preserve(),
      OUTREACH_INTERVAL_MINUTES: preserve(),
      PAYWALL_CANARY_KEY: preserve(),
      PERPLEXITY_API_KEY: preserve(),
      PJM_PASSWORD: preserve(),
      PJM_USERNAME: preserve(),
      PLAUSIBLE_API_KEY: preserve(),
      POOL_HOLD_LOG_MS: preserve(),
      PRECISION_DEPTH_LEVER_GAS_BASIS_OFF: preserve(),
      PRECISION_DEPTH_MASTER_ACT_ENABLE: preserve(),
      PRECISION_LARGE_LOAD_TARIFF_JSON: preserve(),
      PRESS_INTEGRITY_ENFORCE: preserve(),
      PRICING_AB_DISABLE: preserve(),
      PR_SUBMIT_TOKEN: preserve(),
      PUBLISH_API_SECRET: preserve(),
      QA_MAP_KEY: preserve(),
      R2_ACCESS_KEY_ID: preserve(),
      R2_ACCOUNT_ID: preserve(),
      R2_BUCKET: preserve(),
      R2_BUCKET_NAME: preserve(),
      R2_ENDPOINT_URL: preserve(),
      R2_PUBLIC_BASE: preserve(),
      R2_SECRET_ACCESS_KEY: preserve(),
      RAG_LEVER_COVERAGE_OFF: preserve(),
      RAG_MASTER_ARM: preserve(),
      RAILWAY_API_TOKEN: preserve(),
      RAILWAY_BACKEND_URL: preserve(),
      RAILWAY_ENVIRONMENT: preserve(),
      RAILWAY_MCP_RATE_LIMIT_ENABLED: preserve(),
      RAILWAY_MCP_RATE_LIMIT_RPM: preserve(),
      RAILWAY_PUBLISH_SECRET: preserve(),
      REDIS_URL: preserve(),
      REFRESH_SECRET: preserve(),
      REGISTRY_SUBMIT_ENABLED: preserve(),
      RELIABILITY_MASTER_ARM: preserve(),
      RENDER_API_KEY: preserve(),
      RENDER_DEPLOY_HOOK_URL: preserve(),
      REPO_ADMIN_TOKEN: preserve(),
      RESEND_API_KEY: preserve(),
      RESEND_WEBHOOK_SECRET: preserve(),
      SECRET_KEY: preserve(),
      SENDGRID_API_KEY: preserve(),
      SENTINEL_AUTO_MERGE_DRY_RUN: preserve(),
      SMITHERY_API_KEY: preserve(),
      SMITHERY_TOKEN: preserve(),
      SMTP_FROM_EMAIL: preserve(),
      SMTP_FROM_NAME: preserve(),
      SMTP_HOST: preserve(),
      SMTP_PASSWORD: preserve(),
      SMTP_PORT: preserve(),
      SMTP_USERNAME: preserve(),
      SPEC_DEBT_CLOSE_ON_QUIET: preserve(),
      SPEC_IMPLEMENTER_ARM: preserve(),
      SQUASHER_AGENT_MAX_PER_DAY: preserve(),
      STRIPE_PRICE_DEV_MONTHLY: preserve(),
      STRIPE_PRICE_PRO_A: preserve(),
      STRIPE_PRICE_PRO_ANNUAL: preserve(),
      STRIPE_PRICE_PRO_B: preserve(),
      STRIPE_PRICE_RESEARCH_SEED_ANNUAL: preserve(),
      STRIPE_PUBLISHABLE_KEY: preserve(),
      STRIPE_SECRET_KEY: preserve(),
      STRIPE_WEBHOOK_SECRET: preserve(),
      STRIPE_WEBHOOK_SECRET_LIVE: preserve(),
      STRIPE_WEBHOOK_SECRET_MCP: preserve(),
      SUBSTACK_SID: preserve(),
      THIN_INFRA_SLICE: preserve(),
      TOGETHER_API_KEY: preserve(),
      TWITTER_ACCESS_SECRET: preserve(),
      TWITTER_ACCESS_TOKEN: preserve(),
      TWITTER_API_KEY: preserve(),
      TWITTER_API_SECRET: preserve(),
      TWITTER_BEARER_TOKEN: preserve(),
      TWITTER_PUBLISHER_ENABLED: preserve(),
      VAPID_EMAIL: preserve(),
      VAPID_PRIVATE_KEY: preserve(),
      VAPID_PUBLIC_KEY: preserve(),
      WEBMCP_ORIGIN_TRIAL_TOKEN: preserve(),
      WINS_POSTER_AUTOPILOT_ENABLED: preserve(),
      WORKOS_API_KEY: preserve(),
      WORKOS_AUTHKIT_DOMAIN: preserve(),
      WORKOS_CLIENT_ID: preserve(),
      WRI_AQUEDUCT_URL: preserve(),
      X402_ENABLED: preserve(),
      X402_RECIPIENT_ADDRESS: preserve(),
      XAI_API_KEY: preserve(),
      YOUR_API_KEY: preserve(),
      YOU_API_KEY: preserve(),
      "dchub-full-deploy-2026-04": preserve(),
      "dchub-mcp-helper-publish": preserve(),
    },
  });

  const worker = service("dchub-worker", {
    source: dchubBackendRepo,
    // ★ DOCKERFILE + Dockerfile.web: the fix for the worker crashloop (#3222
    // 08-26, #5544 09-24) — under Railpack the venv's python and the runtime's
    // drifted apart. Losing these two lines brings that failure class back.
    build: { builder: "DOCKERFILE", dockerfilePath: "Dockerfile.web" },
    start: "bash start_web.sh",
    healthcheck: "/api/health",
    healthcheckTimeout: 900,
    replicas: { "us-west2": 2 },
    deploy: { restartPolicyMaxRetries: 3 },
    env: {
      ADMIN_API_KEY: preserve(),
      ADMIN_INBOX_EMAIL: preserve(),
      ADMIN_SECRET: preserve(),
      AGENTIC_LOOP_ARM: preserve(),
      AI_PLATFORM_ONBOARDER_CRON_DISABLE: preserve(),
      AI_SURFACE_SENTINEL_AUTOFIX: preserve(),
      AI_SURFACE_SENTINEL_ENABLED: preserve(),
      ANTHROPIC_API_KEY: preserve(),
      ANTHROPIC_BASE_URL: preserve(),
      API_SECRET: preserve(),
      AUTOPOST_ENABLED: preserve(),
      AUTOPOST_SIZE: preserve(),
      AUTOPOST_THEME: preserve(),
      BLUESKY_APP_PASSWORD: preserve(),
      BLUESKY_HANDLE: preserve(),
      BRAIN_ADMIN_KEY: preserve(),
      BRAIN_AUTOMERGE_DRY_RUN: preserve(),
      BRAIN_AUTOMERGE_ENABLED: preserve(),
      BRAIN_AUTONOMY_ENABLED: preserve(),
      BRAIN_CAPABILITY_LEDGER_ENABLED: preserve(),
      BRAIN_CAUSAL_ENABLED: preserve(),
      BRAIN_CODEGEN_EXPOSE_ENABLED: preserve(),
      BRAIN_DATA_GATHER_ENABLED: preserve(),
      BRAIN_DIGEST_EMAIL: preserve(),
      BRAIN_ENHANCER_ENABLED: preserve(),
      BRAIN_FIX_VERIFY: preserve(),
      BRAIN_FORECAST_FINDINGS_ENABLED: preserve(),
      BRAIN_INNOVATION_EMAIL_ENABLED: preserve(),
      BRAIN_INVESTIGATOR_ENABLED: preserve(),
      BRAIN_JANITOR_VERIFY_COMPLETED: preserve(),
      BRAIN_L22_HANDOFF_ENABLE: preserve(),
      BRAIN_MEDIA_BRIDGE_ENABLED: preserve(),
      BRAIN_MEMORY_RECALL_GATE_ENABLED: preserve(),
      BRAIN_NARRATIVE_ENABLED: preserve(),
      BRAIN_ORCHESTRATOR_ENABLED: preserve(),
      BRAIN_PROMOTE_ON_FAILURE_ENABLED: preserve(),
      BRAIN_PR_JANITOR_ENABLED: preserve(),
      BRAIN_RAG_ENABLED: preserve(),
      BRAIN_REASONING_LANE_ENABLED: preserve(),
      BRAIN_REVIEW_LANE_ENABLED: preserve(),
      BRAIN_REVIEW_LANE_MAX_OPEN: preserve(),
      BRAIN_SELF_DIRECT_DAILY_CAP: preserve(),
      BRAIN_SELF_DIRECT_ENABLED: preserve(),
      BRAIN_SPEC_PROMOTE_ENABLED: preserve(),
      BRAIN_STRATEGIC_LEDGER_FEEDBACK_ENABLED: preserve(),
      BRAIN_VERIFY_RESOLVE_ENABLE: preserve(),
      CF_ACCOUNT_ID: preserve(),
      CF_RULESET_TOKEN: preserve(),
      CF_WAF_EDIT_TOKEN: preserve(),
      CLOUDFLARE_ACCOUNT_ID: preserve(),
      CLOUDFLARE_API_TOKEN: preserve(),
      CLOUDFLARE_KV_NAMESPACE: preserve(),
      CLOUDFLARE_PROJECT_NAME: preserve(),
      CLOUDFLARE_ZONE_ID: preserve(),
      COHERE_API_KEY: preserve(),
      CONTENT_QUALITY_MIN: preserve(),
      CRAWLER_SCHEDULE: preserve(),
      CRM_PROVIDER: preserve(),
      CUSTOMER_WHITE_GLOVE_ACT: preserve(),
      DAILY_ADMIN_KEY: preserve(),
      DAILY_SVC_URL: preserve(),
      DATABASE_URL: preserve(),
      DB_POOL_MAX: preserve(),
      DB_POOL_MIN: preserve(),
      DCHUB_ADMIN_KEY: preserve(),
      DCHUB_AGENT_DIGEST_DRY_RUN: preserve(),
      DCHUB_API_BASE: preserve(),
      DCHUB_API_KEY: preserve(),
      DCHUB_API_KEYS: preserve(),
      DCHUB_API_URL: preserve(),
      DCHUB_AUTOPUB_LEGACY: preserve(),
      DCHUB_BRAIN_1M_CONTEXT: preserve(),
      DCHUB_BRAIN_L5_CONF_MIN: preserve(),
      DCHUB_BRAIN_MODEL_CHALLENGER: preserve(),
      DCHUB_BRAIN_MODEL_INSPECTOR: preserve(),
      DCHUB_BRAIN_MODEL_REASONING: preserve(),
      DCHUB_BRAIN_PREFER_FABLE: preserve(),
      DCHUB_BRAIN_STRATEGIC_DRAFT_PR: preserve(),
      DCHUB_BRIEFING_EMAIL: preserve(),
      DCHUB_CLAIM_NOTIFY: preserve(),
      DCHUB_ENT_KEY: preserve(),
      DCHUB_FORCE_IPV4: preserve(),
      DCHUB_FROM_EMAIL: preserve(),
      DCHUB_GAS_INDEX_ENABLED: preserve(),
      DCHUB_HEAL_CACHE_TTL: preserve(),
      DCHUB_HIGH_INTENT_THRESHOLD: preserve(),
      DCHUB_INCONTEXT_CLAIM: preserve(),
      DCHUB_INTERNAL_API: preserve(),
      DCHUB_INTERNAL_KEY: preserve(),
      DCHUB_L22_REAL_PR: preserve(),
      DCHUB_MEDIA_AI_IMAGES: preserve(),
      DCHUB_OUTREACH_FROM_EMAIL: preserve(),
      DCHUB_PACK5_URL: preserve(),
      DCHUB_PUSH_FORCE: preserve(),
      DCHUB_RESEND_API_KEY: preserve(),
      DCHUB_ROLE: preserve(),
      DCHUB_SESSION_SECRET: preserve(),
      DCHUB_SMOKE_ENTERPRISE_KEY: preserve(),
      DCHUB_STRIPE_DEVELOPER_LINK: preserve(),
      DCHUB_SYNC_KEY: preserve(),
      DCHUB_TRIAL_TOOL_DAILY_FULL: preserve(),
      DCHUB_WORKOS_AUD_ENFORCE: preserve(),
      DCM_CRAWL_ENABLED: preserve(),
      DRY_RUN: preserve(),
      EIA_API_KEY: preserve(),
      ENTSOE_API_TOKEN: preserve(),
      EPA_AQS_API_EMAIL: preserve(),
      EPA_AQS_API_KEY: preserve(),
      ERCOT_API_KEY: preserve(),
      ERCOT_CLIENT_ID: preserve(),
      ERCOT_GEN_PRODUCT_ID: preserve(),
      ERCOT_LOAD_PRODUCT_ID: preserve(),
      ERCOT_PASSWORD: preserve(),
      ERCOT_USERNAME: preserve(),
      FCC_BDC_TOKEN: preserve(),
      FCC_BDC_USERNAME: preserve(),
      FIRMS_MAP_KEY: preserve(),
      FIRST_CALL_KEY_SURFACE_ENABLED: preserve(),
      FOUNDING_CUSTOMERS_CAP: preserve(),
      FRONTEND_RELIABILITY_MASTER_ARM: preserve(),
      GEMINI_API_KEY: preserve(),
      GITHUB_TOKEN: preserve(),
      GOOGLE_AI_KEY: preserve(),
      GOOGLE_CLIENT_ID: preserve(),
      GOOGLE_CLIENT_SECRET: preserve(),
      GOOGLE_SERVICE_ACCOUNT_JSON: preserve(),
      GRIDSTATUS_API_KEY: preserve(),
      GROQ_API_KEY: preserve(),
      HEALTH_AUTORESET_ENABLE: preserve(),
      HUBSPOT_API_KEY: preserve(),
      HUNTER_API_KEY: preserve(),
      INTERNAL_AUTH_LEGACY_OK: preserve(),
      INTERNAL_SYNC_SECRET: preserve(),
      IPINFO_TOKEN: preserve(),
      ISONE_PASSWORD: preserve(),
      ISONE_USERNAME: preserve(),
      JWT_SECRET: preserve(),
      L22_AUTO_MERGE_ENABLE: preserve(),
      LINKEDIN_ATTACH_IMAGES: preserve(),
      LINKEDIN_CLIENT_ID: preserve(),
      LINKEDIN_CLIENT_SECRET: preserve(),
      LINKEDIN_COMPANY_ID: preserve(),
      LINKEDIN_ORG_ID: preserve(),
      LINKEDIN_PERSON_URN: preserve(),
      LINKEDIN_REDIRECT_URI: preserve(),
      LINKEDIN_RENDER_DRIFT_PROBE: preserve(),
      MASTODON_ACCESS_TOKEN: preserve(),
      MCP_API_KEY: preserve(),
      MEDIA_DATA_STORY_FACTORY_ENABLED: preserve(),
      MEDIA_ENTITY_WINDOW_DAYS: preserve(),
      MEDIA_FACT_CHECK_GUARD_ENABLED: preserve(),
      MEDIA_REACTIVE_AUTOPOST_ON_APPROVE: preserve(),
      MEDIA_REACTIVE_NEWS_ENABLED: preserve(),
      MEMORY_GC_LIMIT_MB: preserve(),
      MISTRAL_API_KEY: preserve(),
      MODELREL_KEY_COHERE: preserve(),
      MODELREL_KEY_DEEPSEEK: preserve(),
      MODELREL_KEY_GEMINI: preserve(),
      MODELREL_KEY_META: preserve(),
      MODELREL_KEY_MISTRAL: preserve(),
      MODELREL_KEY_MOONSHOT: preserve(),
      MODELREL_KEY_OPENAI: preserve(),
      MODELREL_KEY_PERPLEXITY: preserve(),
      MODELREL_KEY_QWEN: preserve(),
      MODELREL_KEY_XAI: preserve(),
      MODELREL_KEY_ZAI: preserve(),
      MONETIZE_GRID_FIBER_FREE_CALLS_7D: preserve(),
      MOONSHOT_API_KEY: preserve(),
      NEON_DATABASE_URL: preserve(),
      NEON_REPLICA_URL: preserve(),
      NEWS_NER_LLM: preserve(),
      NEWS_VIA_CRON: preserve(),
      NREL_API_KEY: preserve(),
      OPENAI_API_KEY: preserve(),
      OPENAI_BASE_URL: preserve(),
      OPTIN_CTA_ENABLED: preserve(),
      OUTREACH_FROM_EMAIL: preserve(),
      OUTREACH_GENERATE_ENABLED: preserve(),
      OUTREACH_INTERVAL_MINUTES: preserve(),
      PAYWALL_CANARY_KEY: preserve(),
      PERPLEXITY_API_KEY: preserve(),
      PJM_PASSWORD: preserve(),
      PJM_USERNAME: preserve(),
      PLAUSIBLE_API_KEY: preserve(),
      PRECISION_DEPTH_LEVER_GAS_BASIS_OFF: preserve(),
      PRECISION_DEPTH_MASTER_ACT_ENABLE: preserve(),
      PRECISION_LARGE_LOAD_TARIFF_JSON: preserve(),
      PRICING_AB_DISABLE: preserve(),
      PR_SUBMIT_TOKEN: preserve(),
      PUBLISH_API_SECRET: preserve(),
      R2_ACCESS_KEY_ID: preserve(),
      R2_ACCOUNT_ID: preserve(),
      R2_BUCKET: preserve(),
      R2_BUCKET_NAME: preserve(),
      R2_ENDPOINT_URL: preserve(),
      R2_PUBLIC_BASE: preserve(),
      R2_SECRET_ACCESS_KEY: preserve(),
      RAG_LEVER_COVERAGE_OFF: preserve(),
      RAG_MASTER_ARM: preserve(),
      RAILWAY_BACKEND_URL: preserve(),
      RAILWAY_MCP_RATE_LIMIT_ENABLED: preserve(),
      RAILWAY_MCP_RATE_LIMIT_RPM: preserve(),
      RAILWAY_PUBLISH_SECRET: preserve(),
      REDIS_URL: preserve(),
      REFRESH_SECRET: preserve(),
      RELIABILITY_MASTER_ARM: preserve(),
      RENDER_API_KEY: preserve(),
      RENDER_DEPLOY_HOOK_URL: preserve(),
      RESEND_API_KEY: preserve(),
      SENDGRID_API_KEY: preserve(),
      SENTINEL_AUTO_MERGE_DRY_RUN: preserve(),
      SLO_SENTINEL_ROLLBACK: preserve(),
      SMITHERY_TOKEN: preserve(),
      SMTP_FROM_EMAIL: preserve(),
      SMTP_FROM_NAME: preserve(),
      SMTP_HOST: preserve(),
      SMTP_PASSWORD: preserve(),
      SMTP_PORT: preserve(),
      SMTP_USERNAME: preserve(),
      STRIPE_PRICE_DEV_MONTHLY: preserve(),
      STRIPE_PRICE_PRO_A: preserve(),
      STRIPE_PRICE_PRO_ANNUAL: preserve(),
      STRIPE_PRICE_PRO_B: preserve(),
      STRIPE_PRICE_RESEARCH_SEED_ANNUAL: preserve(),
      STRIPE_PUBLISHABLE_KEY: preserve(),
      STRIPE_SECRET_KEY: preserve(),
      STRIPE_WEBHOOK_SECRET: preserve(),
      STRIPE_WEBHOOK_SECRET_LIVE: preserve(),
      STRIPE_WEBHOOK_SECRET_MCP: preserve(),
      TOGETHER_API_KEY: preserve(),
      TWITTER_ACCESS_SECRET: preserve(),
      TWITTER_ACCESS_TOKEN: preserve(),
      TWITTER_API_KEY: preserve(),
      TWITTER_API_SECRET: preserve(),
      TWITTER_BEARER_TOKEN: preserve(),
      TWITTER_PUBLISHER_ENABLED: preserve(),
      VAPID_EMAIL: preserve(),
      VAPID_PRIVATE_KEY: preserve(),
      VAPID_PUBLIC_KEY: preserve(),
      WINS_POSTER_AUTOPILOT_ENABLED: preserve(),
      WORKOS_API_KEY: preserve(),
      WORKOS_AUTHKIT_DOMAIN: preserve(),
      WORKOS_CLIENT_ID: preserve(),
      WRI_AQUEDUCT_S3_PATH: preserve(),
      X402_ENABLED: preserve(),
      X402_RECIPIENT_ADDRESS: preserve(),
      XAI_API_KEY: preserve(),
      YOUR_API_KEY: preserve(),
      YOU_API_KEY: preserve(),
      "dchub-full-deploy-2026-04": preserve(),
      "dchub-mcp-helper-publish": preserve(),
    },
  });

  // dchub-daily — its own root dir and Dockerfile; deploys only when
  // services/daily/** changes (watchPatterns). Values were applied from here on
  // 2026-09-25 while services/daily/railway.json still existed; that file is
  // deleted in the same PR that re-adds this block. `start` is the Dockerfile
  // CMD (the json's older copy lacked `exec` and `--log-level info`).
  const daily = service("dchub-daily", {
    source: github("azmartone67/dchub-backend", { checkSuites: false, rootDirectory: "services/daily" }),
    build: { builder: "DOCKERFILE", dockerfilePath: "Dockerfile", watchPatterns: ["services/daily/**"] },
    start: "sh -c 'exec uvicorn app:app --host 0.0.0.0 --port ${PORT:-8080} --log-level info'",
    healthcheck: "/health",
    healthcheckTimeout: 120,
    replicas: { "us-west2": 1 },
    deploy: { restartPolicyMaxRetries: 3 },
    env: {
      AUTOPOST_ENABLED: preserve(),
      AUTOPOST_SIZE: preserve(),
      AUTOPOST_THEME: preserve(),
      DAILY_RENDER_ORIGIN: preserve(),
      DATABASE_URL: preserve(),
      DCHUB_API_BASE: preserve(),
      DCHUB_API_KEY: preserve(),
      DRY_RUN: preserve(),
      R2_ACCESS_KEY_ID: preserve(),
      R2_ACCOUNT_ID: preserve(),
      R2_BUCKET: preserve(),
      R2_PUBLIC_BASE: preserve(),
      R2_SECRET_ACCESS_KEY: preserve(),
      REFRESH_SECRET: preserve(),
    },
  });

  // desirable-playfulness — the extractor cron (extractor_cron.py every 5 min).
  // Values from the retired railway-extractor.toml, whose header
  // documented the crash history this start command answers: under Railpack a
  // container sometimes started mid-mise-reinstall and ran a bare interpreter
  // (09-06 8c643bec, 09-08 7dfd3fe1). Dockerfile.extractor bakes the venv in;
  // the start command probes that the deps import (5 tries x 3s) and FAILS LOUDLY
  // instead of falling back to python3 — the `|| P=python3` fallback (#4046/#4050)
  // selected exactly the bare interpreter that crashes, and #4257 removed it.
  // Verify by a firing's log line: `[extractor] interpreter=/app/.venv/bin/python`.
  // restartPolicyType NEVER is NOT Railway's default, so it must stay declared:
  // a cron failure waits for the next firing instead of restarting.
  const extractor = service("desirable-playfulness", {
    source: dchubBackendRepo,
    build: { builder: "DOCKERFILE", dockerfilePath: "Dockerfile.extractor" },
    start: "sh -c 'P=\"${VIRTUAL_ENV:-/app/.venv}/bin/python\"; i=0; until \"$P\" -c \"import psycopg2, anthropic\" 2>/dev/null; do i=$((i+1)); if [ \"$i\" -ge 5 ]; then echo \"[extractor] FATAL: psycopg2/anthropic still unimportable via $P after ${i} tries; refusing to fall back to a bare interpreter\"; exit 1; fi; echo \"[extractor] deps unimportable via $P (try $i) - waiting for the runtime to settle\"; sleep 3; done; echo \"[extractor] interpreter=$P\"; exec \"$P\" extractor_cron.py --limit 50'",
    replicas: { "us-west2": 1 },
    deploy: { cronSchedule: "*/5 * * * *", restartPolicyType: "NEVER" },
    env: {
      ANTHROPIC_API_KEY: preserve(),
      CLAUDE_MODEL: preserve(),
      DRY_RUN: preserve(),
      EIA_API_KEY: preserve(),
      NEON_DATABASE_URL: preserve(),
    },
  });

  return project("resourceful-essence", {
    resources: [web, worker, daily, extractor],
  });
});
