#!/usr/bin/env python3
"""refresh_meta_replays.py — re-capture the /integrations/meta replays KEYED and
rebake routes/meta_replays.py between its BAKED-REPLAYS markers.

Run weekly by .github/workflows/refresh-meta-replays.yml (Meta's citation
engine weights recency, so the stamp must move — but only honestly), or by
hand: DCHUB_REVIEWER_KEY=... python3 scripts/refresh_meta_replays.py

HONESTY CONTRACT (the reason this script exists instead of a sed on the date):
- retrieved_at moves ONLY when every capture succeeded end-to-end. Any failure
  exits nonzero and leaves the file byte-identical — a refresh that re-stamps
  on failure is how a date lies (see the registry+clock traps, 2026-07-30).
- Each intent must still route to the class recorded in _REPLAY_INTENTS. A
  routing drift FAILS the run rather than silently rebaking a wrong-class
  replay onto a citability page (the tax intent routed to facility_search
  until planner v5.6 — that page must never have shipped).
- Every baked replay must carry >=1 executed step and >=1 actual rejection.
- Minted credentials (auto_trial_key etc.) are scrubbed before anything is
  written to disk.

The intent list itself lives in routes/meta_replays.py (_REPLAY_INTENTS) so the
page and the refresh can never disagree about what is captured. It is read via
ast.literal_eval — a pure literal, no import of the routes package needed.
"""
from __future__ import annotations

import ast
import datetime as _dt
import json
import os
import pathlib
import py_compile
import re
import sys
import time
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = ROOT / "routes" / "meta_replays.py"
BASE = os.environ.get("DCHUB_MCP_URL", "https://dchub.cloud/mcp")
UA = "dchub-replay-refresh/1.0 (internal capture; excluded by clientname prefix)"
BEGIN = "# ── BAKED-REPLAYS BEGIN — generated by scripts/refresh_meta_replays.py; do not hand-edit ──"
END = "# ── BAKED-REPLAYS END ──"


def _fail(msg: str) -> None:
    print(f"REFRESH FAILED: {msg}", file=sys.stderr)
    sys.exit(1)


def _key() -> str:
    k = (os.environ.get("DCHUB_REVIEWER_KEY") or "").strip()
    if not k:
        p = pathlib.Path.home() / ".dchub_reviewer_key"
        if p.exists():
            k = p.read_text().strip()
    if not k:
        _fail("no key — set DCHUB_REVIEWER_KEY (repo secret) or ~/.dchub_reviewer_key")
    return k


def _read_intents(src: str) -> list[dict]:
    m = re.search(r"_REPLAY_INTENTS\s*=\s*(\[.*?\n\])", src, re.S)
    if not m:
        _fail("could not find _REPLAY_INTENTS in routes/meta_replays.py")
    intents = ast.literal_eval(m.group(1))
    if not intents or not all(i.get("intent") and i.get("expect_class") for i in intents):
        _fail("_REPLAY_INTENTS parsed empty or malformed — refusing to bake nothing")
    return intents


def _post(payload: dict, key: str, sid: str | None = None, timeout: int = 240):
    req = urllib.request.Request(BASE, data=json.dumps(payload).encode(), headers={
        "Content-Type": "application/json",
        "Accept": "application/json, text/event-stream",
        "User-Agent": UA,
        "X-API-Key": key,
        **({"Mcp-Session-Id": sid} if sid else {}),
    })
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.headers.get("Mcp-Session-Id"), r.read().decode()


def _parse(body: str) -> dict:
    if body.lstrip().startswith("event:") or body.startswith("data:") or "\ndata:" in body:
        datas = [ln[5:].strip() for ln in body.splitlines() if ln.startswith("data:")]
        if datas:
            return json.loads(datas[-1])
    return json.loads(body)


def _scrub(obj):
    _DROP = {"auto_trial_key", "api_key", "persist_command", "retry_with_header", "persist_config"}
    if isinstance(obj, dict):
        return {k: ("[scrubbed]" if k in _DROP else _scrub(v)) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_scrub(x) for x in obj]
    return obj


def _capture(intent: str, key: str, sid: str) -> dict:
    _, body = _post({"jsonrpc": "2.0", "id": 10, "method": "tools/call",
                     "params": {"name": "execute_plan", "arguments": {"intent": intent}}},
                    key, sid=sid)
    data = _parse(body)
    if "error" in data:
        _fail(f"{intent!r}: MCP error {data['error']}")
    sc = (data.get("result") or {}).get("structuredContent") or {}
    if not sc:
        _fail(f"{intent!r}: empty structuredContent")
    return _scrub(sc)


def _drop_none(obj):
    if isinstance(obj, dict):
        return {k: _drop_none(v) for k, v in obj.items() if v is not None}
    if isinstance(obj, list):
        return [_drop_none(x) for x in obj]
    return obj


def _bake(sc: dict, intent: str, expect_class: str) -> dict:
    cls = sc.get("intent_class")
    if cls != expect_class:
        _fail(f"{intent!r}: routed to {cls!r}, expected {expect_class!r} — a routing "
              f"drift must be fixed (or the contract updated) before rebaking")
    rep = sc.get("replay") or {}
    executed = [{"tool": e.get("tool"), "ms": int(e.get("ms") or 0),
                 "status": str(e.get("status") or "executed")}
                for e in (sc.get("executed") or []) if e.get("tool")]
    ran = [e for e in executed if e["status"] == "executed"]
    if not ran:
        _fail(f"{intent!r}: zero executed steps — nothing citable to bake")
    rejected = [{"tool": r.get("tool"), "reason": r.get("reason")}
                for r in (rep.get("rejected") or []) if r.get("tool") and r.get("reason")]
    if not rejected:
        _fail(f"{intent!r}: zero rejections in the keyed replay — the page's whole "
              f"premise is the rejected-path rationale; refusing to bake without it")
    decisions = rep.get("decisions") or []
    d0 = decisions[0] if decisions else {}
    totals = sc.get("totals") or {}
    nr = sc.get("next_recipe") or {}
    return _drop_none({
        "intent": intent,
        "intent_class": cls,
        "planner_version": str(sc.get("planner_version") or rep.get("planner_version") or "?"),
        "steps": len(executed),
        "ms": int(totals.get("ms") or sum(e["ms"] for e in ran)),
        "lead_tool": ran[0]["tool"],
        "confidence": d0.get("decision_confidence"),
        "rationale": d0.get("decision"),
        "executed": executed,
        "rejected": rejected,
        "decisions_total": len(decisions),
        "next_recipe": {k: nr[k] for k in ("prompt", "why") if nr.get(k)},
        # Measured 2026-07-28 (v2 bake): anonymous truncates the rejected list
        # to 1 while the keyed capture carries them all. Re-measure if tiering
        # changes; the page renders this as "an anonymous caller sees 1 of N".
        "anon_rejected_shown": 1,
    })


def main() -> None:
    src = TARGET.read_text(encoding="utf-8")
    if BEGIN not in src or END not in src:
        _fail("BAKED-REPLAYS markers missing from routes/meta_replays.py")
    intents = _read_intents(src)
    key = _key()

    sid, _ = _post({"jsonrpc": "2.0", "id": 1, "method": "initialize",
                    "params": {"protocolVersion": "2025-03-26", "capabilities": {},
                               "clientInfo": {"name": "dchub-replay-refresh", "version": "1.0"}}}, key)
    if not sid:
        _fail("no Mcp-Session-Id header on initialize")
    _post({"jsonrpc": "2.0", "method": "notifications/initialized"}, key, sid=sid)

    baked = []
    for it in intents:
        t0 = time.time()
        entry = _bake(_capture(it["intent"], key, sid), it["intent"], it["expect_class"])
        print(f"  ok  {it['intent'][:60]!r} → {entry['intent_class']} "
              f"({len(entry['rejected'])} rejections, {int((time.time()-t0)*1000)} ms)")
        baked.append(entry)

    stamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    body = json.dumps(baked, indent=4, ensure_ascii=False)
    block = (f"{BEGIN}\n_RETRIEVED_AT = '{stamp}'\n_TIER = 'keyed'\n\n"
             f"_BAKED = {body}\n{END}")
    out = src[: src.index(BEGIN)] + block + src[src.index(END) + len(END):]
    TARGET.write_text(out, encoding="utf-8")
    py_compile.compile(str(TARGET), doraise=True)
    print(f"rebaked {len(baked)} replays, retrieved_at={stamp}")


if __name__ == "__main__":
    main()
