#!/usr/bin/env python3
"""Render (and optionally apply) the recipe_executions lifecycle table DDL.

The DDL is GENERATED from recipe_lifecycle.py — edit that module, then
re-render here — the same discipline as scripts/render_identity_views.py, and
for the same reason: a hand-carried migration drifts from the module that
owns the semantics (the LIVE≠repo-DDL class this repo has hit on
interconnect_queue and power_plants).

  python3 scripts/render_recipe_lifecycle_ddl.py               # print DDL
  python3 scripts/render_recipe_lifecycle_ddl.py --write FILE  # write migration SQL
  python3 scripts/render_recipe_lifecycle_ddl.py --apply       # execute against $DATABASE_URL

Apply uses direct psycopg2 (db_utils silently drops DDL) with plain
autocommit — every statement is CREATE ... IF NOT EXISTS, so re-running is a
no-op, and applying is CI's job (.github/workflows/apply-recipe-lifecycle.yml
holds the credentials; never run --apply from a local shell).
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from recipe_lifecycle import all_ddl_statements  # noqa: E402


def full_sql() -> str:
    return (
        "-- GENERATED by scripts/render_recipe_lifecycle_ddl.py from"
        " recipe_lifecycle.py — do not hand-edit; edit the module and"
        " re-render.\n\n"
        + ";\n\n".join(s.strip() for s in all_ddl_statements()) + ";\n")


def main() -> None:
    sql = full_sql()
    if "--write" in sys.argv:
        path = sys.argv[sys.argv.index("--write") + 1]
        with open(path, "w") as f:
            f.write(sql)
        print(f"wrote {path}")
        return
    if "--apply" in sys.argv:
        import psycopg2
        url = os.environ.get("DATABASE_URL") or os.environ.get("NEON_DATABASE_URL")
        if not url:
            sys.exit("DATABASE_URL not set")
        conn = psycopg2.connect(url, connect_timeout=15)
        conn.autocommit = True
        try:
            with conn.cursor() as cur:
                for stmt in all_ddl_statements():
                    cur.execute(stmt)
            print("applied: recipe_executions table + indexes")
        finally:
            conn.close()
        return
    print(sql)


if __name__ == "__main__":
    main()
