#!/usr/bin/env python3
"""Render (and optionally apply) the canonical agent-identity views.

mcp_calls_identity + mcp_agent_retention_30d are GENERATED from
mcp_calls_deloop constants — edit that module, then re-render here. This
script exists because the previous "re-render" was ad-hoc (the 07-01/07-10
migrations were hand-assembled and the IP-exclusion suffix was hand-carried
between them, which is exactly how the two drifted from the module).

  python3 scripts/render_identity_views.py               # print DDL
  python3 scripts/render_identity_views.py --write FILE  # write migration SQL
  python3 scripts/render_identity_views.py --apply       # execute against $DATABASE_URL

View semantics (see mcp_calls_deloop for the full rationale):
  · agent_id = md5(first XFF token) — NULL when that token is a Cloudflare
    edge POP (CF_POP_IP_REGEX): pre-2026-07-10 rows carry the worker's
    rotating egress there, so their agent identity is unknowable. NULLing at
    the view heals every COUNT(DISTINCT agent_id) consumer at once; the
    calls stay counted.
  · is_real_external = real_calls_predicate() + the IP-level self-traffic
    exclusions (Railway egress /24s + the AWS 'node' failover fleet —
    r-reach-canonical-views 2026-07-01).
  · mcp_agent_retention_30d drops NULL-agent rows (a POP is not a returning
    agent).

Apply uses direct psycopg2 (db_utils silently drops DDL) with plain
autocommit — CREATE OR REPLACE VIEW is atomic per statement.
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from mcp_calls_deloop import CF_POP_IP_REGEX, real_calls_predicate  # noqa: E402

_FIRST_TOK = "TRIM(BOTH FROM split_part(ip_address, ',', 1))"

# Non-routable / private first-hop → not a public caller. Verbatim from the
# live view (r-reach-canonical-views 2026-07-01).
_PRIVATE_IP_REGEX = (
    r"^(10\.|127\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.|169\.254\."
    r"|100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.|::1|fc|fd|0\.0\.0\.0|$)"
)

# IP-level self-traffic exclusions (r-reach-canonical-views 2026-07-01):
# Railway egress /24s (our own backend calling itself) + one AWS harness IP,
# and the pre-06-15 AWS failover fleet (bare 'node' UA on 54.*).
_SELF_IP_CLAUSES = (
    f"    AND {_FIRST_TOK} !~ '^(162\\.220\\.232\\.|152\\.55\\.17[67]\\.|50\\.18\\.85\\.20$)'\n"
    f"    AND NOT ({_FIRST_TOK} ~ '^54\\.' AND COALESCE(user_agent, '') = 'node')"
)


def identity_view_ddl() -> str:
    pred = real_calls_predicate()
    return f"""CREATE OR REPLACE VIEW mcp_calls_identity AS
 SELECT id,
    tool_name,
    platform,
    client_name,
    success,
    response_time_ms,
    ip_address,
    user_agent,
    created_at,
    session_id,
    {_FIRST_TOK} AS client_ip,
    -- agent grain guard (2026-07-19): a Cloudflare-POP first hop is NOT an
    -- agent identity — NULL it so COUNT(DISTINCT agent_id) never counts POPs.
    CASE WHEN {_FIRST_TOK} ~ '{CF_POP_IP_REGEX}' THEN NULL
         ELSE md5({_FIRST_TOK}) END AS agent_id,
    ip_address IS NOT NULL AND ip_address <> '' AND {_FIRST_TOK} !~ '{_PRIVATE_IP_REGEX}' AS is_public_ip,
    ({pred}
{_SELF_IP_CLAUSES}
    ) AS is_real_external
   FROM mcp_tool_calls;"""


def retention_view_ddl() -> str:
    return """CREATE OR REPLACE VIEW mcp_agent_retention_30d AS
 SELECT agent_id,
    min(client_ip) AS client_ip,
    min(created_at) AS first_call,
    max(created_at) AS last_call,
    count(*) AS calls,
    count(DISTINCT created_at::date) AS active_days,
    count(DISTINCT session_id) AS sessions,
    count(DISTINCT created_at::date) >= 2 AS returned_2nd_day
   FROM mcp_calls_identity
  WHERE created_at >= (now() - '30 days'::interval) AND is_public_ip AND is_real_external
    AND agent_id IS NOT NULL
  GROUP BY agent_id;"""


def full_sql() -> str:
    return (
        "-- GENERATED by scripts/render_identity_views.py from mcp_calls_deloop"
        " — do not hand-edit; edit the module and re-render.\n\n"
        + identity_view_ddl() + "\n\n" + retention_view_ddl() + "\n")


def main() -> None:
    sql = full_sql()
    if "--write" in sys.argv:
        path = sys.argv[sys.argv.index("--write") + 1]
        with open(path, "w") as f:
            f.write(sql)
        print(f"wrote {path}")
        return
    if "--apply" in sys.argv:
        import psycopg2
        url = os.environ.get("DATABASE_URL") or os.environ.get("NEON_DATABASE_URL")
        if not url:
            sys.exit("DATABASE_URL not set")
        conn = psycopg2.connect(url, connect_timeout=15)
        conn.autocommit = True
        try:
            with conn.cursor() as cur:
                cur.execute(identity_view_ddl())
                cur.execute(retention_view_ddl())
            print("applied: mcp_calls_identity + mcp_agent_retention_30d")
        finally:
            conn.close()
        return
    print(sql)


if __name__ == "__main__":
    main()
